hyperledger-cacti/cacti

- examples/simple-asset-transfer/app.js
- examples/simple-asset-transfer/corda/connector.js
- examples/simple-asset-transfer/fabric/connector.js
- examples/simple-asset-transfer/package-lock.json
- examples/simple-asset-transfer/package.json
- examples/simple-asset-transfer/quorum/api/package-lock.json
- examples/simple-asset-transfer/quorum/api/package.json
- examples/simple-asset-transfer/quorum/connector.js
- examples/simple-asset-transfer/scenarios/corda-to-fabric.js
- examples/simple-asset-transfer/scenarios/corda-to-quorum.js
- examples/simple-asset-transfer/scenarios/fabric-to-corda.js
- examples/simple-asset-transfer/scenarios/fabric-to-quorum.js
- examples/simple-asset-transfer/scenarios/quorum-to-corda.js
- examples/simple-asset-transfer/scenarios/quorum-to-fabric.js
- examples/simple-asset-transfer/scenarios/share-pub-keys.js
- examples/simple-asset-transfer/tests/connector-fabric.js
- examples/simple-asset-transfer/tests/connector-quorum.js
- package-lock.json
- package.json
Fixes #28
We'll be allowed to use the @hyperledger scope once the project
graduates from the labs.
At that point we can publish the same package contents under multiple package
scopes for each new release to spare early adopters the migration
effort.
> chore(npm): changes scope to @hyperledger-labs/

- packages/core/examples/simple-asset-transfer/quorum/api/package-lock.json
Version 1.0.3 broke the build because it insists on NodeJS 10 or higher.
The part in the lock file is what forces the transitive dependencies (web3)
to use the older version which still allows 1.0.2
"mkdirp": {
"version": "1.0.2",
"resolved": "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.2.tgz",
"integrity": "sha512-N2REVrJ/X/jGPfit2d7zea2J1pf7EAR5chIUcfHffAZ7gmlam5U65sAm76+o4ntQbSRdTjYf7qZz3chuHlwXEA=="
},
> fix(ci): lock mkdirp to 1.0.2

- packages/core/examples/simple-asset-transfer/fabric/api/.gitignore
- packages/core/examples/simple-asset-transfer/fabric/api/package-lock.json
- packages/core/examples/simple-asset-transfer/fabric/api/package.json
- packages/core/examples/simple-asset-transfer/quorum/api/package-lock.json
There's one lock file that's an exception for now:
packages/core/examples/simple-asset-transfer/package-lock.json
And the reason for it is that we install a dependency from a file packaged
by npm locally so that it's always the latest code directly from the
project folder that gets installed. The latter is necessary so that
developers can easily test code changes they made by running
the CI script.
> fix(npm-deps): adds lock files where not an issue

- docs/tutorials/simple-asset-transfer.md
- packages/core/tools/cleanup.sh
This was missing from the documentation since we containerized
the Fabric API server last week.
> docs(examples): added Fabric API image build

- README.md
Add a link to a video introduction of Cactus at the Hyperledger Forum.
The linked video is a great introduction to Cactus that I think would be helpful to have in the documentation.
Signed-off-by: Patrick-Erichsen <Patrick.Erichsen@target.com>
> Add video link to docs

- GOVERNANCE.md
This change adds a markdown file explaining the governance policies of Hyperledger Cactus.
Signed-off-by: hartm <hart.montgomery@gmail.com>
> docs(governance.md): add a document to explain Cactus governance

- packages/cactus-common/src/main/typescript/public-api.ts
- packages/cactus-common/src/main/typescript/strings.ts
This is a method that is used pretty often but not included
in the Javascript language itself.
What the method does is what you would expect, it finds
all occurrences of a substring and replaces all of them with
another one. The deafult Javascript String.replace function
only does this with the first occurrence by default so it is not
a good solution.
> feat(common): add utility class Strings with replaceAll

- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
- packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
- packages/cactus-test-tooling/src/main/typescript/http-echo/http-echo-container.ts
- packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
- packages/cactus-test-tooling/src/test/typescript/integration/besu/besu-test-ledger/constructor-validates-options.ts
- packages/cactus-test-tooling/src/test/typescript/integration/quorum/quorum-test-ledger/constructor-validates-options.ts
This makes the ledger container based integration tests pass on macOS that also leads to the CI script finally passing on Macs in general. Yaaay!
Fixes #186
Note: This also has a second commit which is purely a stylistic change so I did not want to submit yet another PR for it, but at the same time it should not be mixed together with the bug-fix itself hence I ended up with two commits in the PR and propose that both commits go in without getting squashed (e.g., hit the rebase button on the Github UI if you are merging the PR, do not squash)
cc: @jweate @sownak
> fix(test-tooling): bind test ledgers to port zero for macOS

- tslint.json
It is very easy to confuse PascalCase variables in JS/TS with classes.
We would much rather keep
lowerCamelCase for variables and PascalCase for classes
to make it easier to read the code.
fix #197
> style(tslint): ban PascalCase variables from the code

- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/besu-test-ledger-parameters.test.ts
- packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
Allows passing input arguments to the docker container running the Besu test ledger. This is useful, for example, to run Besu in different ledgers than the default one.
I've included tests that check if the ledger was successfully initialized, based on the configurations.
> test(test-tooling): parametrize besu-all-in-one container

- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
- packages/cactus-test-tooling/src/test/typescript/integration/fabric/fabric-test-ledger-v1/constructor-validates-options.ts
- tools/docker/fabric-all-in-one/Dockerfile
- tools/docker/fabric-all-in-one/README.md
- tools/docker/fabric-all-in-one/configtx.yaml
- tools/docker/fabric-all-in-one/crypto-config.yaml
- tools/docker/fabric-all-in-one/docker-compose.yml
- tools/docker/fabric-all-in-one/generate.sh
- tools/docker/fabric-all-in-one/hooks/post_push
- tools/docker/fabric-all-in-one/join_channel.sh
- tools/docker/fabric-all-in-one/start_ca.sh
- tools/docker/fabric-all-in-one/start_orderer.sh
- tools/docker/fabric-all-in-one/start_peer.sh
- tools/docker/fabric-all-in-one/supervisord.conf
Fixes #132 
Changes:
1. docker pull hyperledger/cactus-fabric-all-in-one should work after building and pushing.
2. No docker volume used.
3. A class FabricV1TestLedger in the cactus-test-tooling package added that is responsible for managing the all in one docker image (can start, stop, destroy it and allows for customization).
This is a draft PR following are pending:
1. Deploying a hello world sort of contract as Fabric contracts/chaincode are needed to be compiled on the running peer Container.
@petermetz
> feat(fabric all in one): Runs a Fabric Network in one docker container

- packages/cactus-plugin-consortium-manual/src/main/typescript/generated/openapi/typescript-axios/.openapi-generator-ignore
This ensures that the git_push.sh script is not flickering in the
git index when doing a build/re-build of the project/package
> build(plugin-consortium-manual): ignore the git_push script

- packages/cactus-common/src/main/typescript/bools.ts
- packages/cactus-common/src/main/typescript/checks.ts
- packages/cactus-common/src/main/typescript/coded-error.ts
- packages/cactus-common/src/main/typescript/public-api.ts
- packages/cactus-common/src/main/typescript/strings.ts
Utilities for easier one-liners that can verify arguments or
execution state in a much more concise way compared to
if conditions throwing manually. Makes the code less verbose
and requires less typing as well.
Also: added a bools utlity class for checking strict boolean
typing of a value and a new string utility method as well.
Fixes #266
> feat(common): Checks and CodedError classes

- karma.conf.js
- packages/cactus-common/package-lock.json
- packages/cactus-common/package.json
- packages/cactus-common/src/main/typescript/key-converter.ts
- packages/cactus-common/src/main/typescript/public-api.ts
- packages/cactus-common/src/main/typescript/signer-key-pairs.ts
- packages/cactus-common/src/test/typescript/unit/api-surface.ts
- packages/cactus-common/src/test/typescript/unit/js-object-signer.test.ts
- packages/cactus-common/src/test/typescript/unit/key-converter.test.ts
- packages/cactus-common/src/test/typescript/unit/objects/get-all-method-names.ts
This PR resolve issue #247 
This PR depend on PR #245 and #246 as it uses functionality and test from other PRs.
> feat(common): KeyConverter class to and from PEM/hex/buffe

- package-lock.json
- package.json
Instead of Hyperledger Labs, the package scope should
be just Hyperledger since we've graduated from  being
a lab into a top level project.
> chore: fix package scope  typo

- whitepaper/whitepaper.md
1. The horizontal line (---) syntax was breaking the
PDF generation process which lead to 22 pages
being excluded from the final PDF file.
Adding the new line here fixes this syntax error
and therefore the PDF build no longer has this issue.
2. Automated tooling has removed the leading space
characters from some sentences so this is
also included in this change which I considered
small and unimportant enough to just include it
in the same changeset regardless of the fact that
it is actually a different change that is not related
to the PDF generation syntax error explained in 1)
> docs(whitepaper): fix pdf syntax in section 3.8

- tools/get-package-info-list.js
- tools/validate-bundle-names.js
Adds two utility scripts that come handy when
1. Authoring build tools for the project where
the package dependency graph has to be accessed
and processed programmatically for example.
2. Wanting to validate that there are no typos in
the bundle names of packages as declared in
their package.json files (which has been a
recurring theme hence this script to automate
the checks for it).
> build(tools): pkg info and bundle validation scripts

- .github/workflows/dependent-issues.yml
Hey there :wave:,
This is an ***automated PR*** to migrate recent [DEP](https://github.com/apps/dep) App users to a new [GitHub action](https://github.com/features/actions) called [Dependent Issues]( https://github.com/marketplace/actions/dependent-issues). 
If you received this PR it means you have DEP installed on the organization level (not necessarily enabled on this repository). If you think this is a mistake, I'm sorry. Please close this PR.
* The current DEP app has _been deprecated in favor of the new [Dependent Issues](https://github.com/marketplace/actions/dependent-issues)_ Github Action and it will be removed soon.
* The new Action works the same way the bot did but with additional features/changes:
- Works with both _PRs and issues_ (disabled by default).
- Works with …
> build(github): use dependent-issues action

- whitepaper/cacts_arch.svg
- whitepaper/cactus_arch.svg
- whitepaper/whitepaper.md
This PR resolves the issue regarding out-of-date documentations.
Signed-off-by: Shingo Fujimoto <shingo_fujimoto@fujitsu.com>
> docs(whitepaper): updates on architecture diagram and terminology

- packages/cactus-core-api/src/main/typescript/plugin/plugin-registry.ts
- packages/cactus-core-api/src/test/typescript/unit/plugin-registry.test.ts
```
feat(plugin-registry): get keychain by keychainId …
be42952
Adds a utility method where I can just pass in the
keychain ID and get back a plugin instance or an
exception thrown if it was not found.
Fixes #381
```
Resolves #381
> feat(plugin registry): get keychain by keychain id

- packages/cactus-common/src/main/typescript/servers.ts
- packages/cactus-common/src/test/typescript/unit/servers.test.ts
- packages/cactus-core-api/src/main/typescript/plugin/plugin-registry.ts
- packages/cactus-core-api/src/test/typescript/unit/plugin-registry.test.ts
**Depends on #381**
Because this PR is a dependent of PR #381, by default the diff will show the full set of changes including everything from #381 and its parents changes as well. Therefore, to review this pull request please only look at the last commit (hash may change after rebasing later on)
---
Commit: 1ce14fa3fee1a723f96e5ae284bbf91a0ecb7959
Parents: be429528c14c9230bceff31db070424cea702fe2
Date: Tue Nov 10 2020 11:20:52 GMT-0800 (Pacific Standard Time) 
fix(common): servers#listen() port number validation
Fixes #383
Ensures that the when specifying port 0 the liste()
method does not throw an exception since it is
perfectly valid to bind to port zero in general. …
> fix(common): Servers#listen() port number validation

- packages/cactus-cockpit/package-lock.json
- packages/cactus-plugin-ledger-connector-besu/src/main/json/generated/openapi-spec.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/model-type-guards.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/openapi-spec.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
------------------
**<ins>This PR includes the changes required to resolve the issue #425. Please read each point of the description below carefully!</ins>**
- Reviewing this one can be done as of right now as this PR is not dependent on any other PR.
- Feel free to ask @jagpreetsinghsasan via any of your preferred communication channels for help if you get stuck using the GitHub UI or any git features during the review.
----------------------------
feat(besu): remove references to gethkeychainpassword
Primary change
--------------
1. Web3SigningCredentialType.GETHKEYCHAINPASSWORD is removed as Hyperledger Besu doesn't support the PERSONAL api
for --rpc-http-api as per the discussion mentioned here
https://chat.hyperledger.org/channel/besu-contributors?msg=GqQXfW3k79ygRtx5Q
Minor …
> feat(besu): remove references to gethkeychainpassword

- examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
- packages/cactus-core-api/src/main/typescript/public-api.ts
- packages/cactus-core/src/main/typescript/plugin-registry.ts
- packages/cactus-core/src/main/typescript/public-api.ts
- packages/cactus-core/src/test/typescript/unit/plugin-registry.test.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.test.ts
- packages/cactus-test-api-client/package.json
- packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
- packages/cactus-test-plugin-consortium-manual/package.json
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/security-isolation-via-api-server-ports.ts
- packages/cactus-test-plugin-ledger-connector-besu/package.json
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/sign-transaction-endpoint.test.ts
- packages/cactus-test-plugin-ledger-connector-quorum/package.json
- packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-via-web-service.test.ts
```
commit 6c88f647baf6f5f70e47d2634697d47498e8bed4 (refactor/core-api/move-pluginregistry-to-core-package-380)
Date:   Tue Dec 1 17:04:16 2020 -0800
refactor(core-api): move PluginRegistry to core package
Fixes #380
```
> refactor(core-api): move PluginRegistry to core package

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-test-tooling/package-lock.json
- packages/cactus-test-tooling/package.json
- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- tools/docker/fabric-all-in-one/Dockerfile_v1.4.x
- tools/docker/fabric-all-in-one/Dockerfile_v2.x
- tools/docker/fabric-all-in-one/README.md
- tools/docker/fabric-all-in-one/healthcheck.sh
- tools/docker/fabric-all-in-one/run-fabric-network.sh
- tools/docker/fabric-all-in-one/supervisord.conf
----------------------------
feat(fabric): user defined fabric samples version
Primary Change
--------------
1. The fabric-all-in-one can now accept fabric versions as
argument at runtime and corresponding code changes are incorporated.
Minor refactorings that were also necessary to accomodate 1)
2. The interface IFabricTestLedgerV1ConstructorOptions in the
class fabric-test-ledger-v1 is modified to incorporate new
variable fabricVersion. Corresponding changes are made to the
functions to include the same.
3. The client user name has been renamed from user1 to
user2 as Hyperledger Fabric 2.xversions has user1 already
registered.
4. Go has been manually setup in the Dockerfile located
at tools/docker/fabric-all-in-one/Dockerfile …
> feat(fabric): user defined fabric samples version

- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
- packages/cactus-api-client/package.json
- packages/cactus-api-client/src/main/typescript/api-client.ts
- packages/cactus-api-client/src/main/typescript/default-consortium-provider.ts
- packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
- packages/cactus-core-api/src/main/json/generated/openapi-spec.json
- packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-core-api/src/main/typescript/openapi-spec.ts
- packages/cactus-core/src/main/typescript/consortium-repository.ts
- packages/cactus-core/src/main/typescript/index.web.ts
- packages/cactus-core/src/main/typescript/public-api.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-consortium-jws-endpoint-v1.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-node-jws-endpoint-v1.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
- packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts
- packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/security-isolation-via-api-server-ports.ts
**<ins>This PR depends on another [PR](https://github.com/hyperledger/cactus/pull/408) to ensure that the authors are not blocked in performing their work while waiting for the pull request to get reviewed. Please read the each point of the description below carefully!</ins>**
- It is strongly recommended that you review the parent PR first before reviewing this one because once that one (parent PR) is merged, this can be rebased onto the main branch which will literally disappear the additional commits that are shown in this PR but actually belong to the parent PR
- Before this one can be merged, #408 has to be approved and merged first.
- Reviewing this one can be done as of right now by looking at the changes made specifically by the single commit that this branch commits on top of the …
> refactor(core-api): normalize consortium data model

- package.json
- packages/cactus-core-api/package.json
- packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-core-api/src/main/typescript/openapi-spec.ts
- packages/cactus-plugin-consortium-manual/package.json
- packages/cactus-plugin-consortium-manual/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-plugin-ledger-connector-fabric/package.json
- packages/cactus-plugin-ledger-connector-quorum/package.json
This changes makes it so that model properties named `protected` will
no longer get mangled by the OpenAPI generator into `_protected`.
This is needed so that our generated models can be compliant with the
JWS RFC [1]
Since `protected` is only a softly reserved keyword, this means that
you can still declare classes/interfaces with fields that are called
`protected` which is what we need since the RFC mentioned above
declares exactly that for JWS recipients.
[1]: https://tools.ietf.org/html/rfc7515
Fixes #436
> fix: Open API generator config - protected keyword

- packages/cactus-core-api/src/main/json/generated/openapi-spec.json
- packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-core-api/src/main/typescript/openapi-spec.ts
**<ins>This PR depends on another [PR](https://github.com/hyperledger/cactus/pull/409) to ensure that the authors are not blocked in performing their work while waiting for the pull request to get reviewed. Please read the each point of the description below carefully!</ins>**
- It is strongly recommended that you review the parent PR first before reviewing this one because once that one (parent PR) is merged, this can be rebased onto the main branch which will literally disappear the additional commits that are shown in this PR but actually belong to the parent PR
- Before this one can be merged, #409 has to be approved and merged first.
- Reviewing this one can be done as of right now by looking at the changes made specifically by the single commit that this branch commits on top of the …
> feat(core-api): add consensus algorithms OpenAPI enum

- packages/cactus-core-api/src/main/json/generated/openapi-spec.json
- packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-core-api/src/main/typescript/openapi-spec.ts
- packages/cactus-core-api/src/main/typescript/plugin/ledger-connector/i-plugin-ledger-connector.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
**<ins>This PR depends on another [PR](https://github.com/hyperledger/cactus/pull/414) to ensure that the authors are not blocked in performing their work while waiting for the pull request to get reviewed. Please read the each point of the description below carefully!</ins>**
- It is strongly recommended that you review the parent PR first before reviewing this one because once that one (parent PR) is merged, this can be rebased onto the main branch which will literally disappear the additional commits that are shown in this PR but actually belong to the parent PR
- Before this one can be merged, #414 has to be approved and merged first.
- Reviewing this one can be done as of right now by looking at the changes made specifically by the single commit that this branch commits on top of the …
> feat(core-api): getConsensusAlgorithmFamily() on connector API

- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
This must've slipped in during a recent refactor.
Fixes #453
> fix: reverting accidental manual change in generated code

- .github/workflows/ci.yml
Before this change the only time the CI would get executed was when
a pull request was submitted against the $DEFAULT branch. After this
the CI will run for every commit and pull request that is issued against
the any branches.
The specific reason for this change is that we introduced a new branch
called dev which can be used to provide early access to pending changes
that may or may not be stuck in the review queue for longer periods of
time. Of course there's an additional overhead in maintaining this
dev branch by way of cherry picking and rebasing, but this is minor
compared to the positive effects it can bring to the community.
Fixes #434
> ci(github-workflows): launch CI on PR & push for all branches

- packages/cactus-common/src/main/typescript/servers.ts
Adds more type assertions to check if the
provided port number is indeed a finite,
positive integer.
Fixes #491 
(cherry picked from commit 3b16aeb4ba0932c52766fcd365fe14b7319bbed2)
> fix(common): servers.listen() port validation

- package-lock.json
- package.json
This commit is necessary because of a rebase that
happened on the fork where the webpack feature we
need was implemented. The rebase changed the commit
sha and therefore made that version of the code
disappear too. To avoid this issue happening again
in the future a dedicated branch was created on the
fork which will not be touched by future rebases
that are necessary for the pull request to be kept
up to date with the main branch of webpack itself.
The so called backup branch mentioned above is called
cactus-webpack-ignore-require-calls-feature which
you can see being specified in the package.json.
Fixes #506
> fix(package-json): invalid webpack commit sha #506

- packages/cactus-plugin-ledger-connector-besu/package-lock.json
- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-plugin-ledger-connector-fabric/package-lock.json
- packages/cactus-plugin-ledger-connector-fabric/package.json
- packages/cactus-plugin-ledger-connector-quorum/package-lock.json
- packages/cactus-plugin-ledger-connector-quorum/package.json
The previous commit attempting to do the same thing
somehow did not achieve the expected outcome meaning
that there were still leftovers of other versions of axios.
For reference: CVE-2020-28168
Fixes #449
Depends on #506 #507
> build(deps): upgrade axios to 0.21.1 due to high severity CVE #449

- packages/cactus-plugin-ledger-connector-fabric/package-lock.json
- packages/cactus-plugin-ledger-connector-fabric/package.json
Fixes #498 
```sh
commit 5431c4708e842fb4c8384882bd4d5e02f7bef045
Date:   Fri Jan 15 11:44:33 2021 -0800
chore(deps): specify explicit bl version 1.2.3 in fabric plugin
This is necessary so that we can resolve the issue of us
being susceptible to this CVE:
https://github.com/advisories/GHSA-pp7h-53gx-mx7r
Fixes #498
```
Depends on #506
> chore(deps): fabric connector upgrade bl

- .dcilintignore
- CONTRIBUTING.md
- GOVERNANCE.md
- codeql-analysis.yml
- packages/cactus-api-client/src/main/typescript/api-client.ts
- packages/cactus-cockpit/e2e/protractor.conf.js
- packages/ledger-plugin/fabric/validator/unit-test/fabric-docker/README.md
- tools/docker/fabric14-fabcar-testnet/README.md
- tools/docker/quorum-all-in-one/start-tessera.sh
- whitepaper/whitepaper.md
Also adds a .dcilintignore file to specify which files are
not possible to change without breaking third party dependencies.
TODO: If and when these dependencies get swapped out or they
release new versions with inclusive language, we'll need to
update them accordingly and the ignore file as well.
Fixes #514
> fix: dci lint errors #514

- packages/cactus-common/src/main/typescript/servers.ts
Extends the existing functionality of the utility method so that it can
accept a 'host' parameter where callers can
specify if they want to bind to the wildcard
network interface of `0.0.0.0` for example.
The default option of the host argument is
localhost so that we are *secure by default*
even if this method is only used for testing
code, it cannot hurt to be on the safe side.
Fixes #527
> feat(common): servers.startOnPort() host arg #527

- packages/cactus-plugin-consortium-manual/package-lock.json
- packages/cactus-plugin-consortium-manual/package.json
- packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-node-jws-endpoint-v1.ts
- packages/cactus-plugin-keychain-memory/package-lock.json
- packages/cactus-plugin-keychain-memory/package.json
Adds the missing dependency "uuid" to the packages where applicable.
Fixes #529
> fix(deps): missing uuid from plugins #529

- .dockerignore
- README.md
- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app-cli.ts
- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
- examples/supply-chain-app/.dockerignore
- examples/supply-chain-app/Dockerfile
- examples/supply-chain-app/README.md
- examples/supply-chain-app/healthcheck.sh
- examples/supply-chain-app/hooks/post_push
- examples/supply-chain-app/supervisord.conf
Depends on #526 
Depends on #528 
Depends on #530 
```sh
docs(examples): containerize supply-chain-app
Uses a Docker-in-Docker container to run the supply
chain app example which itself has functionality that
spawns docker containers to host the AIO ledger images.
This makes it a 100% turn-key way of providing examples
to anyone who have at least the ability to run docker
containers built for the linux amd64 platform.
Fixes #486
```
> docs(examples): containerize supply-chain-app #344

- examples/cartrade/README.md
> fix(example): fix README on examples/car-trade

- packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
1. the "consortium" property has been renamed to "consortiumDatabase"
when we normalized the data structure of the in-memory
storage of the manual consortium plugin.
2. instanceId and keychainId properties were missing
These are also properties that were recently added to
all constructors and the generator was not updated.
TODO: leverage the compiler to make it impossible to
make these user errors when updating the plugin
constructor interface and forgetting to update the
generator at the same time. The build should fail in
cases like that instead of letting the CI pass.
Fixes #598
> fix(cmd-api-server): config generator emits correct type

- tools/docker/fabric-all-in-one/Dockerfile_v1.4.x
- tools/docker/fabric-all-in-one/Dockerfile_v2.x
- tools/docker/fabric-all-in-one/README.md
Fixes #631
The root user account was locked (assuming by default)
so had to give it a password just so that we can log
in with it via SSH.
Since we don't actually plan on using the root password
I just set it to a UUID to make it a little less trivial
to recover it (which shouldn't matter anyway since we
strictly advise against using the AIO images in production
anyway).
> fix(tools): fabric all-in-one SSH access denied #631

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
fix(fabric): issue with mulitple objects of prometheus metrics
Primary Change
--------------
1. Adding the default_metrics to the registry object which will differ for different objects.
Resolve #634
Signed-off-by: Jagpreet Singh Sasan <jagpreet.singh.sasan@accenture.com>
> fix(fabric): issue with multiple objects of prometheus metrics

- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- tools/docker/fabric-all-in-one/supervisord.conf
This commit is meant to make it much easier to debug
issues with the Fabric 2.x AIO container image in the
future when new bugs (inevitably) arise.
Meaning that the logs of the child processess such as
the fabric network creator script or the docker daemon will
all be piped through to the logs of the container itself
instead of just being dumped into log files under
/var/log/... which has the upside of not having to
shell into the container when something goes wrong
and one wishes to debug what happened. Instead the
logs of the container will show all the information
right away.
In addition to the above change a flag was added to
the FabricTestLedger class' constructor options so
that one  can tell the class to dump the continer's
log stream straight onto it's own logger meaning
that now …
> fix(tools): fabric AIO image log access in CI #643

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- tools/docker/fabric-all-in-one/supervisord.conf
Depends on #644 
Added a docker resource pruning call to the
test case that was triggering the disk full issue
while pulling the Fabric AIO image necessary
for it's operation.
It is expected that this error will crop up in the future with different test cases and if and when that
happens we can add more of the same to
those tests as well, but for now, I did not want to
make this change to every single test case since
it wasn't strictly necessary and a better solution may
come along in the near future as well.
Fixes #641
> fix(ci): github action runner disk full error #641

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- tools/docker/fabric-all-in-one/Dockerfile_v2.x
- tools/docker/fabric-all-in-one/README.md
- tools/docker/fabric-all-in-one/healthcheck.sh
- tools/docker/fabric-all-in-one/run-fabric-network.sh
- tools/docker/fabric-all-in-one/supervisord.conf
Depends on #644
Depends on #645
Fixes #632 
Primary change
============
Not sure how exactly, but the rug got pulled from under our
image build despite it specifying all tags/versions for fabric
explicitly. Suspicion right now is that the release tags were force
pushed to something new which no longer supported the fabcar
example chaincode that we were depending on.
Evidence to the above is also that our old image works just fine
that was built back in December 2020 (who knew 2020 was
going to be the year we depend on for stability...)
The fix itself: Migrated over the image to be compatible with
the 2.x fabric-samples code which meant no more fabcar
instead of which we now have the basic asset transfer
chaincode that gets deployed by default and then also serves
as the backbone for the …
> fix(tools): fabric AIO fabric-samples v2.2.0 breaking change #632

- packages/cactus-plugin-ledger-connector-fabric/package-lock.json
- packages/cactus-plugin-ledger-connector-fabric/package.json
- packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/chain-code-compiler.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-source/deploy-contract-go-source-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/unit/chain-code-compiler.test.ts
- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- tools/docker/fabric-all-in-one/Dockerfile_v2.x
- tools/docker/fabric-all-in-one/README.md
- tools/docker/fabric-all-in-one/healthcheck.sh
- tools/docker/fabric-all-in-one/run-fabric-network.sh
- tools/docker/fabric-all-in-one/supervisord.conf
Depends on #644
Depends on #645
Depends on #646
Primary change
=============
Finally adds real support for chain code deployment with
custom made contracts not just the ones that the fabric
samples container comes pre-built with.
Additional notes, changes
========================
1. Makes assumptions about the ledger being containerized the
same way the fabric-samples repo does it, e.g. there must
be a container called "cli" which is set up to execute the peer
binary and to be able to perform go builds with a version of
go that has go modules support (1.11+ IIRC)
2. Does not yet support Fabric 2.x (at least it was not tested)
3. Magic strings in the connector that still need to be eliminted.
4. Go mod file upload is not supported, for now one must use the
pinned dependencies array to lock …
> feat(fabric-connector): contract deployment endpoint #616

- .github/workflows/ci.yml
- package.json
Provides a workaround to avoid having to deal
with the issue of the Fabric AIO image not using
randomized host ports by marking the test cases
that use said docker image as 'parallel not ok'
for the tap test runner meaning that all the tests
will run parallel except for these ones for Fabric.
Fixes #416
> fix(performance): parallel test execution #416

- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/.openapi-generator/FILES
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/api/ApiPluginLedgerConnectorCorda.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/api/ApiPluginLedgerConnectorCordaService.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/ListFlowsV1Request.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/ListFlowsV1Response.kt
- packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
Adds an endpoint that responds with the Corda RPC
proxies similarly named method's return value (e.g. the list of flows)
As an example return value, please observe this JSON array:
```json
[
"net.corda.core.flows.ContractUpgradeFlow$Authorise",
"net.corda.core.flows.ContractUpgradeFlow$Deauthorise",
"net.corda.core.flows.ContractUpgradeFlow$Initiate",
"net.corda.finance.flows.CashExitFlow",
"net.corda.finance.flows.CashIssueAndPaymentFlow",
"net.corda.finance.flows.CashIssueFlow",
"net.corda.finance.flows.CashPaymentFlow",
"net.corda.finance.internal.CashConfigDataFlow",
"net.corda.samples.obligation.flows.IOUIssueFlow",
"net.corda.samples.obligation.flows.IOUSettleFlow",
"net.corda.samples.obligation.flows.IOUTransferFlow",
"net.corda.samples.obligation.flows.SelfIssueCashFlow"
]
``` …
> feat(corda-connector): list flows endpoint #624

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/prometheus-exporter/data-fetcher.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
--------------------------------
fix(fabric): prometheus exporter metrics naming	
Primary Change
--------------
1. Change the cactus_fabric_total_tx_count metric name to be fetched from a variable
2. Update the same in the test cases
Signed-off-by: Jagpreet Singh Sasan <jagpreet.singh.sasan@accenture.com>
> fix(fabric): prometheus exporter metrics naming

- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
Primary change
-----------------------
Adds request and response definitions to
the pruneDockerResources() method to
allow callers to control the log levels
and also to get a complete report of the
pruning processes' outcome from the
returned object instead of just returning
with `void`.
Miscellaneous changes
----------------------------------
Significantly improved the documentation
for the utility method in question.
Fixes #694
> feat(test-tooling): pruneDockerResources() observability #694

- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/main/typescript/github-actions/is-running-in-github-action.ts
- packages/cactus-test-tooling/src/main/typescript/github-actions/prune-docker-all-if-github-action.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
Depends on #695 
feat(test-tooling): utility function docker prune in GH action #696
Primary change
--------------
Added a convenience function that tests can call in order to easily
get rid of dangling docker resources that could be eating up the
file system's available space on disk (which is an issue that we've
started hitting more and more as we kept increasing the number
of test cases that use containers for end to end testing).
A good problem to have but nevertheless it is a problem that we
need to be vigilant about cleaning up after our test cases to avoid
overusing the resources of the CI runner.
Miscellaneous change(s)
-----------------------
Also added another utility function to determine if the current code
is being executed in a GitHub Action Workflow runner or not.
The …
> feat(test-tooling): utility function docker prune in GH action #696

- packages/cactus-plugin-ledger-connector-corda/README.md
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/.openapi-generator/FILES
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/api/ApiPluginLedgerConnectorCorda.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/api/ApiPluginLedgerConnectorCordaService.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/CordappInfo.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/DiagnoseNodeV1Request.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/DiagnoseNodeV1Response.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/NodeDiagnosticInfo.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/SHA256.kt
- packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
Depends on #655 
The Corda RPC proxy has a diagnostics method that we
exposed here as an endpoint for our own connector as well.
This will help tremendously in debugging things when
people are working with the corda connector
(speaking from experience here).
Fixes #623
> feat(corda-connector): node diagnostics endpoint #623

- packages/cactus-plugin-keychain-vault/README.md
- packages/cactus-plugin-keychain-vault/package-lock.json
- packages/cactus-plugin-keychain-vault/package.json
- packages/cactus-plugin-keychain-vault/src/main/json/openapi.json
- packages/cactus-plugin-keychain-vault/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/prometheus-exporter/data-fetcher.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/prometheus-exporter/response.type.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint-v1.ts
- packages/cactus-plugin-keychain-vault/src/test/typescript/integration/plugin-keychain-vault.test.ts
Commit to be reviewed
------------------------------
feat(keychain-vault): add prometheus metrics	
Primary Change
--------------
1. The keychain-vault plugin now includes the prometheus metrics exporter integration
4. IPluginKeychainVaultOptions interface in PluginKeychainVault class now has a prometheusExporter optional field
5. The PluginKeychainMemory class has relevant functions and codes to incorporate prometheus exporter
6. Added Readme.md on the prometheus exporter usage
Resolve #536
Signed-off-by: …
> feat(keychain-vault): add prometheus exporter

- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
- packages/cactus-test-tooling/src/main/typescript/corda/corda-test-ledger.ts
feat(test-tooling): add corda AIO emitContainerLogs option
This is the same thing that we added to the Fabric
AIO image earlier:
Setting the flag controls whether the CordaTestLedger
class will automatically pipe the container's own logs onto the logger object of the
class instance (CordaTestLedger) or not.
By default it does pipe the logs but if it gets spammy
developers can turn it off via the flag to avoid
having to scroll through thousands of lines of
logs that may or may not be useful to them.
> feat(test-tooling): add corda AIO emitContainerLogs option

- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
- packages/cactus-test-tooling/src/main/typescript/corda/corda-test-ledger.ts
Depends on #688
fix(test-tooling): uncomment code that was forgotten
During testing it was easier and faster to have the
cordapp building process commented out because
the obligation cordapp is pre-built within the
container image of AIO Corda, then it was forgotten
like that which is not good because the rest of the examples
are not pre-built and therefore don't actually work
without this line being uncommented.
> fix(test-tooling): uncomment code that was forgotten

- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
- packages/cactus-test-tooling/src/main/typescript/corda/corda-test-ledger.ts
- tools/docker/corda-all-in-one/supervisord.conf
Depends on #688
Depends on #689
Author Date: 2021-03-14 16:06:54 -0700
Committer Date: 2021-03-14 16:11:09 -0700 
fix(tools): corda AIO supervisorctl configuration
While trying to use the supervisorctl binary
to manage the starting of the corda-network
process configured in supervisord.conf the
following error was encountered and then
fixed by this change:
$ supervisorctl -c /etc/supervisor/supervisord.conf
Error: .ini file does not include supervisorctl section
For help, use /usr/bin/supervisorctl -h
> fix(tools): corda AIO supervisorctl configuration

- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
- packages/cactus-test-tooling/src/main/typescript/corda/corda-test-ledger.ts
- tools/docker/corda-all-in-one/Dockerfile
- tools/docker/corda-all-in-one/supervisord.conf
Depends on #688
Depends on #689
Depends on #690
Author Date: 2021-03-14 17:17:35 -0700
Committer Date: 2021-03-14 18:51:05 -0700 
feat(tools): add standalone shell CLI tool to corda AIO image
The corda AIO docker image now downloads
the CLI tools jar for the standalone shell at
build time.
By default it downloads the 4.5 version of the
jar but this can be altered to any other version
through a dedicated build argument of the
container image definition.
The image built from this commit is also tagged
(on top of the automatic tagging script) as
hyperledger/cactus-corda-4-6-all-in-one-obligation:2021-03-14-standalone-corda-shel …
> feat(tools): add standalone shell CLI tool to corda AIO image

- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
- packages/cactus-test-tooling/src/main/typescript/corda/corda-test-ledger.ts
- tools/docker/corda-all-in-one/Dockerfile
- tools/docker/corda-all-in-one/healthcheck.sh
- tools/docker/corda-all-in-one/supervisord.conf
Depends on #688
Depends on #689
Depends on #690
Depends on #691
Author Date: 2021-03-15 16:06:41 -0700
Committer Date: 2021-03-15 16:14:59 -0700 
fix(tools): corda AIO healthcheck ignores jolokia errors
The healthcheck script did not fail on curl returning
a non-zero exit code because the bahs script that
does the healthcheck was not configured to do so
leaving the healthcheck essentially broken.
Added the set -e line to the healthcheck to ensure
that this does not happen (it makes the whole script
fail as soon as any command within the script
does so which is what we want from the healthcheck
script)
Tagged in the …
> fix(tools): corda AIO healthcheck ignores jolokia errors

- packages/cactus-common/src/main/typescript/servers.ts
- packages/cactus-common/src/test/typescript/unit/servers.test.ts
fix(common): servers#startOnPreferredPort no graceful fallback #683
The code of the method was not waiting for a promise to resolve
which was masking the underlying exception that the code
was supposed to catch and examine in order to determine if
it should perform a fallback of binding to port zero or not.
Fixed it by making sure the initial try of the preferred port
allocation is awaited for so that the exception is thrown
where it is expected by the algorithm.
Fixes #683
> fix(common): servers#startOnPreferredPort no graceful fallback #683

- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/invoke-contract-v2.test.ts
Adds new parameters to the run transaction endpoint's request object
that allow the caller to specify a the consistency strategy
parameters that can define if the connector should wait for either:
1. the transaction to be confirmed only by the node's transaction pool
2. if at least the block containing the transaction should be mined
by the ledger
3. an N number of additional blocks should be confirmed by the ledger
in **addition** to the block that contained the transaction.
The parameters also allow to specify a timeout in milliseconds that
if unspecified defaults to the maximum safe integer that Javascript
can represent which for practical purposes we consider to be the
same as waiting until the heat death of the universe or infinity.
Fixes #685 …
> feat(connector-besu): request param: wait for ledger tx receipt #685

- packages/cactus-cmd-api-server/README.md
Author Date: 2021-03-24 17:26:14 -0700
Committer Date: 2021-03-24 17:30:45 -0700 
docs(cmd-api-server): finish writing the readme file #341
Added a README file for the API server equipped with
a table of contents, usage examples and an FAQ.
Also took some parts of the whitepaper that talk about
the node and API server deployment scenarios which are
of course very relevant here.
Fixes #341
> docs(cmd-api-server): finish writing the readme file #341

- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/JsonJvmObjectDeserializer.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/NodeRPCConnection.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/DeployContractJarsV1Request.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/JvmType.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/start-app.sh
- packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
- packages/cactus-test-tooling/src/main/typescript/corda-connector/corda-connector-container.ts
Depends on #666 
Date: 2021-03-24 22:33:40 -0700 
feat(corda-connector): params factory pattern support #620
Primary change
============
Added support in the Corda ledger connector plugin's JVM backend to
have the JSON DSL be able to express static and non-static factory
functions.
For the non-static factory functions, the invocation target can be any
constructable object that the DLS can express via the JvmObject type.
The method lookups are performed the same way as when looking up
constructors but with the additional constraint that the name of the
method has to also match not just the parameter types/count.
Miscellaneous changes
==================
Refactored …
> feat(corda-connector): params factory pattern support #620

- packages/cactus-plugin-ledger-connector-fabric/package-lock.json
- packages/cactus-plugin-ledger-connector-fabric/package.json
The dependency was removed accidentally during a refactor
where we deprecated the chain code compiler component
in its current form (ngo is a depenency of that). Later on
they are both scheduled to depart from the codebase (ngo
and the chain code compiler) but that will be part of a larger
refactor so for now I just added the missing dependency back
to ensure that the `./tools/ci.sh` script doesn't crash when
it runs the production build (the one that bundles with
webpack and minifies it as well)
Fixes #673
> fix(tools): prod build fail due to missing dependency ngo #673

- packages/cactus-plugin-ledger-connector-besu/README.md
- packages/cactus-plugin-ledger-connector-besu/package-lock.json
- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/prometheus-exporter/data-fetcher.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/prometheus-exporter/response.type.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
------------------------------
feat(besu): prometheus exporter metrics integration
Primary Change
--------------
1. The besu ledger connector plugin now includes the prometheus metrics exporter integration
4. IPluginLedgerConnectorBesuOptions interface in PluginLedgerConnectorBesu class now has a prometheusExporter optional field
5. The PluginLedgerConnectorBesu class has relevant functions and codes to incorporate prometheus exporter
6. Added Readme.md on the prometheus exporter usage
Fixes #533
Signed-off-by: …
> feat(besu): add prometheus exporter

- packages/cactus-plugin-ledger-connector-quorum/README.md
- packages/cactus-plugin-ledger-connector-quorum/package-lock.json
- packages/cactus-plugin-ledger-connector-quorum/package.json
- packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/prometheus-exporter/data.fetcher.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/prometheus-exporter/response.type.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.test.ts
feat(quorum): prometheus exporter metrics integration
Primary Change
--------------
1. The quorum ledger connector plugin now includes the prometheus metrics exporter integration
4. IPluginLedgerConnectorQuorumOptions interface in PluginLedgerConnectorQuorum class now has a prometheusExporter optional field
5. The PluginLedgerConnectorQuorum class has relevant functions and codes to incorporate prometheus exporter
6. Added Readme.md on the prometheus exporter usage
Fixes #534 …
> feat(quorum): add prometheus exporter

- tools/ci.sh
Depends on #713
Depends on #674 
Author Date: 2021-03-24 15:19:59 -0700
Committer Date: 2021-03-24 17:42:51 -0700 
fix(tools): ci.sh wsl2 lsmem does not support memory blocks #556
Added a fallback || true suffix to the lsmem, lscpu and smem commands
which are used by the ci.sh script to dump diagnostic information about
the hardware of the CI runner prior to actually proceeding with the
execution of the full build+test suite.
The existing guards examining the presence of the lsmem binary were
not enough because the lsmem binary is indeed present on WSL 2
Ubuntu, it just does not work as intended (exit code is non-zero which
crashes the ci.sh script by design)
Fixes #556 …
> fix(tools): ci.sh wsl2 lsmem does not support memory blocks #556

- packages/cactus-plugin-consortium-manual/README.md
- packages/cactus-plugin-consortium-manual/package-lock.json
- packages/cactus-plugin-consortium-manual/package.json
- packages/cactus-plugin-consortium-manual/src/main/json/openapi.json
- packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-node-jws-endpoint-v1.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-prometheus-exporter-metrics-endpoint-v1.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/prometheus-exporter/data-fetcher.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/prometheus-exporter/response.type.ts
- packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts
feat(consortium-manual): add prometheus exporter
Primary Change
--------------
1. The consortium-manual plugin now includes the prometheus metrics exporter integration
4. IPluginConsortiumManualOptions interface in PluginConsortiumManual class now has a prometheusExporter optional field
5. The PluginConsortiumManual class has relevant functions and codes to incorporate prometheus exporter
6. get-node-jws-endpoint-v1.test.ts is changed to incorporate the prometheus exporter
7. …
> feat(consortium-manual): add prometheus exporter

- .github/workflows/ci.yml
- tools/ci.sh
Depends on #674
ci: use tools/ci.sh in Github Actions #497
While we were getting to know the GitHub Actions CI runner
we temporarily stopped using the tools/ci.sh script
to run the tests, but now that we are properly
familiarized with GHA and it's quirks, it is time to
go back to the good old script we've been using before migrating
over to GHA for CI.
Fixes #497
> ci: use tools/ci.sh in Github Actions #497

- packages/cactus-cmd-api-server/README.md
- packages/cactus-cmd-api-server/package-lock.json
- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-api-server/src/main/json/openapi.json
- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-cmd-api-server/src/main/typescript/prometheus-exporter/data-fetcher.ts
- packages/cactus-cmd-api-server/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-cmd-api-server/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-cmd-api-server/src/main/typescript/prometheus-exporter/response.type.ts
- packages/cactus-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
- packages/cactus-plugin-consortium-manual/README.md
- packages/cactus-plugin-keychain-memory/README.md
feat(api-server): add prometheus exporter
Primary Change
--------------
1. The api-server plugin now includes the prometheus metrics exporter integration
4. IApiServerConstructorOptions interface in ApiServer class now has a prometheusExporter optional field
5. The ApiServer class has relevant functions and codes to incorporate prometheus exporter
6. runtime-plugin-imports.test.ts is changed to incorporate the prometheus exporter
7. Added Readme.md on the prometheus exporter …
> feat(api-server): add prometheus exporter

- examples/cactus-example-supply-chain-backend/package.json
- examples/cactus-example-supply-chain-business-logic-plugin/package.json
- examples/cactus-example-supply-chain-frontend/package.json
- packages/cactus-cmd-api-server/package.json
- packages/cactus-cockpit/package.json
- packages/cactus-core-api/package.json
- packages/cactus-plugin-consortium-manual/package.json
Several packages were missing the publish configuration
from their package.json files which made them private
packages on npm by default.
I fixed the visibility manually via npm GUI but we still need
to update the package.json files to match that in version
control as well so here we go.
Fixes #753
> fix(release): package.json publish config non-public #753

- examples/supply-chain-app/Dockerfile
Remove the specific versions from the Dockerfile so that instead what
gets installed is "whatever's latest that day". This is not preferred, but
since Alpine Package Manager disappears versions of packages after
the fact, we do not have a choice but to abandon our quest for
reproducible builds in this particular instance.
Fixes #751
> fix(docs): supply chain example container image exact versions #751

- package.json
- packages/cactus-cmd-api-server/package-lock.json
- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts
- packages/cactus-test-cmd-api-server/package-lock.json
- packages/cactus-test-cmd-api-server/package.json
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
- webpack.dev.node.js
- webpack.prod.node.js
Author Date: 2021-04-02 13:32:28 -0700
Committer Date: 2021-04-02 17:06:06 -0700 
feat(api-server): ability to install plugins at runtime #764
The API server will now use npm as a dependency to install
plugin packages before trying to import them (via require())
This is helpful in being able to ship a container image that
contains the API server and does not need additional chores
to be done in order to be able to use plugins (such as
starting a new node package with its own dependencies).
The security implications here are of course that we are
pulling code form the internet at runtime and if npm's
verification method for the code fails or if the plugin
package is …
> feat(api-server): ability to install plugins at runtime #764

- examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/supply-chain-cactus-plugin.ts
- packages/cactus-cmd-api-server/package-lock.json
- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
- packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts
- packages/cactus-plugin-keychain-memory/src/main/typescript/plugin-keychain-memory.ts
- packages/cactus-plugin-keychain-memory/src/test/typescript/unit/plugin-keychain-memory.test.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault-remote-adapter.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault.ts
- packages/cactus-plugin-keychain-vault/src/test/typescript/integration/plugin-keychain-vault.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/plugin-ledger-connector-corda.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.test.ts
Primary change:
==============
Divide the endpoint installation method into two smaller
ones where the first one only instantiates the endpoints
and the other one "registers" them as-in it hooks the
endpoint up onto the ExpressJS web app object so that
it will actually be responded to as HTTP requests come
in.
Why though?
We'll need this for the authorization MVP which will
need to be able to introspect the endpoints **prior**
to them getting registered so that it can determine
authz specific parameters like "is this endpoint
secured or non-secure?" or what scopes are necessary
for this endpoint? Etc.
Additional changes:
==================
Everything else that was needed to make the project
compile again and the tests passnig (which is a lot
because this is a very central, heavily used …
> feat(core-api): decouple web service install & registration #771

- examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
- packages/cactus-cockpit/package-lock.json
- packages/cactus-plugin-keychain-memory/package-lock.json
- packages/cactus-plugin-keychain-memory/package.json
- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/invoke-contract-v2.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/invoke-contract-v2.test.ts
- packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-via-web-service.test.ts
> feat(connector-besu, connector-quorum): filesystem replaced by keychain

- tools/ci.sh
We'll likely continue using GitHub Actions for CI so the CircleCI specific
guard rails shouldn't be littering the ci.sh script to make it easier
to understand for newcomers.
> refactor(tools): clean up CircleCI guard code in ci.sh

- packages/cactus-cmd-api-server/src/main/typescript/model/is-healthcheck-response-type-guard.ts
- packages/cactus-cmd-api-server/src/main/typescript/public-api.ts
Useful for validating if an untyped object has the
API surface of a HealthCheckResponse as defined
in the OpenAPI specs of the API server.
> feat(cmd-api-server): user defined type guard isHealthcheckResponse

- packages/cactus-core/src/main/typescript/plugin-registry.ts
Very minor improvement that makes it possible for the
plugin registry to have an injectable log level for its
logger (most classes already have this in the codebase
but it was forgotten here).
> feat(core): add plugin registry log level constructor arg

- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
Without the commit timeout explicitly being specified, it
defaults to 10 seconds which is not enough for commits that
are initial ones for a chaincode because in that edge case
the chaincode gets deployed to the rest of the peers as part
of the execution of that initial transaction and this takes
longer than 10 seconds on average even on relatively strong
hardware.
The trick was figuring out that the documented default timeout
is 300 seconds but in practice it ends up somehow being 10
instead. Once the explicit timeout is specified in the connector
parameters (constructor args) the test appears to be passing.
> test(connector-fabric): explicitly specify commit timeout

- examples/cactus-example-supply-chain-backend/package.json
Increase the RAM to 4 GB for the webpack bundling process
so that it has enough to work with instead
of crashing.
Fixes #766
> fix(examples): supply chain backend bundle build RAM #766

- tools/docker/fabric-all-in-one/supervisord.conf
The extra verbose logs of the SSH daemon were useful when
debugging issues with SSHd itself but it has been stabilized
and so it is no longer helpful but rather just makes debugging other
issues harder with the spammy logs it produces so it seemed like
it was time to drop the log levels a bit. It can always be added back
later if further issues are encountered with SSHd in the container.
> refactor(tools): reduce SSHd log level in Fabric All In One image

- tools/docker/fabric-all-in-one/Dockerfile_v1.4.x
- tools/docker/fabric-all-in-one/Dockerfile_v2.x
Fabric appears to have embraced inclusive naming for their branches and
deleted the previous default branch of theirs which all the older revisions
of their bootstrap.sh script is pointing to by way of attempint to check that
branch out.
This broke our containers at runtime because the old bootstrap scripts are
now crashing due to the non-existent branch.
Updated both the 1.4.x and the 2.x dockerfiles to use the current latest
bootstrap.sh script instead in order to alleviate the problem.
> fix(tools): use latest fabric bootstrap.sh script for AIO image

- packages/cactus-cmd-api-server/src/main/typescript/cmd/cactus-api.ts
Guard against examinig the help command's presence if there's no
CLI arguments specified at all.
Fixes #794
> fix(cmd-api-server): no CLI args causes crash #794

- examples/cactus-example-supply-chain-backend/package-lock.json
- examples/cactus-example-supply-chain-business-logic-plugin/package-lock.json
- examples/cactus-example-supply-chain-business-logic-plugin/package.json
- examples/cactus-example-supply-chain-frontend/package-lock.json
- packages/cactus-cockpit/package-lock.json
- packages/cactus-common/package-lock.json
- packages/cactus-plugin-ledger-connector-besu/package-lock.json
- packages/cactus-plugin-ledger-connector-quorum/package-lock.json
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
- packages/cactus-test-api-client/package-lock.json
- packages/cactus-test-plugin-ledger-connector-besu/package-lock.json
- packages/cactus-test-plugin-ledger-connector-quorum/package-lock.json
- packages/cactus-test-tooling/package-lock.json
The updates here were automatically done by running the
`npx lerna-audit` shell command in the project root.
https://github.com/advisories/GHSA-r9p9-mrjm-926w
CVE-2020-28498
moderate severity
Vulnerable versions: < 6.5.4
Patched version: 6.5.4
The npm package elliptic before version 6.5.4 are vulnerable to Cryptographic Issues via the secp256k1 implementation in elliptic/ec/key.js. There is no check to confirm that the public key point passed into the derive function actually exists on the secp256k1 curve. This results in the potential for the private key used in this implementation to be revealed after a number of ECDH operations are performed.
> fix(deps): elliptic upgrade to >6.5.3 for CVE-2020-28498

- packages/cactus-cmd-api-server/package.json
For a production API server deployment where the testing GUI is not
needed we do not need to ship the package with all the baggage
(transitive dependencies) that the cockpit
package brings with it (UI frameworks)
> refactor(cmd-api-server): cockpit to be dev dependency only

- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- tools/ci.sh
/facepalm
Since this retry mechanism was introduced test failures
were being ignord by the CI and this will now rectify that
issue which might also start up our CI stability issues
again, but it is what it is. Had to be done.
Depends on #792
> fix(tools): ci.sh retry mechanism no longer ignores last failure

- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
Depends on #792 
Date: 2021-04-14 09:23:28 -0700 
refactor(connector-fabric): deploy go contract response
Include the complete set of SSH command outputs.
Helps with debugging in case a contract deployment goes awry.
> refactor(connector-fabric): deploy go contract response

- packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
Also adding a logger object so that the test ledger can
be a little more chatty while starting up.
Related to #780 (but does not solve it completely)
> feat(test-tooling): add besu test ledger log level constructor arg

- BUILD.md
- README.md
docs(readme): add reference to BUILD.md
BUILD.md: add GIF showcasing the watch script
We've received feedback from multiple people that long build
times are tedious and reduce general productivity which is
(probably) hindering the growth of the community so here is
a video guide (GIF) on how fast builds can be achieved by
only rebuilding what you actually changed on the package level.
It also comes with support for regenerating the code that we
don't write ourselves but use the OpenAPI generator for it instead.
All the openapi.json files are being watched by the npm run watch
script for code changes the same way that Typescript files are being
watched so this just works out of the box.
> docs(readme): add GIF showcasing the watch script

- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
This was broken by an earlier commit:
d75b9af764241ab2e10914769412201fb040b1ed
> fix(connector-quorum): web3 Contract type usage

- tools/docker/fabric-all-in-one/Dockerfile_v1.4.x
- tools/docker/fabric-all-in-one/Dockerfile_v2.x
- tools/docker/fabric-all-in-one/run-fabric-network.sh
Fixes #649
In addition to that fix it also fixes a pre-fetching bug in the 2.x
image which was stopping it from actually using the pre-fetched images
on the file-system => the directory paths had to be specified
one by one for each image that we pre-fetched, it did not
work if you specified a common parent directory where the
images were stored, so this commit provides a fix for both
1.4.x and 2.x in the sense that they both should no longer
hit DockerHub for image downloads at container startup
time, only build-time as long as the FABRIC_VERSION
env vars were not altered by the person launching the
containers (if they were then those different versions
will still have to be fetched at runtime).
The biggest net positive effect(s) of this commit:
1. Image boot will be much faster, …
> perf(tools): fabric 1.x AIO image pre-fetching #649

- examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/invoke-contract.test.ts
Previously you couldn't deploy a contract that had constructor arguments
of it's own because there was no way to pass in these.
With this improvement this is now possible.
Depends on #810
cc: @jordigiam @AzaharaC
> feat(connector-besu): contract deployment with constructor arguments

- tools/docker/fabric-all-in-one/Dockerfile_v2.x
- tools/docker/fabric-all-in-one/README.md
- tools/docker/fabric-all-in-one/run-fabric-network.sh
Depends on #826 
Author Date: Tue Apr 20 2021 23:20:06 GMT-0700 (Pacific Daylight Time)
Committer Date: Tue Apr 20 2021 23:24:44 GMT-0700 (Pacific Daylight Time) 
feat(tools): fabric all-in-one 2.x add nodejs to image
This is necessary so that the AIO image can compile Typescript
contracts down into Javascript for the NodeJS
chaincode runtime.
Tagged on DockerHub as
hyperledger/cactus-fabric2-all-in-one:2021-04-20-nodejs
> feat(tools): fabric all-in-one 2.x add nodejs to image

- CONTRIBUTING.md
New section to explain that after lerna add, sometimes it might be
necessary to reload VSCode for it to pick up the Typescript definitions
of the newly added dependency.
> docs(contributing): add Reload VSCode Window After Adding Dependencies

- tools/ci.sh
the script uses npm ci, which should not cause
any updates to the lock files, therefor currently
the git index is checked only at the end of the
script
Resolves https://github.com/hyperledger/cactus/issues/809
Signed-off-by: Hristiyan Ivanov <hristiyan.d.ivanov@gmail.com>
> test(ci): fail ci.sh if git index is not empty

- package.json
Primary change:
=============
Fixes #850 
The npm dist-tag parameter will now be set to whatever is the
current git branch checked out.
This allows for developers to work on their own feature branches
and publish their own canary releases
for every single commit as they see fit without having to wait for the
an upcoming official release.
Miscellaneous change:
The script will now make sure to run the CI script prior to issuing the
canary release so that it is guaranteed
that the canary release does not go
out unless it was made from a revision
of the code that has the tests and build passing.
> build(lerna): canary publish script dist-tag = current git branch

- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
Only attempt to set/update the networks object on the contract JSON if
it was present in the keychain, leave it alone
otherwise.
> fix(connector-besu): network update only if present in keychain

- packages/cactus-cmd-api-server/src/test/typescript/fixtures/plugin-ledger-connector-stub/plugin-ledger-connector-stub.ts
- packages/cactus-core-api/src/main/json/openapi.json
- packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-core-api/src/main/typescript/plugin/ledger-connector/i-plugin-ledger-connector.ts
- packages/cactus-core/src/main/typescript/consensus-has-transaction-finality.ts
- packages/cactus-core/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/plugin-ledger-connector-corda.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
Adding function hasTransactionFinality() on connector API, to let ledger query whether the configured consensus has transaction finality at run time.
Fixes #354
> feat(core-api): hasTransactionFinality() on connector API

- packages/cactus-test-tooling/src/main/typescript/openethereum/openethereum-test-ledger.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
We did not need to roll our own contanier image for this
so the only thing new here is the class in the test tooling
package that makes it convenient to write test cases against
OpenEthereum. The container image used by the class behind
the scenes is just the stock OpenEthereum image from DockerHub.
Fixes #851
> feat(test-tooling): add OpenEthereumTestLedger #851

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts
Depends on #841
Date: Sat Apr 24 2021 20:55:46 GMT-0700 (Pacific Daylight Time) 
feat(connector-fabric): enrollAdmin() and createCaClient()
These are methods that come in handy while working with
Fabric networks.
> feat(connector-fabric): enrollAdmin() and createCaClient()

- package-lock.json
- package.json
Allegedly fixes the strange git-cz error encountered
while running "npm run commit"
(node:11594) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at runInteractiveQuestions (//node_modules/git-cz/dist/cz.js:576:10)
at run (//node_modules/git-cz/dist/cz.js:157:11)
at exports.prompter (//node_modules/git-cz/dist/cz.js:164:3)
at //node_modules/commitizen/dist/commitizen/commit.js:598:9
at //node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16
at callback (//node_modules/graceful-fs/polyfills.js:295:20)
at FSReqCallback.oncomplete (fs.js:184:5)
Hit the same issue, multiple times with it disappearing and then resurfacing with different versions as well, made no sense.
So, I started checking other things and found out that I also …
> build: remove npm dep. commitizen to avoid git-cz conflict

- webpack.dev.node.js
- webpack.dev.web.js
- webpack.prod.node.js
- webpack.prod.web.js
Needed this because otherwise the perfectly valid Typescript code would
not compile when using TS loader in cases when multiple Cactus packages
were depending on types from certain dependencies (example both core-api
and the besu connector would depend on the socketio package and its
"Server" class would be claimed as incompatible by the TS loader
compilation process even when the source files for those types were byte
to byte the same (but the path was different to them because they
existed in different node_modules directories)
> build: webpack ts-loader transpileOnly set to true

- BUILD.md
People have been reporting concerns when the ci.sh script runs
for an hour or more on their machines (rightly so).
Thoguht it best to take it down a notch and just have BUILD.md
instruct the reader to run the configure script isntead.
> docs(build-md): swap ci.sh with npm run configure

- tools/docker/quorum-all-in-one/supervisord.conf
This makes it much easier to debug issues with the AIO container at runtime because
one does not have to shell into the container, find the log files manually and
then print them there. Instead the container just forwards the
output of Tessera and Quorum straight to it's own stdout/stderr.
> refactor(test-tooling): quorum AIO supervisord to log to stdout

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-core-api/package-lock.json
- packages/cactus-core-api/package.json
- packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts
Adds a second parameter after the epxress object. The second parameter
is a SocketIO server object which plugins will be able to use to
register their asynchronous/streaming endpoints which do not use
traditional REST nor necessarily HTTP as the transport (think websocket
or SocketIO)
Related to #297
> refactor(core-api): register web service method to accept socket io srv

- packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
With this boolean argument of the start() method of the test ledger
class one can test locally built container images that were no yet
pushed to a public docker registry.
To use it: build your docker image locally with a tag of "your-tag", then
specify this as the tag to be used and also the omitPull argument of the start
method as true which will result in your local image being used without
any attempts to pull it (which would fail).
> feat(test-tooling): quorum test ledger omit pull parameter

- package-lock.json
- package.json
This is a preliminary step in us migrating over (potentially) to use
workspaces which in theory will significantly improve the build speeds.
> chore(deps): upgrade to Typescript v.4.2.4

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
Great explanation can be found here:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html
> perf(cmd-api-server): shrink API server bundle with type-only imports

- packages/cactus-plugin-ledger-connector-corda/README.md
The hierarchy makes more sense (to me personally) this way with
the monitoring section being a level above the prometheus specific
sections.
> docs(connector-corda): added table of contents, moved monitoring section

- package-lock.json
- package.json
Previously we were using a fork of Peter's because there was a missing
feature that we needed and the PR approval in webpack took a long time
but now it has been approved and released onto the upstream so
we can just go back to using the official release channel of webpack
and that's what this commit does.
The other reason why this suddenly became so important is because
npm v7 is failing to install webpack directly from GitHub forks which
may be easy to fix with some flag to make npm ignore the SSL issues
but that's not how we roll since one of our core design principles is
secure by default.
> build(webpack): upgrade to v5.36.2

- packages/cactus-core-api/src/main/json/openapi.json
- packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
This defines a constant in the OpenAPI specification so that it can be
reused everywhere else in the code, including in the generated
documentation that we intend to create from the OpenAPI specifications
later on and also other packages in the Typescript code who import the
core-api package.
Related to #297
> feat(core-api): add SocketIoConnectionPathV1 constant to OpenAPI specs

- examples/cartrade/README.md
- examples/cartrade/TransactionEthereum.ts
- packages/ledger-plugin/ValidatorAuthentication.ts
- packages/ledger-plugin/go-ethereum/validator/src/core/bin/www.ts
- packages/ledger-plugin/go-ethereum/validator/src/dependent/ServerPlugin.ts
- packages/ledger-plugin/go-ethereum/validator/unit-test/validatorDriver_getNonceHex.ts
- packages/ledger-plugin/go-ethereum/validator/unit-test/validatorDriver_sendRawTransaction.ts
- packages/ledger-plugin/go-ethereum/validator/unit-test/validatorDriver_transferNumericAsset.ts
Related to Issue #970 
Contents:
- (main) [Validator] add getNonce as execSyncFunction on Go-Ethereum Validator in order to solve #970.
- (sub) [car-trade] refactor to use the above function instead of web3 function.
> feat(Go-Ethereum Validator): add getNonceHex on Go-Ethereum Validator

- packages/cactus-core-api/package-lock.json
- packages/cactus-core-api/package.json
- packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts
Depends on #897 
Author Date: 2021-05-01 16:49:48 -0700
Committer Date: 2021-05-01 17:13:43 -0700 
perf: leverage import type syntax to save on bundle size
We can exclude ExpressJS from the core-api bundles because it is
designed to only ship interfaces for re-use by other packages.
> perf: leverage import type syntax to save on bundle size

- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-invoke-contract.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
Refactored how tests are named so that we can start having a support
matrix backed by tests for each permutation needed.
The used Quorum version is encoded in the beginning of the
test case file name to make them easy to tell apart in logs.
Fixes https://github.com/hyperledger/cactus/issues/901
> feat(connector-quorum): support v21.4.1 and Tessera 21.1.1 #901

- packages/cactus-test-tooling/package-lock.json
- packages/cactus-test-tooling/package.json
- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/test/typescript/integration/common/containers.test.ts
This helper is designed to be used by test cases to dump (hopefully)
useful information about the docker daemon of the CI runner in
the event of a test failure.
The idea is that we could potentially nail down the source of the the
flake we have with the Fabric end to end tests where the AIO container
fails to start due to unavailable ports.
Using this to dump information in the tests should at least get us
closer to the solution to stomping that flake at last.
Also fixed spelling errors that were introduced by a previous commit.
In the future these kind of issues will be made impossible by the
new PR merge constraint that we had just introduced (see the mailing
list post at the time of this writing)
> feat(test-tooling): containers#logDiagnostics() utility method

- packages/cactus-cmd-api-server/src/main/typescript/config/self-signed-pki-generator.ts
The test verifying mTLS support was failing on NodeJS v16
with the error below which was traced back to the fact that
the URL constructor fails with "localhost" as an input at the
verify server identity phase.
This seems like a bug in NodeJS, but maybe it works as intended.
TypeError [ERR_INVALID_URL]: Invalid URL: localhost
at new NodeError (node:internal/errors:363:5)
at onParseError (node:internal/url:537:9)
at new URL (node:internal/url:613:5)
at node:tls:247:21
at Array.forEach (<anonymous>)
at Object.checkServerIdentity (node:tls:243:5)
at TLSSocket.onConnectSecure (node:_tls_wrap:1551:27)
at TLSSocket.emit (node:events:365:28)
at TLSSocket._finishInit (node:_tls_wrap:952:8)
at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:723:12) …
> fix(cmd-api-server): drop URI type alt name from self signed TLS cert

- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-invoke-contract.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
- packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts
Depends on #993 
Date: Fri May 28 2021 00:04:09 GMT-0700 (Pacific Daylight Time) 
test: container shutdown hook prior to starting
Figured out from the additional logs we recently added that
the reason why the Fabric 1.4.x AIO image fails to start for
the 1.4.x tests is because a previously ran test (2.x)
crashes and never stops it's container which then ends up
hogging the ports which cannot be randomized for the
Fabric AIO images yet.
So, adding more logging here and also ensuring that the
test finish hooks that are responsible for shutting down
the containers are registered prior to calling
the start method on the test container classes so that
if the start method hangs …
> test: container shutdown hook prior to starting

- examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes.test.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
- packages/cactus-plugin-ledger-connector-fabric/README.md
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/unit/chain-code-compiler.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-invoke-contract.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
- packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts
- tools/docker/fabric-all-in-one/Dockerfile_v1.4.x
Depends on #993 
Date: Tue May 04 2021 14:32:33 GMT-0700 (Pacific Daylight Time)	 
test(connector-fabric): fix module requires Go 1.17 #914
Primary change:
------------------
Pinned the buggy dependency to yesterday's version
(the bug was introduced in this morning's build).
This prevents today's version from being used and
fixes the problem.
Secondary change:
--------------------
Upgraded the container image that's being used for the test to
the one that has the fabric images pre-cached.
This leads to faster test execution and lower probability
of developers getting hit by the dreaded DockerHub rate limiting issue.
Fixes #914  …
> test(connector-fabric): fix module requires Go 1.17 #914

- CONTRIBUTING.md
docs(contributing.md): explicit recommendation for avoiding global dependencies #585
Signed-off-by: Zachary Villanueva <Zachary.Villanueva@ibm.com>
Fixes #585
> docs(contributing.md): explicit recommendation for avoiding global dependencies #585

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/deploy-cc-from-golang-source.test.ts
Pinned all the hello world chaincode's dependencies to exact versions
that are known to have worked in the past for builds. We needed this
because the 1.13 go version of the Fabric CLI container could no
longer build (tidy+vendor) the dependencies that were built with the
newer versions of go such as 1.16 and 1.17.
More info about the root cause can be read here:
https://github.com/golang/go/issues/40067
By locking the dependencies versions to older ones we we ensured that
the older go installation of the Fabric CLI container does not fail.
The known-to-be-working dependency versions are coming from
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/hello-world-contract-fabric-v14/hello-world-contract-go-mod.ts …
> test(connector-fabric): fix v1.4.8 golang chaincode test

- examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
This is another step taken to win the epic battle that we have been
waging against a particularly nasty test flake that is plaguing the
Fabric tests that use the AIO ledger.
This will make the test output much more verbose, but there's no other
way around to making sure that we can narrow down the root cause of the
flake to a specific issue.
> test: add logLevel parameter to Fabric AIO ctor calls

- packages/cactus-test-tooling/src/test/typescript/integration/besu/besu-test-ledger/constructor-validates-options.ts
- packages/cactus-test-tooling/src/test/typescript/integration/quorum/quorum-test-ledger/constructor-validates-options.ts
The tests were asynchronously calling the stop and the destroy methods
which sometimes randomly crashed the test case after it successfully
passed the assertions.
Putting both stop and destroy calls in the same function and await-ing
for them one by one guarantees that this does not happen because
destroy will not get called until stop has finished.
Fixes #1052
> test: fixed race in besu, quorum test ledger teardown logic

- .devcontainer/Dockerfile
Purpose: Enable the possibility to test/build chain code modules within
the dev container in the future for development/debugging
purposes.
> build(dev-container): add GVM (go version manager)

- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
Also adds a timeout and a log level parameter to the containers#exec
utility function to improve the developer experience while
troubleshooting test failures related to containers.
> test(test-tooling): containers#pruneDockerResources prints disk usage

- package-lock.json
- packages/cactus-cmd-api-server/src/test/typescript/integration/remote-plugin-imports.test.ts
- packages/cactus-plugin-keychain-vault/package-lock.json
- packages/cactus-plugin-keychain-vault/package.json
- packages/cactus-plugin-keychain-vault/src/main/json/openapi.json
- packages/cactus-plugin-keychain-vault/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault-remote-adapter.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/delete-keychain-entry-endpoint-v1.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/get-keychain-entry-endpoint-v1.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/has-keychain-entry-endpoint-v1.ts
- packages/cactus-plugin-keychain-vault/src/test/typescript/integration/cactus-keychain-vault-server.test.ts
- packages/cactus-plugin-keychain-vault/src/test/typescript/integration/plugin-keychain-vault.test.ts
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/remote-plugin-imports.test.ts
- packages/cactus-test-tooling/package-lock.json
1. Adds the has/delete endpoints (which were missing completely)
2. Adds the get/set endpoints which were partially already implemented.
3. Moves the express dependency to be a dev dependency since we only
use the types (e.g. only needed at compile time, not at runtime)
4. Adds specific test cases to the API client verifying the
get/set/has/delete endpoints
5. Renames the getKeychainEntry and setKeychainEntry operationIDs
to have a V1 suffix.
Fixes #676
cc: @Zzocker @sichen1234
> feat(keychain-vault): add the missing endpoint classes #676

- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
When we added the prometheus monitoring endpoint to the
OpenAPI spec, the kotlin implementation was not updated
and this has lead to the container image build process failing
which was not noticed because currently the GHA CI does not
build the container images and therefore you can get away
with introducing issues to the container image build.
(this is soon to be rectified)
> fix(connector-corda): kotlin compilation error due to missing method

- .dockerignore
- README.md
- examples/carbon-accounting/Dockerfile
- examples/carbon-accounting/supervisord.conf
- examples/supply-chain-app/Dockerfile
- examples/supply-chain-app/README.md
- examples/supply-chain-app/supervisord.conf
- packages/cactus-cmd-api-server/package-lock.json
- packages/cactus-cmd-api-server/package.json
This restores the supply chain example app into a working state.
Also migrated the carbon accounting example app onto the new base
image, but that one isn't fully functional just yet (but at least the
contanier build isn't broken anymore which is already signfiicant
progress.)
The image built from this revision of the source code has been
tagged on the container registry as:
ghcr.io/hyperledger/cactus-example-supply-chain-app:2021-07-01--fix-1063-v2
Fixes #1063
(this is the second try to fix that issue, the previous one failed)
> docs(examples): migrate containers to ubuntu-20.04 Docker-in-Docker

- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/besu-get-transaction.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-balance.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-past-logs.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/invoke-contract.test.ts
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/new-contract-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/refund-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/withdraw-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint-invalid.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint-invalid.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint-invalid.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/refund-endpoint.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/withdraw-endpoint-invalid.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/withdraw-endpoint.test.ts
Fixes #1104
Signed-off-by: Hana Awad <awadhana0825@gmail.com>
> remove magic strings

- README.md
- ROADMAP.md
Depends on #656 (only so that the CI actually passes, not a code dependency since this is only a documentation change)
Date: Tue Mar 23 2021 20:41:04 GMT-0700 (Pacific Daylight Time) 
docs(roadmap.md): add roadmap with epics for next release #550
WORK IN PROGRESS
- Epics need to be created in ZenHub still
Fixes #550
> docs(roadmap.md): add roadmap with epics for next release #550

- packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/common/create-gateway.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
Introduces a new, optional (for now) parameter on the run tx
endpoint's request object called gatewayOptions which is capable
of including everything that one needs to instantiate a gateway
object of the underlying Fabric Node SDK.
This change makes it possible to not need the keychain plugin
at all when someone does not need/want it.
Fixes #1130
Depends on #1124
> feat(connector-fabric): identity json signing credentials #1130

- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-besu-record-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-record-locator.test.ts
> feat(besu): record locator

- .cspell.json
- packages/cactus-plugin-ledger-connector-fabric/package.json
- packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- yarn.lock
Makes it possible to set the endorsing peers on a transaction
when submitted through the Fabric connector.
For example these values can be passed in to the new parameter
and it will set the endorsers up accordingly prior to submitting
the transaction to the ledger:
- org1.example.com
- Org1MSP
- org2.example.com
- Org2MSP
(You only need either the org domain or the msp ID, no need
to specify both of them for it to work).
For a working example, see this test case:
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
Depends on #1123
Depends on #1130
Fixes #1122
> feat(connector-fabric): endorsing peers request arg #1122

- examples/cactus-example-carbon-accounting-backend/tsconfig.json
- examples/cactus-example-carbon-accounting-business-logic-plugin/tsconfig.json
- examples/cactus-example-supply-chain-backend/tsconfig.json
- examples/cactus-example-supply-chain-business-logic-plugin/tsconfig.json
- extensions/cactus-plugin-object-store-ipfs/tsconfig.json
- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-api-server/tsconfig.json
- packages/cactus-core-api/tsconfig.json
- packages/cactus-plugin-consortium-manual/tsconfig.json
- packages/cactus-plugin-htlc-eth-besu-erc20/tsconfig.json
- packages/cactus-plugin-htlc-eth-besu/tsconfig.json
- packages/cactus-plugin-keychain-aws-sm/tsconfig.json
- packages/cactus-plugin-keychain-azure-kv/tsconfig.json
- packages/cactus-plugin-keychain-google-sm/tsconfig.json
- packages/cactus-plugin-keychain-memory/tsconfig.json
- packages/cactus-plugin-keychain-vault/tsconfig.json
- packages/cactus-plugin-ledger-connector-besu/tsconfig.json
- packages/cactus-plugin-ledger-connector-corda/tsconfig.json
- packages/cactus-plugin-ledger-connector-fabric/tsconfig.json
- packages/cactus-plugin-ledger-connector-quorum/tsconfig.json
- packages/cactus-plugin-ledger-connector-xdai/tsconfig.json
- packages/cactus-test-plugin-htlc-eth-besu-erc20/tsconfig.json
- packages/cactus-test-plugin-htlc-eth-besu/tsconfig.json
- packages/cactus-test-plugin-ledger-connector-quorum/tsconfig.json
- tools/sync-npm-deps-to-tsc-projects.ts
- tsconfig.json
- yarn.lock
1. The ./tools/sync-npm-deps-to-tsc-projects.ts script
had a missing part in it which would fill the root
tsconfig.json file with the references to the packages
of the monorepo.
2. Point 1 could not be achieved without removing the
cactus-cockpit package from the dependencies of
cmd-api-server because the script mentioned above fails
if there are dependencies declared which do not exist
on the file-system anymore (which is exactly what
happened when we deprecated the cockpit package and then
forgot to remove it from the list of dependencies.
3. All the tsconfig.json files are updated by the sync
script (from point 1.)
4. Adds skip lib check true to the ipfs package's tsconfig
file so that the issue with uint8array dependency's own typings
don't break the build. For reference, the errors …
> build(deps): fix sync-npm-deps-to-tsc-projects tool

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-cmd-api-server/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-keychain-memory/src/main/typescript/plugin-keychain-memory.ts
- packages/cactus-plugin-keychain-memory/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-keychain-memory/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/plugin-ledger-connector-corda.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
- packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/prometheus-exporter/metrics.ts
- packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/prometheus-exporter/prometheus-exporter.ts
fix(prometheus): metrics.ts leaks to global registry #1202
1. Specified a `register` property of the gauges as an empty
array so that it does not pollute the global namespace. This
is how this is supposed to be done as per the docs of prom-client.
2. Once the change from 1) took place, the issue became that
the metrics gathering code was still trying to hit up the
global scope for the metrics, e.g. calling the get metrics
methods directly on the promClient object instead of the
registry that we create for each prmoetheus exporter object
separately. So a little additional refactor ensued to fix this
as well by making sure that we grab a reference of the registry
object at construction time and then re-use that wherever needed
instead of going through the global promClient object.
3. Added …
> fix(prometheus): metrics.ts leaks to global registry #1202

- packages/cactus-cmd-api-server/src/test/typescript/unit/config/config-service-example-config-validity.test.ts
If you don't specify port zero for the API and the cockpit then they
will default to 3000 and 4000 instead which is bad for
parallel test execution where we need guarantees not to
use potentially conflicting port numbers.
> test(cmd-api-server): randomize port in config service test

- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
- packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts
- packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/security-isolation-via-api-server-ports.ts
Removes the non-serializable consortiumRepo argument from the
constructor of the consortium plugin manual class's options.
Refactors the constructor and the internals of the plugin  to initialize
the consortium repo from the consortium database at runtime
instead of expecting it passed in via the constructor.
Refactors the internal code previously using the options.consoritumRepo
object to use this.repo instead which is what gets initalized in
the constructor as explained above.
All this leads to equivalent functionality but less boilerplate and now
thanks to this the plugin can be (should be - more tests needed)
initialized by the API server purely based on the static configuration
file when necessary.
Fixes #1199
> fix(plugin-consortium-manual): drop repo constructor arg #1199

- packages/cactus-plugin-keychain-aws-sm/src/main/typescript/plugin-keychain-aws-sm.ts
- packages/cactus-plugin-keychain-azure-kv/src/main/typescript/plugin-keychain-azure-kv.ts
- packages/cactus-plugin-keychain-google-sm/src/main/typescript/plugin-keychain-google-sm.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault-remote-adapter.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/plugin-keychain-vault.ts
- packages/cactus-plugin-keychain-vault/src/test/typescript/integration/plugin-keychain-vault.test.ts
refactor(keychain): deprecate rotateEncryptionKeys method #1108
Found 6 locations of the method:
This pull request removes the method from 6/6 locations
> deprecate rotateEncryptionKeys method #1108

- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/plugin-ledger-connector-corda.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/web-services/deploy-contract-jars-endpoint.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/web-services/diagnose-node-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/web-services/list-flows-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/web-services/network-map-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes-v4.8-express.test.ts
> fix: endpoints implementation in corda plugin

- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-xdai/src/main/typescript/plugin-ledger-connector-xdai.ts
For all the connector class definitions the implementation are fixed to
follow their interface definition and to match in consistent way for all
the connectors
Closes: #1445
Signed-off-by: Michael Courtin <michael.courtin@accenture.com>
> fix(plugin-ledger-connectors): fixes 1445 and implementing correct interface types

- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json-json-object-endpoints.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-deploy-contract-from-json-json-object-endpoints.test.ts
> fix(connector-quorum): transaction with different credentials #1098

- examples/cactus-example-supply-chain-backend/src/test/typescript/integration/supply-chain-backend-api-calls.test.ts
Made it so that the test uses a config that does not specify a config
file path to be parsed by the config service so that it does not depend
on one existing on the file system when the test gets executed.
It works fine without the .config.json file because we anyway configure
everything via code within the test.
This test started failing while I was working on the Jest/Tap co-existence
pull request so it might have something to do with the migration, but it
does not look like it.
Fixes #1516
> test: supply-chain-backend-api-calls fails without config file #1516

- tools/custom-checks/check-sibling-dep-version-consistency.ts
- tools/custom-checks/run-custom-checks.ts
With this, the `yarn custom-checks` script will go through all the
package.json files and validate the following things:
1. The top level "version" property in the package.json of the package is
set to a value that equals whatever is set as the project-wide version
of the monorepo as defined by the lerna.json file's "version" property.
(the latter gets automatically bumped by the relese process)
2. Verifies that all dependencies within each package.json pointing to
sibling packages are also using the correct version from lerna.json as
described above.
3. Same check as in 2) but for the "devDependencies" section of each
package.json file within the monorepo.
The upside of this custom check is that maintainers no longer need to
manually ensure that the version numbers are kept up to date …
> ci: custom check to verify uniform sibling dependency versions #1534

- packages/cactus-cmd-api-server/src/test/resources/cactus-dummy-package/index.js
- packages/cactus-cmd-api-server/src/test/resources/cactus-dummy-package/package.json
added a dummy package for tests about install packages from github
sources required for #1210 
> fix: added a dummy package

- .taprc
- jest.config.js
- packages/cactus-cmd-api-server/README.md
- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
- packages/cactus-cmd-api-server/src/test/typescript/benchmark/artillery-api-benchmark.test.ts
- packages/cactus-cmd-api-server/src/test/typescript/integration/jwt-endpoint-authorization.test.ts
- packages/cactus-cmd-api-server/src/test/typescript/integration/plugin-import-from-github.test.ts
- packages/cactus-cmd-api-server/src/test/typescript/integration/plugin-import-without-install.test.ts
- packages/cactus-cmd-api-server/src/test/typescript/integration/remote-plugin-imports.test.ts
- packages/cactus-cmd-api-server/src/test/typescript/unit/plugins/install-basic-plugin-consortium-manual.test.ts
- packages/cactus-cmd-api-server/src/test/typescript/unit/plugins/install-basic-plugin-keychain-memory.test.ts
- packages/cactus-cmd-api-server/src/test/typescript/unit/plugins/install-basic-plugin-ledger-connector-fabric-0-7-0.test.ts
- packages/cactus-cmd-api-server/src/test/typescript/unit/plugins/install-basic-plugin-ledger-connector-quorum-0-7-0.test.ts
- packages/cactus-core-api/src/main/json/openapi.json
- packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/README.md
- packages/cactus-plugin-ledger-connector-fabric/README.md
- packages/cactus-plugin-ledger-connector-iroha/README.md
- packages/cactus-plugin-ledger-connector-quorum/README.md
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install-version-selection.test.ts
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts
Added parameter action to PluginImport to determine if the plugin
should be installed.
Enabled feature to instantiate plugins from cactus-cmd-api-server
without install it.
Enabled feature to install packages from github
Added method create in class ConfigService to override old configuration.
Method newExampleConfigConvict accepts a boolean parameter to force
configuration override.
Closes #1210
Depends on #1527 
> refactor(api-server): instantiate plugins in api-server without install them

- .github/workflows/ci.yml
Related to #1566 but does not actually fix it.
For now I just commented out the build step
of the flaky container image until we figure out
how to remedy the situation properly because
in the meantime I do not want to waste time
having to re-run the CI all the time because of the
flake.
> ci(tools): fix iroha AIO image build flake on CI

- .taprc
- jest.config.js
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/unit/model-type-guards.test.ts
File Path:
packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/unit/model-type-guards.test.ts
> test: jestify model-type-guards test

- .taprc
- jest.config.js
- packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-nodejs.test.ts
File Path:
packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/
rustc-container-target-nodejs.test.ts
> test: jestify rustc-container-target-nodejs

- .taprc
- jest.config.js
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
File Path:
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
> test: jestify deploy-cc-from-golang-source-private-data test

- packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
Disable validateKeyPairMatch call from config-service create method
because it fails with supply-chain default configuration and is going to
be removed when cleaning parameters
> fix(cmd-api-server): disable validateKeyPairMatch

- contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/appserver/serviceapi/package.json
- contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/restserver/coreapi/package.json
- examples/cartrade/package.json
- examples/discounted-cartrade/package.json
- examples/electricity-trade/package.json
- examples/test-run-transaction/package.json
- packages/cactus-cmd-socketio-server/package.json
Remove jade dependencies from multiple package.json files because of
reported security flaw
Closes: #1662
Signed-off-by: stepniowskip <piotr.stepniowski@fujitsu.com>
> fix: remove jade dependencies

- .taprc
- jest.config.js
- packages/cactus-common/src/test/typescript/unit/objects/get-all-field-names.test.ts
File Path:
packages/cactus-common/src/test/typescript/unit/objects/get-all-field-names.test.ts
> test: jestify get-all-field-names test

- .taprc
- jest.config.js
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint-invalid.test.ts
File Path:
packages/cactus-test-plugin-htlc-eth-besu/src/
test/typescript/integration/plugin-htlc-eth-besu/
get-single-status-endpoint-invalid.test.ts
> test: jestify get-single-status-endpoint-invalid test

- .taprc
- jest.config.js
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts
File Path:
packages/cactus-test-plugin-htlc-eth-besu/src/
test/typescript/integration/plugin-htlc-eth-besu/
new-contract-endpoint-invalid.test.ts
> test: jestify new-contract-endpoint-invalid test

- .taprc
- jest.config.js
- packages/cactus-cmd-api-server/src/test/typescript/integration/jwt-endpoint-authorization.test.ts
File Path:
packages/cactus-cmd-api-server/src/test/
typescript/integration/jwt-endpoint-authorization.test.ts
> test: jestify jwt-endpoint-authorization test

- .taprc
- jest.config.js
- packages/cactus-common/src/test/typescript/unit/js-object-signer.test.ts
File Path:
packages/cactus-common/src/test/typescript/
unit/js-object-signer.test.ts
> test: jestify js-object-signer test

- contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/cooperation/coreSide/ec1_adapter/package.json
- contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/cooperation/coreSide/ec2_adapter/package.json
- contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/cooperation/ecSide/ec1_connector/package.json
- contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/cooperation/ecSide/ec2_connector/package.json
- contribs/Fujitsu-ConnectionChain/connection-chain/environment/base/cc_env/servers/restserver/coreapi/package.json
- examples/cartrade/package.json
- examples/cartrade/validatorDriver/package.json
- examples/discounted-cartrade/package.json
- examples/discounted-cartrade/validatorDriver/package.json
- examples/electricity-trade/package.json
- examples/test-run-transaction/package.json
Update log4js in packages not handled by dependabot
Closes: #1825
> build(examples): bump log4js from 3.0.6 to 6.4.0

- packages/cactus-api-client/src/test/typescript/unit/verifier.test.ts
- packages/cactus-test-api-client/src/test/typescript/integration/verifier-integration-with-openapi-connectors.test.ts
Use global jest timeout for verifier-integration-with-openapi-connectors
functional test. It's 60 minutes at the moment, should be enough for
docker based test. Increase timeout in verifier unit test to handle
possible failures.
Closes: #1827
> test(api-client): fix flaky verifier-integration-with-openapi-connectors

- packages/cactus-test-tooling/src/main/typescript/postgres/postgres-test-container.ts
Fixes #1373
previous commit has been dropped off accidentally and was unable to reopen PR, see https://github.com/hyperledger/cactus/pull/1766 for history reference.
> style: 2021-09-20 linter warnings batch 24 / 26

- examples/cartrade/README.md
- examples/cartrade/config/default.yaml
- examples/cartrade/docker-compose.yml
- examples/cartrade/script-get-app.sh
- examples/cartrade/script-start-ledgers.sh
- examples/discounted-cartrade/README.md
- examples/discounted-cartrade/config/default.yaml
- examples/discounted-cartrade/docker-compose.yml
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/connector/PluginConfig.ts
- tools/docker/fabric-all-in-one/docker-compose-v2.x.yml
- tools/docker/fabric-all-in-one/fabcar-cli-1.4/README.md
- tools/docker/fabric-all-in-one/fabcar-cli-1.4/query.js
- tools/docker/fabric-all-in-one/fabcar-cli-1.4/registerUser.js
- tools/docker/fabric-all-in-one/fabcar-cli-1.4/setup.sh
- tools/docker/fabric-all-in-one/healthcheck.sh
- tools/docker/fabric-all-in-one/run-fabric-network.sh
Add fabcar setup to fabric 2.x all-in-one startup script and adjust
healthcheck accordingly. Use fabric 2.x in cartrade and discounted
cartrade sample apps. No packages updated, fabric sdk 1.4.19 seems to
work fine with fabric 2.2 for now. Both samples has been tested and work
OK.
Closes: https://github.com/hyperledger/cactus/issues/1842
- Next step is to use basic asset transfer instead of depracated fabcar, so fabcar-cli-1.4 will be removed in the future (most probably).
- Upgrade of SDK seems to be complex task for now (since packages were re-organized), I think it'd be better to just focus on migration to common fabric connector.
Depends on #1824
> refactor(cartrade): upgrade cartrade samples to fabric 2.2 

- packages/cactus-cmd-socketio-server/package.json
- packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
- yarn.lock
> fix(security): address CVE-2019-5413

- package.json
> fix: reset script from package.json does not work #1656

- examples/test-run-transaction/supply-chain-app-stub/package.json
These files are auto-generated with ISC as
the default licese. Switched to Apache 2
> chore: fix licenses

- .taprc
- jest.config.js
- packages/cactus-plugin-odap-hermes/src/test/typescript/integration/odap/transfer-complete.test.ts
File Path:
packages/cactus-plugin-odap-hermes/src/test/typescript/
integration/odap/transfer-complete.test.ts
Signed-off-by: awadhana awadhana0825@gmail.com
> test: jestify transfer-complete test

- packages/cactus-plugin-ledger-connector-fabric/package.json
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-source/deploy-contract-go-source-endpoint-v1.ts
- yarn.lock
Starts using the `sanitize-filename` npm package to
secure the Fabric ledger connector against malicious
user input when it comes to file paths of the golang
source codes that can be deployed through it.
https://www.npmjs.com/package/sanitize-filename
Fixes #1909
> fix(connector-fabric): uncontrolled data used in path expression

- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- yarn.lock
fix(cmd-api-server): add express static rate limiting
Introduces rate limiting to the static file serving express
middleware that returns the index.html of the single
page web applications that the API server can host.
The lack of rate limiting was highlighted as a problem by
CodeQL
Fixes #1840
> fix(cmd-api-server): add express static rate limiting

- package.json
This is just a temporary fix for the short term where we
simply force all underscore versions to be the latest availabe
at the time of this writing.
This is necessary because the vulnerabilities would be
much more complicated to be fixed on the top level
where we have to execute a costly migration from web3-eea to
web3js-quorum.
Temporarily addresses #1775
TODO: We still need to fix this in the correct way on the longer term.
> fix(security): address CVE-2021-23358 - TEMPORARY fix

- .github/workflows/codeql-analysis.yml
- Moved the file to the correct directory
- Pinned the runner version to Ubuntu 20.04
Fixes #1836
Depends on #1912 
Depends on #1910 
Depends on #1908
> ci: fix CodeQL security scans

- examples/cactus-check-connection-ethereum-validator/package.json
- examples/discounted-cartrade/package.json
- examples/electricity-trade/package.json
- examples/electricity-trade/tools/transferNumericAsset/package.json
- examples/test-run-transaction/package.json
- extensions/cactus-plugin-htlc-coordinator-besu/package.json
- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-api-server/src/main/typescript/api-client/api-server-api-client.ts
- packages/cactus-cmd-socketio-server/package.json
- packages/cactus-core-api/package.json
- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
- packages/cactus-plugin-odap-hermes/package.json
- yarn.lock
Upgrade the version of socket.io to 4.4.1 which contains the
patches for the CVE mentioned in the title.
Fixes #1914
> fix(cmd-api-server): upgrade socket.io - CVE-2022-21676

- package.json
- packages/cactus-plugin-keychain-memory-wasm/package.json
- yarn.lock
1. Upgrade cpy-cli to 4.1.0
2. Force glob-parent to be on 5.1.2
TODO: The proper solution to 2) is to upgrade Angular to 13
so we do need to do that later when more time is available.
Fixes #1916
> fix(deps): ensure glob-parent is above 5.1.2 - CVE-2020-28469

- package.json
- yarn.lock
TODO: Longer term we should take care to upgrade the top level
dependencies instead (as patched releases become available)
Fixes #1918
> fix(security): force lodash > 4.17.20 - CVE-2020-8203

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
authorizeSocket middleware will be installed only if AuthorizationProtocol different than NONE was provided.
Closes:  #1925
Note
- This change work on my other local branch (not PR ready yet).
- This can be refactored, so that all authorization middleware creation would be handled by `AuthorizerFactory.createMiddleware`, but I didn't want to touch it without test coverage. I will probably introduce some tests with of socketio authorization as part of other PR, we can think about improvements then.
> fix(api-server): allow no authorization on socketio endpoints

- examples/cactus-check-connection-ethereum-validator/check-ethereum-validator.ts
- examples/cactus-check-connection-ethereum-validator/package.json
- examples/discounted-cartrade/package.json
- examples/discounted-cartrade/trades.ts
- examples/electricity-trade/electricity-trade.ts
- examples/electricity-trade/package.json
- examples/test-run-transaction/package.json
- examples/test-run-transaction/test-run-transaction.ts
- packages/cactus-cmd-socketio-server/package.json
- packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/routes/index.ts
- yarn.lock
Fix CodeQL warnings:
- Reflected cross-site scripting
- Exception text reinterpreted as HTML
In following files:
- `examples/cactus-check-connection-ethereum-validator/check-ethereum-validator.ts`
- `examples/discounted-cartrade/trades.ts`
- `examples/electricity-trade/electricity-trade.ts`
- `examples/test-run-transaction/test-run-transaction.ts`
- `packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/routes/index.ts`
Also, sample apps in `example/` did not build after last socketio upgrade, had to upgrade typescript to make them build again.
> fix: resolve some CodeQL warnings

- package.json
Ensures that yarn will only install 1.2.6 or newer versions for
minimist.
The proper fix would be to have the dependencies issue releases
which upgrade their own (transitive) dependencies of minimist
so that we don't have to explicitly force it here, but at the time
of this writing these upgrades in our direct dependencies are just
not available yet.
Fixes #1943
> fix(deps): force minimist >=1.2.6 for CVE-2021-44906

- packages/cactus-plugin-htlc-eth-besu/package.json
- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-cactus.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-web3-eea.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/package.json
- packages/cactus-test-plugin-ledger-connector-besu/package.json
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-balance-endpoint.test.ts
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-past-logs-endpoint.test.ts
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-transaction-endpoint.test.ts
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/sign-transaction-endpoint.test.ts
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-get-balance-endpoint.test.ts
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-get-past-logs-endpoint.test.ts
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-get-transaction-endpoint.test.ts
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-sign-transaction-endpoint.test.ts
- typings/web3js-quorum/index.d.ts
> fix(security): address CVE-2021-23358

- package.json
> fix(security): address CVE-2021-23337

- .cspell.json
- .github/workflows/ci.yml
- .github/workflows/quorum-multi-party-all-in-one-publish.yaml
- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
- packages/cactus-test-tooling/src/main/typescript/quorum/quorum-mp-test-ledger.ts
- tools/docker/quorum-multi-party-all-in-one/Dockerfile
- tools/docker/quorum-multi-party-all-in-one/README.md
- tools/docker/quorum-multi-party-all-in-one/healthcheck.sh
- tools/docker/quorum-multi-party-all-in-one/supervisord.conf
Current Quorum-MP WS endpoints are not available outside of docker, fix
it. Use upstream npm setup package instead of contributor branch. Test
all members in healthcheck. Update readme. Add test tooling to setup
multi party ledger in functional tests. Cleanup and simplify dockerfile.
Publish MP image to ghcr.
Closes: #1927
Notes
- I've added a new image publish in this PR, but there's ongoing issue with package publish - https://github.com/hyperledger/cactus/issues/1881
- Since I'm not sure when the image will be published, I've used my personal ghcr for now, since I'm already using it in some functional tests on another branch. I will change it to hyperledger ghcr when the publish completes correctly.
> refactor(quorum-multi-party-all-in-one): enhance quorum-mp image

- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/common/core/app.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/common/core/bin/www.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/connector/ServerMonitorPlugin.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/connector/ServerPlugin.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/connector/fabricaccess.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/tsconfig.json
cactus-plugin-ledger-connector-fabric-socketio will compile with global strict flag.
Related issue: #1671
> refactor(connector-fabric-socketio): fix strict flag warnings

- examples/electricity-trade/BalanceManagement.ts
- examples/electricity-trade/BusinessLogicElectricityTrade.ts
- examples/electricity-trade/Dockerfile
- examples/electricity-trade/TransactionEthereum.ts
- examples/electricity-trade/config/validator-registry-config.yaml
- examples/electricity-trade/docker-compose.yml
- examples/electricity-trade/package.json
- examples/electricity-trade/tsconfig.json
Sample app electricity-trade is currently using Verifier interface from cactus-cmd-socket-server.
Replace it with VerifierFactory from cactus-verifier-client package that
can work with all cactus connectors.
Related: #1982
> refactor(electricity-trade): use cactus-verifier-client

- examples/discounted-cartrade/AssetManagement.ts
- examples/discounted-cartrade/BalanceManagement.ts
- examples/discounted-cartrade/BusinessLogicCartrade.ts
- examples/discounted-cartrade/CarsManagement.ts
- examples/discounted-cartrade/Dockerfile
- examples/discounted-cartrade/TemplateTradeManagement.ts
- examples/discounted-cartrade/TransactionEthereum.ts
- examples/discounted-cartrade/TransactionFabric.ts
- examples/discounted-cartrade/TransactionIndy.ts
- examples/discounted-cartrade/config/validator-registry-config.yaml
- examples/discounted-cartrade/package.json
- examples/discounted-cartrade/tsconfig.json
Sample app discounted-cartrade is currently using Verifier interface from cactus-cmd-socket-server.
Replace it with VerifierFactory from cactus-verifier-client package that
can work with all cactus connectors.
Related: #1982
> refactor(discounted-cartrade): use cactus-verifier-client

- README.md
Since the migration from RocketChat to Discord we had our chat platform
link in the readme outdated and basically dead. This change remedies that.
Fixes: #1937
Signed-off-by: Emerson Shoichet-Bartus <emersonfieldstone@gmail.com>
> docs(readme): replaced rocketchat link with discord link in README

- packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/routes/index.ts
Unsanitized input from an HTTP parameter flows into send, where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS).
Signed-off-by: Bhaskar <dev@bhaskar.email>
> fix(security): mitigate Cross-Site Scripting attack (XSS).

- .taprc
- jest.config.js
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
File Path:
packages/cactus-test-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
> test: jestify runtime-plugin-import test

- packages/cactus-test-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
This is a flaky test case that can't be reliably reproduce. I've ran the test individually 40 times and all 40 times it has passed successfully. 
This error, however, seems to pop up only when the `yarn jest` command is run (when I ran the test individually). 
Based on the linked ["hint"](https://stackoverflow.com/questions/50793885/referenceerror-you-are-trying-to-import-a-file-after-the-jest-environment-has/50793993#50793993) from the issue, it seems like using `jest.useFakeTimers()` a good solution. However, using the `jest.useFakeTimers()` with`async/await` was not recommended.
However, I found a [different source](https://gist.github.com/apieceofbart/e6dea8d884d29cf88cdb54ef14ddbcc4#file-test-js-L58) that showed examples of how to use the `jest.useFakeTimers()`. Our original problem, …
> test(cmd-api-server): fix flaky runtime-plugin-imports-test

- tools/ci.sh
- tools/custom-checks/run-custom-checks.ts
> ci: remove nodejs v12 exclusion logic from run custom checks

- MAINTAINERS.md
Adding Rama and Sandeep as maintainers.
Also updated the chat column for Takuma, Izuru, Jagpreet and Peter
so that their Discord IDs are visible there instead of the former
RocketChat user handles which are no longer in existence anyway since
the Hyperledger RocketChat got shut down in early 2022.
> docs(maintainers): add Rama and Sandeep

- package.json
[test: fix jest out of memory errors on Node v16.14.2](https://github.com/hyperledger/cactus/pull/2009/commits/756d80f7a5249cda681e40dce407b19fb681d172)
Explicitly specify the heap size (RAM) for the Jest process
that executes the tests to be 3 GB instead of the default
2 GB that NodeJS allocates by default.
This is not a good solution, but a workaround instead.
The test runner itself using this much RAM is the acutal
problem that we need to fix longer term and I'll be opening
a follow-up task specifically to address that and once that
has been fixed we can lower back the test runner's
heap size to the default 2 GB (which is still a lot BTW)
Not sure why the out of memory errors starting occuring only
on NodeJS 16.14.2, probably something made it use
slightly more memory and it finally …
> test: fix jest out of memory errors on Node v16.14.2

- .taprc
- jest.config.js
- packages/cactus-test-tooling/src/main/typescript/substrate-test-ledger/substrate-test-ledger.ts
- packages/cactus-test-tooling/src/test/typescript/integration/substrate/substrate-test-ledger-multiple-concurrent.test.ts
- tools/docker/substrate-all-in-one/Dockerfile
- tools/docker/substrate-all-in-one/README.md
- tools/docker/substrate-all-in-one/start.sh
This PR allows developers to choose the port where the saio exposes.
However, there is a bug: the substrate connector cannot connect to the saio running on the custom port. Perhaps it is an issue with port exposing?
> feat(substrate-aio): add ws-port argument

- packages/cactus-verifier-client/README.md
Update Supported ledger connectors table in `cactus-verifier-client` README file.
Add missing QUORUM_2X and CORDA_4X ledgers which are also supported.
> fix(cactus-verifier-client): update supported ledgers in readme

- .taprc
- jest.config.js
- packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
This test file required more refactoring because the `tap` tests were nested, however `jest` doesn't allow nested test cases
File Path: 
packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
> test: jestify api client routing node to node test

- packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
- yarn.lock
Affected versions of mime are vulnerable to regular expression denial of service when a mime lookup is performed on untrusted user input.
Action Applied:
Updated to version 3.
> fix(security): address CVE-2017-16138 

- examples/cactus-example-supply-chain-backend/package.json
- examples/cactus-example-supply-chain-frontend/package.json
- examples/cactus-example-supply-chain-frontend/proxy.conf.json
- examples/supply-chain-app/README.md
- yarn.lock
We should have documentation for how to develop the
supply chain app front-end with live-reloading enabled.
The ionic serve command has a built-in reverse-proxy
feature that makes this possible quite easily with
the right configuration in place.
How to achieve this is explained in the README.md
file of the supply chain app and the necessary updates
were made so that it actually works.
Fixes #2010
> docs(examples): explain supply chain live development

- .taprc
- jest.config.js
- packages/cactus-cmd-api-server/src/test/typescript/integration/jwt-unprotected-endpoint-authz.test.ts
Migrated test from Tap to Jest
File Path:
packages/cactus-cmd-api-server/src/test/
typescript/integration/
jwt-unprotected-endpoint-authz.test.ts
> test: jestify jwt-unprotected-endpoint-authz

- CODEOWNERS
Took the active maintainers from MAINTAINERS.md and
loaded them onto the root CODEOWNERS.md file.
We can define the more granular ownership structure
later as things crystalize.
Fixes #2024
> docs(codeowners): sync root codowners file to maintainers.md

- packages/cactus-plugin-ledger-connector-besu/Dockerfile
- packages/cactus-plugin-ledger-connector-besu/README.md
1. The besu connector container was using an outdated version
of the base image (which is the cmd-api-server image)
This was leading to the API server not recognizing the
besu plugin as a web service plugin and then not installing
the endpoints due to that.
Fixed this by specifying the current latest image tag of
the API server image:
ghcr.io/hyperledger/cactus-cmd-api-server:2022-05-12-2330a96
2. The environment variables for disabling authorization and gRPC TLS
were missing from the command that runs the besu connector
connector container. Adding those made it work and the cURL
requests from the example is now succeeding as expected.
Fixes #2022
> docs(connector-besu): fix besu AIO image tag in README.md

- .taprc
- jest.config.js
- packages/cactus-common/src/test/typescript/unit/servers.test.ts
test: jestify server test in cactus common
Migrate Tap to Jest
File Path:
packages/cactus-common/src/
test/typescript/
unit/servers.test.ts
> test: jestify server test from cactus common

- .gitignore
- packages/cactus-api-client/src/main/typescript/socketio-api-client.ts
- packages/cactus-api-client/src/test/typescript/unit/socketio-api-client.test.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/common/core/bin/www.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/connector/ServerMonitorPlugin.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/connector/ServerPlugin.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/connector/ValidatorAuthentication.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/connector/fabricaccess.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/index.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/integration/fabric-setup-helpers.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/integration/fabric-socketio-connector.test.ts
- packages/cactus-plugin-ledger-connector-fabric-socketio/tsconfig.json
- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- packages/cactus-verifier-client/src/test/typescript/unit/get-validator-api-client.test.ts
- packages/cactus-verifier-client/src/test/typescript/unit/verifier-factory.test.ts
Added functional jest test `fabric-socketio-connector.test` that can be run during CI process. It checks evaluate/sending transactions and monitoring for new events. Connector had to be refactored to be testable, tests also discovered some bugs that had to be fixed in order to pass.
- Added option for supplying `validatorKeyValue` instead of `validatorKeyPath`.
- JWT validation function works with key value now (instead of reading the key).
- Validator can now return messages that are not encrypted (it throwed error previously).
- Adjusted unit tests.
- Connector can be run both as a standalone app and loaded as a module `www.js`. Caller can use exported `startFabricSocketIOConnector` function to run the connector. Configuration must be supplied in file or in env variable like it's done …
> test(connector-fabric-socketio): add functional test, bug fix

- packages/cactus-plugin-ledger-connector-corda/README.md
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/Application.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/StateMonitorClientSession.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/StateMonitorSessionsManager.kt
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/monitor-transactions-v4.8.test.ts
Fix race condition that caused user session removal during request processing,
that caused test to fail occasionaly.
Correlated fixes / improvements:
- Use paging when watching for vault changes.
This was necessary to perform long-running runs of a failing test.
Without it, start monitor of a state with 200+ changes was failing instantly.
I thought that paging was needed when there are 200+ changes in single observer push,
but it seems that it breaks when total number of changes are that large,
which makes it more critical to fix.
- To prevent deadlock of cleanup thread I introduced thread pool to corda kotlin server.
Number of threads is configurable in environment variable.
Updated readme to show this option.
Closes: #1995
> test(connector-corda): fix flaky monitor transactions v4.8

- .taprc
- jest.config.js
- packages/cactus-cmd-api-server/src/test/typescript/integration/jwt-endpoint-authz-scope-enforcement.test.ts
File Path:
packages/cactus-cmd-api-server/src/test/typescript/integration/jwt-endpoint-authz-scope-enforcement.test.ts
> test: jestify jwt endpoint authz scope enforcement

- .github/workflows/ci.yml
- packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-bundler.test.ts
- tools/ci.sh
1. ci.yml workflows went through a massive refactoring to parallelize
the test execution for two main reasons: First this makes it faster,
second this also reduces the flakyness that comes from our ever growing
test suite making the test runner consume more and more RAM (the back
story here is that Yarn needed more than 2 GB RAM at first, and
when we bumped the heap size up to 3 GB it exhausted that soon after at
which point it became clear that this is not sustainable at all on the
long run since our GitHub CI runners come with 7 GB RAM total)
2. tools/ci.sh can now be configured via environment variables:
- DEV_BUILD_DISABLED (defaults to false)
true/false: if set to true the initial configure script execution is skipped
- FULL_BUILD_DISABLED (defaults to false)
true/false: if set to …
> test: fix CI - chunk up Jest tests

- .github/workflows/ci.yml
- .taprc
- jest.config.js
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/withdraw-endpoint-invalid.test.ts
Original issue was to  __test(plugin-htlc-eth-besu): fix assertion withdraw-endpoint-invalid #1871__  However, this test case hadn't been jestified (slipped through the cracks according to @awadhana) so I went ahead and jestified the file along with fixing the negative test case. Commit message for jestification and the original issue. 
_______________________________
Migrated test from Tap to Jest
File Path: packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/withdraw-endpoint-invalid.test.ts
This is a PARTIAL resolution to issue https://github.com/hyperledger/cactus/issues/238
_______________________________
Fixes #1871
> refactor: migrate to jest and fix neg test

- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/common/core/bin/www.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/connector/PluginUtil.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/connector/ServerMonitorPlugin.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/connector/ServerPlugin.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/tsconfig.json
cactus-plugin-ledger-connector-go-ethereum-socketio will compile with global strict flag.
Related issue: #1671
> refactor(connector-go-ethereum-socketio): fix strict flag warnings

- .github/workflows/ci.yml
- .taprc
- jest.config.js
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/remote-plugin-imports.test.ts
Migrated test from Tap to Jest
File Path:
packages/cactus-test-cmd-api-server/
src/test/typescript/integration/
remote-plugin-imports.test.ts
> test: jestify remote plugin imports 

- .github/workflows/ci.yml
- .taprc
- CONTRIBUTING.md
- jest.config.js
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
File Path:
packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
> test: jestify get consortium jws endpoint test

- packages/cactus-plugin-ledger-connector-sawtooth-socketio/src/main/typescript/common/core/bin/www.ts
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/src/main/typescript/connector/PluginUtil.ts
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/src/main/typescript/connector/ServerMonitorPlugin.ts
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/tsconfig.json
cactus-plugin-ledger-connector-sawtooth-socketio will compile with global strict flag.
Related issue: #1671
> refactor(connector-sawtooth-socketio): fix strict flag warnings

- examples/carbon-accounting/Dockerfile
- examples/supply-chain-app/Dockerfile
- packages/cactus-cmd-api-server/Dockerfile
> fix(security): address CVE-2022-29244, CVE-2021-39135

- packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/Dockerfile
- packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/rust/gen/Cargo.lock
- packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/rust/gen/Cargo.toml
- packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/rust/gen/src/server/mod.rs
--------------------------------
fix(plugin-keychain-vault): hyper upgrade   
Primary changes
--------------
1. Updated rust docker container base image to the latest
2. Updated hyper, hyper-openssl, hyper-tls, swagger, tokio, tokio-openssl versions in cargo.toml
3. Updated the depricated to_body() method to to_bytes() method and relevant imports
Fixes #2120
> fix(plugin-keychain-vault): hyper upgrade

- tools/docker/quorum-multi-party-all-in-one/Dockerfile
Upgraded the base image version from
`docker:20.10.3-dind`
to
`docker:20.10.21-dind`
which ships with newer rust versions through apk
by default and thereby fixing the issue of the rust
compiler version being not new enough for
docker-compose.
Fixes #2183
> fix(tools): ghcr-quorum-multi-party-all-in-one pip install

- .github/workflows/all-nodejs-packages-publish.yaml
A second attempt at fixing the release automation.
The missing piece was that some of the Indy SDK dependencies
were not installed by default and we forgot to run the ci.sh
script to take care of that within this workflow action.
With this fix now we have an additional step in the action which
takes care of installing the OS level build dependencies for
the project.
Fixes #1951
Fixes #2069
Fixes #2175
> build: fix release automation - try #2

- .github/workflows/.dast-nuclei-cmd-api-server.yaml
- .github/workflows/all-nodejs-packages-publish.yaml
- .github/workflows/besu-all-in-one-publish.yaml
- .github/workflows/cactus-whitepaper-publish.yaml
- .github/workflows/ci.yml
- .github/workflows/cmd-api-server-publish.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/commitlint-pull-request.yml
- .github/workflows/connector-besu-publish.yaml
- .github/workflows/connector-corda-server-publish.yaml
- .github/workflows/connector-fabric-publish.yaml
- .github/workflows/corda-4-6-all-in-one-obligation-publish.yaml
- .github/workflows/corda-4-7-all-in-one-obligation-publish.yaml
- .github/workflows/corda-4-8-all-in-one-obligation-publish.yaml
- .github/workflows/dev-container-vscode-publish.yaml
- .github/workflows/example-carbon-accounting-publish.yaml
- .github/workflows/example-supply-chain-app-publish.yaml
- .github/workflows/fabric-all-in-one-publish.yaml
- .github/workflows/fabric2-all-in-one-publish.yaml
- .github/workflows/iroha-all-in-one-publish.yaml
- .github/workflows/keychain-vault-server-publish.yaml
- .github/workflows/quorum-all-in-one-publish.yaml
- .github/workflows/quorum-multi-party-all-in-one-publish.yaml
- .github/workflows/rust-compiler-publish.yaml
- .github/workflows/sawtooth-all-in-one-publish.yaml
- .github/workflows/test-npm-registry-publish.yaml
- BUILD.md
Project-wide search and replace for all occurrences of the
checkout GH workflow action so that it is at the current
latest stable release version which is v3.1.0
Fixes #2187
> ci(github): upgrade actions/checkout to v3.1.0

- .github/workflows/iroha2-all-in-one-publish.yaml
- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/main/typescript/iroha/iroha2-test-ledger.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
- packages/cactus-test-tooling/src/test/typescript/integration/iroha/iroha2-test-ledger/iroha2-test-ledger.test.ts
- tools/docker/iroha2-all-in-one/Dockerfile
- tools/docker/iroha2-all-in-one/README.md
- tools/docker/iroha2-all-in-one/docker-compose.yml
- tools/docker/iroha2-all-in-one/healthcheck.sh
- tools/docker/iroha2-all-in-one/iroha_client_cli.sh
- tools/docker/iroha2-all-in-one/script-start-docker.sh
- tools/docker/iroha2-all-in-one/src/configs/client_cli/config.json
- tools/docker/iroha2-all-in-one/src/configs/peer/config.json
- tools/docker/iroha2-all-in-one/src/configs/peer/genesis.json
- tools/docker/iroha2-all-in-one/src/docker-compose.yml
- tools/docker/iroha2-all-in-one/supervisord.conf
- Add a new test image for Iroha V2 (iroha2-all-in-one). It start a test ledger in single container,
and also contains a proxy script for running iroha_client_cli.
- Add the new image to the CI.
- Add a new class for starting and interacting with Iroha V2 test ledger
from typescript test - Iroha2TestLedger.
- Add test for test setup class to ensure basic functions are working correctly.
Relates to #2138
> feat(iroha2-ledger): add Iroha V2 test ledger image and setup class

- packages/cactus-core-api/src/main/typescript/plugin/ledger-connector/i-socket-api-client.ts
- packages/cactus-plugin-ledger-connector-iroha/package.json
- packages/cactus-plugin-ledger-connector-iroha/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/api-client/iroha-api-client.ts
- packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/iroha-transaction-wrapper.ts
- packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/plugin-ledger-connector-iroha.ts
- packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/web-services/iroha-socketio-endpoint.ts
- packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/iroha-iroha-transfer-example.test.ts
- packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/iroha-socketio-endpoint.test.ts
- packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/socket-api.test.ts
- packages/cactus-test-tooling/src/main/typescript/iroha/iroha-test-ledger.ts
- packages/cactus-verifier-client/README.md
- packages/cactus-verifier-client/package.json
- packages/cactus-verifier-client/src/main/typescript/get-validator-api-client.ts
- packages/cactus-verifier-client/tsconfig.json
- tools/docker/iroha-testnet/docker-compose.yml
- yarn.lock
feat(iroha-connector): implement validator interface
Add monitoring and sending async/sync requests to ledger via SocketIO.
Closes: https://github.com/hyperledger/cactus/issues/1941
Author: stepniowskip <piotr.stepniowski@fujitsu.com>
Original PR: #1966
> feat(iroha-connector): implement validator interface

- tools/sync-npm-deps-to-tsc-projects.ts
> fix(build): sync-ts-config script needs import assertion of type json

- packages/cactus-plugin-odap-hermes/knex/knex.js
- packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/besu-odap-gateway.ts
- packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/fabric-odap-gateway.ts
- packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/plugin-odap-gateway.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/integration/backup-gateway-after-client-crash.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/integration/client-crash-after-delete-asset.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/integration/client-crash-after-lock-asset.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/integration/client-crash-after-transfer-initiation.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/integration/server-crash-after-create-asset.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/integration/server-crash-after-transfer-initiation.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/unit/recovery/logging.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/unit/recovery/recover-success.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/unit/recovery/recover-update-ack.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/unit/recovery/recover-update.test.ts
- packages/cactus-plugin-odap-hermes/src/test/typescript/unit/recovery/recover.test.ts
Two gateways were using the same database, which was causing a test to fail.
When retrieving the logs since a certain timestamp, there were logs from the other gateway. This caused the number of logs retrieved to be higher than what was supposed to be.
Fixes #2198
Signed-off-by: André Augusto [andre.augusto@tecnico.ulisboa.pt](mailto:andre.augusto@tecnico.ulisboa.pt)
> fix(odap-plugin): fix bug in #2198

- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/common/core/bin/www.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/connector/ServerPlugin.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/index.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/solidity/hello-world-contract/HelloWorld.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/solidity/hello-world-contract/HelloWorld.sol
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/integration/go-ethereum-socketio-connector.test.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/tsconfig.json
- packages/cactus-test-tooling/src/main/typescript/openethereum/openethereum-test-ledger.ts
- Add functional test of all functions from go-ethereum-socketio validator.
- Refactor go-ethereum validator to allow importing as a module, to simplify the functional test.
- Fix sendRawTransaction to work with Verifier protocol.
It couldn't be reached by any client library until now, so I consider this as "private" interface.
- Add common web3 client object in openethereum test ledger helper class.
- Add few new functions to ethereum test ledger helper class:
newEthPersonalAccount, transferAssetFromCoinbase, deployContract.
Depends on #2051
Depends on #2047
Closes: #2052
-------------
Please consider only the last commit - `test(connector-go-ethereum-socketio): add functional test, bug fix`. The rest are the dependencies that should …
> test(connector-go-ethereum-socketio): add functional test, bug fix

- CODEOWNERS
Transformed Rama's and Sandeep's usernames in the
CODEOWNERS file to all lower-case.
Hoping that this will fix the problem where GitHub
does not auto-assign them as reviewers to new PRs.
Fixes #2200
> docs(codeowners): fix Rama's and Sandeep's usernames

- packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/src/main/typescript/common/core/bin/www.ts
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/src/main/typescript/connector/ServerMonitorPlugin.ts
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/src/main/typescript/index.ts
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/src/test/typescript/integration/sawtooth-socketio-connector.test.ts
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/tsconfig.json
- Add functional test of all functions from sawtooth-socketio validator.
- Refactor sawtooth validator to allow importing as a module, to simplify the functional test.
- Add stopMonitor to terminate tests easily.
- Allow multiple clients to monitor for blocks.
- Fix parsing of URL from config so that it doesn't depend on trailing slash anymore.
Closes: https://github.com/hyperledger/cactus/issues/2107
Depends on: https://github.com/hyperledger/cactus/pull/2109
Depends on: https://github.com/hyperledger/cactus/pull/2110
Depends on: https://github.com/hyperledger/cactus/pull/2047
> test(connector-sawtooth-socketio): add functional test, bug fix

- .github/workflows/ci.yml
- .taprc
- jest.config.js
- packages/cactus-plugin-keychain-memory/src/test/typescript/unit/plugin-keychain-memory.test.ts
File Path:
packages/cactus-plugin-keychain-memory/src/
test/typescript/unit/plugin-keychain-memory.test.ts
This is a PARTIAL resolution to issue https://github.com/hyperledger/cactus/issues/238
Signed-off-by: awadhana <awadhana2021@gmail.com>
> test: jestify plugin-keychain-memory test

- .github/workflows/ci.yml
- .taprc
- jest.config.js
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts
Migrated test from Tap to Jest
File Path:
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts
Signed-off-by: awadhana <awadhana2021@gmail.com>
> test(get-single-status-endpoint-invalid): jestify get-single-status-endpoint-invalid

- packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
fixed 2 lint errors that were the any type error for Typescript and removed Node
Partial solution to #1375 
Signed-off-by: Alec Phong <alecphong@gmail.com>
> style(test-tooling): fixed any type linter warns in quorum-test-ledger

- packages/cactus-test-tooling/src/main/typescript/substrate-test-ledger/substrate-test-ledger.ts
Docker expects environment variables passed to the container
to be strings.
The null coalescing code was making it so that if the test case
did not pass in a custom WS_PORT  env var, then it would default
to using a value for the port that was a number not a string.
This would crash the serialization logic within docker that was
trying to apply the environment variables to the container when
starting it.
Switching the type of 9944 default WS port to "9944" (string) fixes it.
Also specifying explicitly the `wsPort` variable's type to be
string so that the next time someone tries to make this mistake
the compiler will slap their hands right away.
Fixes #2213
> fix(test-tooling): substrate test ledger fails if WS_PORT not specified

- examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/utility-emissions-channel/enroll-admin-v1-endpoint.ts
- examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bamboo-harvest-endpoint.ts
- examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bookshelf-endpoint.ts
- examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-shipment-endpoint.ts
- examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bamboo-harvest-endpoint.ts
- examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bookshelf-endpoint.ts
- examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-shipment-endpoint.ts
Edited it after the fact to correct the bugs introduced in the catch
blocks where non-Error type exceptions were getting ignored which was
not the case before the linter fixes.
The original commit message from Alec:
`=======================================================================`
Primary Change
Fixed lint errors on utility-emissions-channel/enroll-admin-v1-endpoint.ts
(line 54, col 25), insert-bamboo-harvest-endpoint.ts (line 78, col 3),
insert-bookshelf-endpoint.ts (line 59, col 3),
insert-shipment-endpoint.ts (line 69, col 3),
list-bamboo-harvest-endpoint.ts (line 38, col 3; line 58, col 3; ),
list-bookshelf-endpoint.ts (line 56, col 3), and
list-shipment-endpoint.ts (line 40, col 3)
In order to fix changes from any to unknown, had to change the
output path to directed types: …
> style(examples): error handling and return type linter fixes

- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/common/core/bin/www.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/connector/ServerMonitorPlugin.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/integration/go-ethereum-socketio-connector.test.ts
- added parameter in monitorOptions what triggers monitor to report empty blocks
Closes: #2236
Signed-off-by: Tomasz Awramski <tomasz.awramski@fujitsu.com>
> feat: connector-go-ethereum now can report empty blocks

- package.json
There is a new method of specifying the package manager from Node v16 and
up.
The promise of this is that the package manager can be automatically
made available to project builds via this declarative property of the
package.json file without forcing contributors to manually deal with
installation of custom package managers such as yarn (which we use) or
to manually switch the version of it used (which is also important to us
because we are still using the legacy version of yarn instead of v3 -
the latest at the time of this writing)
This task is about trying out this new property to see if it helps
lowering the bar of the initial project setup for new contributors.
Fixes #2267
> build(yarn): specify packageManager in package.json

- examples/cactus-workshop-examples-2022-11-14/README.md
- examples/cactus-workshop-examples-2022-11-14/package.json
- examples/cactus-workshop-examples-2022-11-14/src/main/typescript/hello-world.ts
- examples/cactus-workshop-examples-2022-11-14/src/main/typescript/simple-consortium.ts
- examples/cactus-workshop-examples-2022-11-14/src/main/typescript/test-ledger.ts
- examples/cactus-workshop-examples-2022-11-14/tsconfig.json
- yarn.lock
Simple examples using Cacti tailored for the workshop.
Thanks to @AndreAugusto11  and Monica Gomez <monicasrgomez@gmail.com> @msrgomez for the amazing work.  
Works with version 1.0.0 of cactus-tooling.  
Depends on #2213 
Depends on #2223
> docs(examples): add workshop 2022-11-14 examples

- CODEOWNERS
- MAINTAINERS.md
Housekeeping of the documents that mention usernames.
Had to skip changing the username in the ./weaver/*.md because of the
newline index corruption problem explained in
https://github.com/hyperledger/cacti/issues/2302
Resolves #2304
> docs(maintainers/codeowners): update Sandeep's GH user to sandeepnRES

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/basic-asset-transfer/chaincode-typescript/tsconfig.json
The test case [1] uses the "standard" basic-asset-transfer example for
verifying contract deployment functionality and in this instance, the
problem was traced back to the NodeJS flavor of the contract having
a transitive dependency (fabric-contract-api => winston => logform) which
was probably being auto-upgraded (due to our test fixture lacking a
package-lock.json or yarn.lock file) and leading to the typescript
compilation of the project failing because of updates that must've been
pushed into the index.d.ts file of the logform transitive dependency.
The fix applied here is to just disable the lib checking of the compiler
so that the typescript code of dependencies is not type-checked at all.
This would be a no-go if we were talking about the code of the Cacti
framework itself, but …
> test(connector-fabric): fix v2-2-x/deploy-cc-from-typescript-source

- tools/docker/rust-compiler/Dockerfile
Upgraded the container image's base image so that the Rust compiler
that is being used is now v1.68.0 instead of v1.57.0.
Fixes #2325
> test(ghcr-rust-compiler): fix image rust build openssl-src v111.25.1

- packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/rust/gen/Cargo.lock
- packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/rust/gen/Cargo.toml
Verified that these changes are okay by recompiling the rust code
and executing the manual steps from the readme that launch the containers
and then uses cURL to send a couple of requests in.
Fixes #2338
> build(plugin-keychain-vault): fix CVE-2021-32810 - upgrade vault crate

- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/common/core/bin/www.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/connector/ServerPlugin.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/integration/go-ethereum-socketio-connector.test.ts
- getBlock and getTransactionReceipt added in go-ethereum-socketio-connector
- Added nullish coalescing in monitor options
Closes: #2255
Signed-off-by: tomasz awramski <tomasz.awramski@fujitsu.com>
> feat(connector-go-ethereum): add getBlock and getTransactionReceipt methods to connector

- .github/containerscan/allowedlist.yaml
- tools/docker/quorum-multi-party-all-in-one/Dockerfile
> fix(security): vulnerabilities found in quorum-multi-party-all-in-one

- .gitguardian.yaml
- .github/workflows/gg-shield-action.yaml
related to #720
this includes gitguardian workflow + configuration file
> chore: adding custom gitguardian check

- packages/cactus-core/package.json
- packages/cactus-plugin-ledger-connector-besu/package.json
fixes: #2039
related to: #2241
> fix(cmd-api-server): mitigate CVE-2022-24434 and CVE-2022-24999 #2039

- .gitignore
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/lock-asset/chaincode-typescript/tsconfig.json
Telling the typescript compiler to skip the library code check so that
auto-updating dependencies don't break the test fixture chain code
compilation.
The root cause and the fix are equivalent as they were for:
https://github.com/hyperledger/cacti/issues/2322
https://github.com/hyperledger/cacti/pull/2323
Commit SHA: dfb727861b5e26a15dbef0729a2a14dd26b4655f
Fixes #2341
Also sneaking in a .gitignore change with this: there is a VSCode
extension that stores local editing history of files in a .history/
sub-folder and that needs to be ignored in git otherwise it just keeps
popping up in the git index which is annoying sometimes.
> test(connector-fabric): fix v2-2-x/deploy-lock-asset.test.ts

- .github/workflows/test_weaver-asset-transfer.yml
- .github/workflows/test_weaver-corda-interop-app.yml
- .github/workflows/test_weaver-data-sharing.yml
- .github/workflows/test_weaver-docker-build.yml
- .github/workflows/test_weaver-go.yml
- .github/workflows/test_weaver-node-pkgs.yml
- .github/workflows/test_weaver-relay.yml
- .gitignore
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/lock-asset/chaincode-typescript/tsconfig.json
This is to resolve data sharing worklow failing for abritrary reasons.
Additionally rename weaver workflows jobs, so as to uniquely identify them by their name.
> refactor(workflows): use 4vcpu runner for weaver data sharing workflow

- .github/workflows/all-nodejs-packages-publish.yaml
- .github/workflows/ci.yml
- .github/workflows/ghpkg-all-kotlin-api-clients-publish.yaml
- .github/workflows/publish-npm.yaml
- .github/workflows/test_weaver-asset-exchange-besu.yml
- .github/workflows/test_weaver-asset-exchange-fabric.yml
- .github/workflows/test_weaver-asset-transfer.yml
- .github/workflows/test_weaver-corda-interop-app.yml
- .github/workflows/test_weaver-data-sharing.yml
- .github/workflows/test_weaver-docker-build.yml
- .github/workflows/test_weaver-go.yml
- .github/workflows/test_weaver-node-pkgs.yml
- .github/workflows/test_weaver-relay.yml
- .gitignore
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/lock-asset/chaincode-typescript/tsconfig.json
Use current version of GitHub action
> chore(ci): update deprecated GitHub API

- tools/docker/quorum-all-in-one/Dockerfile
Other, lower severity vulnerabilities are also being addressed by this
change but the two big ones are the critical severity ones mentioned
in the commit subject.
Most of the vulnerabilities are now fixed in quorum-all-in-one but
there are still some that are not because most of the remaining
vulnerabilities are still new and is still waiting for the new changes
to be pulled in and released on their respective package versions.
And we tried to ask on the quorum discussions on github as you can
see here. (ConsenSys/quorum#1513).
Here are the remaining vulnerabilities for quorum-all-in-one:
CVE-2022-3602
CVE-2022-3786
CVE-2022-3602
CVE-2022-3786
CVE-2022-42003
CVE-2022-42004
CVE-2022-45868
CVE-2022-1471
CVE-2022-21698
CVE-2022-27664
CVE-2022-32149
CVE-2022-21698
CVE-2022-27664 …
> fix(tools/quorum-all-in-one): address CVE-2021-36159 and CVE-2022-28391

- .dcilintignore
> chore(docs): fix dci-lint failure

- packages/cactus-plugin-keychain-memory-wasm/src/main/rust/cactus-plugin-keychain-memory-wasm/Cargo.toml
- packages/cactus-plugin-keychain-memory-wasm/src/main/rust/cactus-plugin-keychain-memory-wasm/README.md
- packages/cactus-plugin-keychain-memory-wasm/src/main/rust/cactus-plugin-keychain-memory-wasm/src/lib.rs
Removed wee_alloc from being used entirely.
The default Rust allocator will be used instead
which is better maintained and poses less
of a security threat.
Fixes #2352
> fix(keychain-memory-wasm): wee_alloc is Unmaintained GHSA-rc23-xxgq-x27g

- packages/cactus-plugin-ledger-connector-iroha2/src/test/typescript/integration/iroha2-generate-and-send-signed-transaction.test.ts
- packages/cactus-plugin-ledger-connector-iroha2/src/test/typescript/integration/iroha2-setup-and-basic-operations.test.ts
- Use waitForCommit for all transactions used in test suites to prevent spurious CI test failures.
Closes: #2370
Closes: #2373
> fix(iroha2-connector): fix flaky tests to solve #2370 and #2373

- .github/workflows/test_weaver-pre-release.yaml
- .github/workflows/weaver_deploy_corda-pkgs.yml
- .github/workflows/weaver_deploy_go-pkgs.yml
- .github/workflows/weaver_deploy_node-pkgs.yml
- .github/workflows/weaver_deploy_relay-server.yml
- tools/go-gen-checksum.sh
- weaver/core/network/fabric-interop-cc/contracts/interop/VERSION
- weaver/core/network/fabric-interop-cc/interfaces/asset-mgmt/VERSION
- weaver/core/network/fabric-interop-cc/libs/assetexchange/VERSION
- weaver/core/network/fabric-interop-cc/libs/utils/VERSION
Chore:
- chore(ci): publish weaver go modules
This way of publishing all go modules in single commit will work as long as in the release commit, only version files are changed and script `go-gen-checksum.sh` in root directory is run, and no other changes are made between that commit and actual releasing (i.e. no other PR is merged affecting these go modules till release PR is merged).
Fixes:
- fix(ci): update version only if tag has version
> chore(ci): publish weaver go modules

- weaver/samples/besu/simpleasset/truffle-config.js
- weaver/tests/network-setups/besu/scripts/setupEthSigner.sh
1. Without having it pinned to v0.8.8, some breaking changes that solc
has snuck in [1] [2] around v0.8.15 (for IR) are breaking the contract
deployment in a way that opcodes end up in the migration contract's
constructor that Besu does not recognize ("opcode INVALID" in the besu
logs if you set the log level to "ALL") in the Besu logs and then sends
back an "internal error" message via the JSON-RPC response, which is a
bug IMO it should state that the user input was invalid (user input
being the contract)
2. Disabled IR in the truffle (solc) config which is a step backwards
because it's a new feature of the solidity compiler that has certain
benefits to it compared to the legacy compilation mode, but enabling it
breaks the build so it just had to be done. In the future if someone
has …
> docs(weaver/samples): pin solc to v0.8.8 and turn off IR for Besu asset exchange

- packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/web-services/invoke-contract-endpoint.ts
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/web-services/run-transaction-endpoint.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json-private.test.ts
- packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
- packages/cactus-test-tooling/src/main/typescript/quorum/quorum-mp-test-ledger.ts
- typings/web3js-quorum/index.d.ts
Fixes #951
Co-authored-by: Travis Payne <travis.payne@accenture.com>
Co-authored-by: johnhomantaring <john.h.o.mantaring@accenture.com>
Co-authored-by: jagpreetsinghsasan <jagpreet.singh.sasan@accenture.com>
Co-authored-by: aldousalvarez aldousss.alvarez@gmail.com
> feat(quorum): private transaction support

- packages/cactus-plugin-ledger-connector-quorum/package.json
- packages/cactus-plugin-ledger-connector-quorum/src/scripts/get-quorum-connector-status.ts
- yarn.lock
- Simple script will check ledger connection by getting block through the connector.
Closes: #2309
> feat(quorum-connector): add script for checking connection status

- examples/cactus-example-carbon-accounting-backend/package.json
- yarn.lock
Bumping hardhat so that flat gets upgraded transitively/indirectly.
Fixes #2394
> docs(examples): fix CVE-2020-36632 flat vulnerable to Prototype Pollution

- weaver/sdks/besu/node/package-local.json
- weaver/sdks/besu/node/package.json
- weaver/tests/network-setups/besu/.gitignore
- weaver/tests/network-setups/besu/Makefile
- weaver/tests/network-setups/besu/package.json
- weaver/tests/network-setups/besu/scripts/setupEthSigner.sh
This fixes the issue with failing besu-asset-exchange workflows
> fix(besu): testnet web3 version fixed to 1.10.0

- whitepaper/Dockerfile
fix(security): vulnerabilities found in cactus-whitepaper #2038
> fix(security): vulnerabilities found in cactus-whitepaper

- packages/cactus-common/src/main/typescript/signer-key-pairs.ts
- packages/cactus-common/src/main/typescript/strings.ts
- packages/cactus-common/src/test/typescript/unit/key-converter.test.ts
- packages/cactus-common/src/test/typescript/unit/logging/logger.test.ts
submitting fixes for issue #1357 minus the linter warning ID 79 and 80 as they have been already solved in batch 9 #1478.
I have added types of variables and objects wherever necessary in place of 'any' and for packages/cactus-common/src/test/typescript/unit/logging/logger.test.ts I have declared a interface for prototyping the stdOutDataHandler function.
fixes #1357
Signed-off-by: Arnab Nandi arnabnandi2002@gmail.com
> style: changes made for fixing #1357

- .github/workflows/ci.yaml
- packages/cactus-cmd-api-server/src/test/resources/cactus-dummy-package/package.json
- packages/cactus-plugin-htlc-eth-besu/package.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
- packages/cactus-plugin-ledger-connector-ubiquity/package.json
- tools/ci.sh
- tools/custom-checks/run-custom-checks.ts
- replace old packages verions in package.json files printed after $npm run custom-checks
Closes: #2431
> ci(custom-checks): fix sibling pkg dependency version inconsistencies

- examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/model/converter/bamboo-harvest-converter.ts
- examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/model/converter/bookshelf-converter.ts
- examples/cactus-example-supply-chain-frontend/src/app/bamboo-harvest/bamboo-harvest-detail/bamboo-harvest-detail.page.ts
- examples/cactus-example-supply-chain-frontend/src/app/bamboo-harvest/is-bamboo-harvest.ts
1. Added a user-defined type guard to check for `BambooHarvest` types
on the front-end.
2. Additional runtime type checks during data type conversion so that
if we get invalid input it speaks up against it specifically instead of
using `any` types and generic crashes.
Fixes #2092
Signed-off-by: adrianbatuto <adrian.batuto@accenture.com>
> style(examples): 2021-09-20 linter warnings batch 17 / 26; part 2

- tools/docker/besu-multi-party-all-in-one/Dockerfile
- tools/docker/corda-all-in-one/Dockerfile
- tools/docker/corda-all-in-one/corda-v4_8-flowdb/Dockerfile
- tools/docker/corda-all-in-one/corda-v4_8/Dockerfile
- tools/docker/iroha2-all-in-one/Dockerfile
- tools/docker/quorum-multi-party-all-in-one/Dockerfile
- tools/docker/sawtooth-all-in-one/Dockerfile
- tools/docker/supabase-all-in-one/Dockerfile
Bump the versions across the board so that all our
test container images are fixed.
Once this is merged, we can start upgrading the
images that the test cases are using (for now
they remain pinned to the previous, buggy images)
Fixes #2518
> build(tools): bump DinD base images - fix cgroup v2 sed: write error

- packages/cactus-common/src/main/typescript/checks.ts
- packages/cactus-common/src/main/typescript/logging/logger-provider.ts
- packages/cactus-common/src/main/typescript/objects.ts
- packages/cactus-common/src/main/typescript/public-api.ts
- packages/cactus-common/src/main/typescript/secp256k1-keys.ts
- packages/cactus-common/src/main/typescript/types/is-record.ts
[style(common): fix batch 7/26 of linter warnings](https://github.com/hyperledger/cacti/pull/2098/commits/fda1910eac5289f56fa3ec30cba24e6a73d09afe)
Changes made:
- Fixed lint warnings associated with any-type for truthyness and nonBlankString checking
- Fixed lint warnings associated with type-aliases in logger
- Fixed lint warnings associated with  non-any type in getAllMethodNames and getAllFieldNames
- Fixed lint errors associated with unexpected any for private-public keypairs
- Added an isRecord user-defined type guard in the common package that
can narrow `unknown` types into `Record<string, unknown>`
Fixes https://github.com/hyperledger/cacti/issues/1356
Signed-off-by: akankshadixit <akanksha.dixit12@gmail.com> …
> fix: part 2 of lint warnings resolved for batch 7/26 #1356 : Commit to be reviewed

- examples/cactus-example-carbon-accounting-frontend/angular.json
- examples/cactus-example-carbon-accounting-frontend/package.json
- examples/cactus-example-carbon-accounting-frontend/src/app/app.component.html
- examples/cactus-example-carbon-accounting-frontend/src/index.html
- examples/cactus-example-carbon-accounting-frontend/tsconfig.json
- examples/cactus-example-supply-chain-frontend/angular.json
- examples/cactus-example-supply-chain-frontend/package.json
- examples/cactus-example-supply-chain-frontend/src/app/app.component.html
- examples/cactus-example-supply-chain-frontend/src/app/bamboo-harvest/bamboo-harvest-detail/bamboo-harvest-detail.page.ts
- examples/cactus-example-supply-chain-frontend/src/app/bookshelf/bookshelf-detail/bookshelf-detail.page.ts
- examples/cactus-example-supply-chain-frontend/src/app/shipment/shipment-detail/shipment-detail.page.ts
- examples/cactus-example-supply-chain-frontend/src/index.html
- examples/cactus-example-supply-chain-frontend/tsconfig.json
- yarn.lock
1. Upgraded Angular from v13 to v14
2. Also bumped up the Ionic Framework dependencies
as needed because older versions that we were using
were not compatible [1] with Angular v14
3. Also did some of the Cactus -> Cacti renaming
in the front-end code namely the front-page of
both the supply chain and the carbon accounting
app examples.
[1] https://stackoverflow.com/a/72508644
Verbatim copy of the above link's comment:
==================================
The current version of Ionic v6.1.8 is not
compatible with Angular 14. Apparently,
it's been fixed in a dev release but it's not
stable yet. Have a look here
https://github.com/ionic-team/ionic-framework/issues/25353
you can update @ionic/angular to
version 6.1.9-dev.11654275237.1b595be3
and re-run npm install.
Should work fine for now, if …
> docs(examples): upgrade Angular to v14

- README.md
1. Replaced the Open in VSCode badge to be backed by the shields.io
service which actually works.
2. Removed the codecov badge for now because it does not work
at the moment due to us having broken up the test execution into
smaller CI jobs that are separate from each other.
Fixes #2169
> docs(readme): fix broken VS-code badge in the readme

- .github/workflows/ci.yaml
- package.json
- tools/ci.sh
- yarn.lock
1. Stopped using the openapi-generator-cli package to download the .jar files
and instead went with a direct download approach after having reverse
engineered the HTTP URLs that can be used for fetching the jars from
the maven repository.
2. The above appears to be a good fix because the third party service
that was serving HTTP 504 errors was not the download link but the
version validator link (e.g. a service that can tell us whether a
specific version of the OpenAPI generator jar file exists or not). So,
now that we just download exactly the versions of the .jars that we need
there is no request sent to that other service and the problem therefore
seems to have been solved.
3. We no longer need to delete the openapitools.json file in the root
because it no longer gets created to begin …
> build(codegen): fix OpenAPI TypeError: error.response.data.on is not a function

- weaver/tests/network-setups/indy/docker/Dockerfile
Fixes issue #2500 
Changed the line 24 of the dockerfile, to remove the use of the erroneous setup.py to replace it with a full line of all the dependencies modeled from the same file. 
@VRamakrishna Kindly check
> test(weaver/indy-plenum): fix dockerfile - use pip3 install instead of setup.py

- packages/cactus-test-tooling/src/main/typescript/rustc-container/rustc-container.ts
Updated the cactus-rust-compiler version to properly build the image and get the required files.
Fixes https://github.com/hyperledger/cacti/issues/2407
Signed-off-by: adrianbatuto <adrian.batuto@accenture.com>
> ci(test-tooling): fix CI job failing due to with wasm-pack

- weaver/core/network/corda-interop-app/interop-workflows/src/main/kotlin/org/hyperledger/cacti/weaver/imodule/corda/flows/AccessControlFlows.kt
- weaver/core/network/corda-interop-app/interop-workflows/src/main/kotlin/org/hyperledger/cacti/weaver/imodule/corda/flows/AssetExchangeHTLCFlows.kt
- weaver/core/network/corda-interop-app/interop-workflows/src/main/kotlin/org/hyperledger/cacti/weaver/imodule/corda/flows/AssetTransferFlows.kt
- weaver/core/network/corda-interop-app/interop-workflows/src/main/kotlin/org/hyperledger/cacti/weaver/imodule/corda/flows/MembershipFlows.kt
- weaver/core/network/corda-interop-app/interop-workflows/src/main/kotlin/org/hyperledger/cacti/weaver/imodule/corda/flows/NetworkIdFlows.kt
- weaver/core/network/corda-interop-app/interop-workflows/src/main/kotlin/org/hyperledger/cacti/weaver/imodule/corda/flows/VerificationPolicyFlows.kt
- weaver/core/network/corda-interop-app/interop-workflows/src/main/kotlin/org/hyperledger/cacti/weaver/imodule/corda/flows/WriteExternalStateFlows.kt
- weaver/rfcs/models/security/confidentiality.md
Bug fix in corda interop app (weaver), where flows would get stuck if responder flow verification fails.
> fix(weaver-corda): throw error correctly in responder flows

- tools/docker/quorum-all-in-one/Dockerfile
- tools/docker/quorum-all-in-one/start-quorum.sh
- tools/docker/quorum-all-in-one/start-tessera.sh
fixes: #2411
related to: #2240 and #2274
Tessera version was updated and some flags were deprecated. It has been
fixed in this commit. Also, the quorum and tessera compatibility with
quorum-all-in-one. The container and image has been built and ran
successfully.
> fix(tessera): updated tessera version error in quorum-all-in-one #2411

- examples/cactus-check-connection-ethereum-validator/package.json
- examples/cactus-example-discounted-asset-trade/package.json
- examples/cactus-example-electricity-trade/package.json
- examples/cactus-example-electricity-trade/tools/transferNumericAsset/package.json
- examples/cactus-example-tcs-huawei/package.json
- examples/cactus-example-tcs-huawei/tools/transferNumericAsset/package.json
- examples/test-run-transaction/package.json
- extensions/cactus-plugin-htlc-coordinator-besu/package.json
- packages-python/cactus_validator_socketio_indy/testcli/package.json
- packages-python/cactus_validator_socketio_iroha/testcli/package.json
- packages/cactus-api-client/src/main/typescript/socketio-api-client.ts
- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-socketio-server/package.json
- packages/cactus-core-api/package.json
- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/unit-test/package.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/package.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/unit-test/package.json
- packages/cactus-plugin-ledger-connector-iroha2/package.json
- packages/cactus-plugin-ledger-connector-sawtooth-socketio/package.json
- packages/cactus-plugin-ledger-connector-tcs-huawei-socketio/package.json
- packages/cactus-plugin-odap-hermes/package.json
- yarn.lock
To completely get rid of all instances of the vulnerable versions,
we also have to upgrade the example application's Angular versions:
Depends on #2229
Fixes #2228
> fix(security): the CVE-2022-2421 - upgrade socket.io-parser to >=4.2.1

- examples/cactus-example-carbon-accounting-backend/package.json
- examples/cactus-example-supply-chain-backend/package.json
- packages/cactus-cmd-socketio-server/package.json
- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/watch-blocks-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-quorum/package.json
- packages/cactus-plugin-ledger-connector-xdai/package.json
- packages/cactus-plugin-odap-hermes/package.json
- packages/cactus-plugin-persistence-ethereum/package.json
- packages/cactus-test-api-client/package.json
- packages/cactus-test-plugin-htlc-eth-besu/package.json
- packages/cactus-test-plugin-ledger-connector-besu/package.json
- packages/cactus-test-plugin-ledger-connector-quorum/package.json
- packages/cactus-test-tooling/package.json
- yarn.lock
Update from Peter: I needed to do an unsafe cast because that was the least
bad option (other option was to make a breaking change in the quourm 
connector's API).
The issue opened for tracking a proper resolution to this is titled as:
refactor(connector-quorum): make Web3BlockHeader.receiptRoot optional #2555
and the link to it on GitHub is https://github.com/hyperledger/cacti/issues/2555
Fixes #2332
> build(deps): upgrade web3 project-wide to v1.6.1

- jest.config.js
- packages/cactus-plugin-ledger-connector-cdl-socketio/Dockerfile
- packages/cactus-plugin-ledger-connector-cdl-socketio/README.md
- packages/cactus-plugin-ledger-connector-cdl-socketio/package.json
- packages/cactus-plugin-ledger-connector-cdl-socketio/sample-config/default.yaml
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/common/core/app.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/common/core/bin/www.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/common/core/config.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/connector/ServerPlugin.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/connector/ValidatorAuthentication.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/connector/cdl-request.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/index.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/test/typescript/integration/cdl-connector-manual.test.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/tsconfig.json
- tsconfig.json
- yarn.lock
- Add new plugin for connecting with Fujitsu CDL.
- Add test script for checking connector operations manually.
- Peter: Fixed missing dependency declarations
- Peter: Consolidated the socket.io versions to the main branch
- Peter: Fixed merge conflicts in yarn.lock file
Closes: https://github.com/hyperledger/cacti/issues/2455
> feat(cactus-plugin-ledger-connector-cdl-socketio): add new connector plugin

- packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/generate-and-send-signed-transaction.test.ts
- packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts
- packages/cactus-test-tooling/src/main/typescript/iroha/iroha-test-ledger.ts
- tools/docker/iroha-all-in-one/Dockerfile
- tools/docker/iroha-all-in-one/entrypoint.sh
1. Upgraded the Iroha AIO image to use v1.4.0-patch-3
2. The new Iroha version now supports configuraton via ENV variables
3. Because of 2) we don't need to apply config file changes in the
entrypoint script of the container anymore, yay.
4. The new image uses the iroha release image as the base and  it
does NOT recompile the entire project which makes the build
orders of magnitude faster, wasting much less CI time/resources.
5. Exposed the healthcheck port for through the IrohaTestLedger class
so the other improvement we'll be able to do after this is to phase out
the hacky python script that does the healthcheck at the moment if
the new built-in healthcheck endpoint does actually work fine.
6. Migrated all the test cases to the new image version.
Fixes #2524
Signed-off-by: Peter …
> ci(tools/docker): stop compiling Iroha as part of the all-in-one image build

- packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/plugin-odap-gateway.ts
CommitFinalResponse and CommitPreparationResponse
were accidentally having the same enum value, fixed it by
providing the correct enum value (as per the specs) for
CommitFinalResponse.
Links:
1. https://datatracker.ietf.org/doc/bofreq-hardjono-secure-asset-transfer-protocol/
2. https://www.ietf.org/archive/id/draft-hargreaves-odap-03.txt
Fixes #2553
> fix(plugin-odap-hermes): fix duplicate enum values of OdapMessageType

- weaver/common/protos/besu/view_data.proto
- weaver/rfcs/formats/views/besu.md
- weaver/rfcs/protocols/data-sharing/besu.md
feat(weaver/common): add data view protocol buffer spec & RFCs for Besu
> feat(weaver/common): add data view protocol buffer spec & RFCs for Besu

- examples/cactus-example-carbon-accounting-backend/src/utility-emissions-channel/typescript/package.json
- examples/cactus-example-electricity-trade/tools/periodicExecuter/package.json
- examples/cactus-example-electricity-trade/tools/transferNumericAsset/package.json
- examples/cactus-example-tcs-huawei/tools/periodicExecuter/package.json
- examples/cactus-example-tcs-huawei/tools/transferNumericAsset/package.json
- examples/test-run-transaction/package.json
- examples/test-run-transaction/supply-chain-app-stub/package.json
- packages/cactus-plugin-ledger-connector-fabric-socketio/src/test/typescript/unit-test/package.json
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/basic-asset-transfer/chaincode-typescript/package.json
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/lock-asset/chaincode-typescript/package.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/unit-test/package.json
- packages/cactus-plugin-odap-hermes/package.json
- packages/cactus-plugin-odap-hermes/src/test/typescript/fabric-contracts/lock-asset/chaincode-typescript/package.json
- weaver/core/drivers/fabric-driver/package-local.json
- weaver/core/drivers/fabric-driver/package.json
- weaver/core/identity-management/iin-agent/package-local.json
- weaver/core/identity-management/iin-agent/package.json
- weaver/samples/besu/besu-cli/package-local.json
- weaver/samples/besu/besu-cli/package.json
- weaver/samples/besu/simpleasset/package.json
- weaver/samples/fabric/fabric-cli/package-local.json
- weaver/samples/fabric/fabric-cli/package.json
- weaver/sdks/besu/node/package-local.json
- weaver/sdks/besu/node/package.json
- weaver/sdks/fabric/interoperation-node-sdk/package-local.json
- weaver/sdks/fabric/interoperation-node-sdk/package.json
- yarn.lock
Pinned all of the versions to 4.9.5 in all of the packages.
Fixes #2532
> chore(deps): clean up typescript compiler dependency declarations

- examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/json/openapi.json
- examples/cactus-example-supply-chain-business-logic-plugin/src/main/json/openapi.json
- extensions/cactus-plugin-htlc-coordinator-besu/src/main/json/openapi.json
- extensions/cactus-plugin-object-store-ipfs/src/main/json/openapi.json
- packages/cactus-cmd-api-server/src/main/json/openapi.json
- packages/cactus-core-api/src/main/json/openapi.json
- packages/cactus-plugin-consortium-manual/src/main/json/openapi.json
- packages/cactus-plugin-htlc-eth-besu-erc20/src/main/json/openapi.json
- packages/cactus-plugin-htlc-eth-besu/src/main/json/openapi.json
- packages/cactus-plugin-keychain-aws-sm/src/main/json/openapi.json
- packages/cactus-plugin-keychain-azure-kv/src/main/json/openapi.json
- packages/cactus-plugin-keychain-google-sm/src/main/json/openapi.json
- packages/cactus-plugin-keychain-memory-wasm/src/main/json/openapi.json
- packages/cactus-plugin-keychain-memory/src/main/json/openapi.json
- packages/cactus-plugin-keychain-vault/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-iroha/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-iroha2/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-ubiquity/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-xdai/src/main/json/openapi.json
- packages/cactus-plugin-odap-hermes/src/main/json/openapi.json
- packages/cactus-plugin-persistence-ethereum/src/main/json/openapi.json
- packages/cactus-plugin-persistence-fabric/src/main/json/openapi.json
- tools/custom-checks/check-open-api-json-specs.ts
1. Adds a custom check that ensures that all the properties of the
license object are specified (name, identifier, url).
2. Optimized the custom-check that verifies the opan API json specs so
that it ignores **/node_modules/ not just node_modules (meaning that it
was only excluding the root dir not all sub-dirs of the packages as well)
Fixes #490
> build(openapi): license presence check

- jest.config.js
- jest.setup.console.logs.js
Configure jest to override it's internal console logger with the
regular console object provided by the JS runtime.
This way it does not have the extra information printed that is
not useful for 99% of our use-cases (100% of the known ones).
Fixes #2595
> test(jest): reduce Jest log verbosity - make logs more compact

- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-cactus.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-web3-eea.test.ts
- tools/docker/besu-multi-party-all-in-one/Dockerfile
- tools/docker/besu-multi-party-all-in-one/README.md
- tools/docker/besu-multi-party-all-in-one/env-config.ini
- tools/docker/besu-multi-party-all-in-one/supervisord.conf
- tools/docker/fabric-all-in-one/Dockerfile_v1.4.x
- tools/docker/fabric-all-in-one/Dockerfile_v2.x
- tools/docker/fabric-all-in-one/README.md
- tools/docker/fabric-all-in-one/docker-compose-v2.x.yml
- tools/docker/quorum-multi-party-all-in-one/Dockerfile
- tools/docker/quorum-multi-party-all-in-one/README.md
- tools/docker/quorum-multi-party-all-in-one/env-config.ini
- tools/docker/quorum-multi-party-all-in-one/supervisord.conf
- tools/docker/sawtooth-all-in-one/Dockerfile
- tools/docker/sawtooth-all-in-one/README.md
- `quorum-multi-party-all-in-one`: use newest `quorum-quorum-dev-quickstart`, update quorum versions to most recent available. Run ledger as `quorum` user (required by newer versions). Use docker compose V2 from alpine package registry instead of V1 from pip.
- `besu-multi-party-all-in-one`: similar changes as for quorum-multi-party-all-in-on. Fix broken besu private transaction tests.
- `fabric-all-in-one`: Use docker compose V2 from alpine package registry instead of V1 from pip.
- `sawtooth-all-in-one`: Use docker compose V2 from alpine package registry instead of V1 from pip.
Closes: #2593
Closes: #2557
> build(docker-compose): upgrade to docker compose V2

- packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
Enable sending funds to an existing account.
New method created:
* sendEthToAccount
closes #2250
> feat(besu-test-ledger): send funds to already created address

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/add-orgs.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/fabric-watch-blocks-v1-endpoint.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/obtain-profiles.test.ts
- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
Created new methods to avoid breaking changes in the API exported.
New methods created:
* capitalizedMspIdOfOrg
* enrollAdminV2
* enrollUserV2
* createCaClientV2
closes #2248
> feat(fabric-test-ledger): add support to enrolling users in different Orgs

- commitlint.config.js
- packages-python/cactus_validator_socketio_indy/setup.py
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/.idea/jarRepositories.xml
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/build.gradle.kts
- tools/docker/corda-all-in-one/Dockerfile
- tools/docker/corda-all-in-one/corda-v4_8-flowdb/Dockerfile
- tools/docker/corda-all-in-one/corda-v4_8-flowdb/build.gradle
- tools/docker/corda-all-in-one/corda-v4_8/Dockerfile
- weaver/common/protos-java-kt/build.gradle
- weaver/common/protos-java-kt/repositories.gradle
- weaver/core/drivers/corda-driver/build.gradle
- weaver/core/network/corda-interop-app/build.gradle
- weaver/core/network/corda-interop-app/repositories.gradle
- weaver/samples/corda/corda-simple-application/build.gradle
- weaver/samples/corda/corda-simple-application/clients/build.gradle
- weaver/samples/corda/corda-simple-application/repositories.gradle
- weaver/samples/corda/fungible-house-token/build.gradle
- weaver/sdks/corda/build.gradle
- weaver/tests/network-setups/corda/dev/Corda_Network/build.gradle
- weaver/tests/network-setups/corda/dev/Corda_Network2/build.gradle
- weaver/tests/network-setups/corda/scripts/get-cordapps.sh
- weaver/tests/network-setups/shared/charts/corda-net/corda-gradle/build.gradle
CVE ID CVE-2022-29217
GHSA ID GHSA-ffqj-6fqr-9h24
https://github.com/advisories/GHSA-ffqj-6fqr-9h24
https://github.com/hyperledger/cacti/security/dependabot/175
Fixes #2614
> fix(cactus-validator-socketio-indy): upgrade pyjwt to 2.4.0

- examples/test-run-transaction/supply-chain-app-stub/package.json
CVE-2022-24785
- https://nvd.nist.gov/vuln/detail/cve-2022-24785
GHSA-8hfj-j24r-96c4
- https://github.com/advisories/GHSA-8hfj-j24r-96c4
Fixes #2608
> docs(examples): fix CVE-2022-24785 - test-run-transaction/supply-chain-app-stub

- packages/cactus-core-api/Cargo.lock
- packages/cactus-core-api/Cargo.toml
- packages/cactus-core-api/src/main/rust/generated/proto-rs/common.ack.rs
- packages/cactus-core-api/src/main/rust/generated/proto-rs/common.query.rs
- packages/cactus-core-api/src/main/rust/generated/proto-rs/common.state.rs
- packages/cactus-core-api/src/main/rust/generated/proto-rs/driver.driver.rs
- packages/cactus-core-api/src/main/rust/generated/proto-rs/networks.networks.rs
- packages/cactus-core-api/src/main/rust/generated/proto-rs/relay.datatransfer.rs
Performs a minor semver upgrades to tonic, tonic-build and prost so
that the vulnerable version of prost-types is no longer in the
dependency tree.
Fixes #2612
> fix(cactus-core-api): address CVE-2021-38192 - GHSA-x4qm-mcjq-v2gf

- packages/cactus-cmd-api-server/package.json
- packages/cactus-core/package.json
- packages/cactus-plugin-keychain-aws-sm/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-plugin-keychain-google-sm/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-plugin-keychain-vault/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/openapi/openapi-validation.test.ts
- packages/cactus-plugin-ledger-connector-corda/package.json
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/openapi/openapi-validation-go.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/openapi/openapi-validation-no-keychain.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/openapi/openapi-validation.test.ts
- packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/openapi/openapi-validation-no-keychain.test.ts
- packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/openapi/openapi-validation.test.ts
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/openapi/openapi-validation.test.ts
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/openapi/openapi-validation.test.ts
- yarn.lock
Addresses the advisory:
https://github.com/hyperledger/cacti/security/dependabot/176
The dicer dependency is included via the express-openapi-validator
package which needed to be upgraded project-wide for a fix.
The test cases for verifying that the OpenAPI validation still works had
to be updated because the way invalid field names are represented by
the new version of the validator have been changed. It used to say if
in the request body there was a problematic field ".body.SOME_FIELD"
but now it says instead "/body/SOME_FIELD" so a minor change was needed
in the test cases assertions to make sure they are not ending up with
false negative results.
URL https://github.com/advisories/GHSA-wm7h-9275-46v2
CVE ID CVE-2022-24434
GHSA ID GHSA-wm7h-9275-46v2
Fixes …
> fix(security): crash in HeaderParser in dicer

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-identities.test.ts
- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- tools/docker/fabric-all-in-one/Dockerfile_v2.x
Hard to dertermine which exact vulnerabilities will this be fixing because
other pull requests also upgrade the image version of this container in
the time while the pull request for this commit was open.
Nevertheless, it is an upgrade of versions and therefore some of the CVEs
are very likely getting addressed by it.
Fixes https://github.com/hyperledger/cacti/issues/2057
Signed-off-by: zondervancalvez <zondervan.v.calvez@accenture.com>
> tools(fabric2-all-in-one): fix multiple vulnerabilities - 2023-08-17

- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json-private.test.ts
Added an extra wait for the member 2 contract invocation
where we first obtain the receipt thereby forcing
the execution to wait until it has been mined on
member 2 as well.
Fixes #2635
> test(connector-quorum): fix flaky v2.3.0-deploy-contract-from-json-private.test

- tools/docker/rust-compiler/Dockerfile
1. Upgraded the rust version of the image to v1.72.0 - short term fix
2. The longer term fix is that I locked down the version of wasm-pack to
the current latest stable (v0.12.1) so that the auto-upgrade
doesn't bite is again like this where the newer wasm-pack
starts demanding a newer rust compiler which we don't
have because we are pinning to a specific version through
the image tag that's being used.
Fixes #2641
> test(ghcr-rust-compiler): fix image build - anstream v0.5.0 cannot be built

- packages/cactus-plugin-htlc-eth-besu/package.json
- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-test-plugin-htlc-eth-besu/package.json
- packages/cactus-test-plugin-ledger-connector-besu/package.json
- yarn.lock
Upgraded to v22.4.0 but did not yet delete our hand-built typings
because the ones that v22.4.0 ships with are broken (do not match the
actual implementation forcing programmers to fight the compiler
needlessly)
Fixes #2648
> build(deps): upgrade web3js-quorum to v22.4.0

- tools/docker/corda-all-in-one/corda-v4_8/Dockerfile
1. Fixed the OpenSSH related problems by wiping the default installation
of it that ships with the distro (Alpine Linux images)
2. Updated the kotlin samples repository's code manually so that it
specifies the platform version as 11 instead of 12 for the basic contracts
which is what we need for Corda v4.8 and v4.9 as well (I'm guessing that
platform  version 12 will stand for v5 when it becomes GA but not sure)
The manual update is done via sed-ing at image build time right after
the kotlin samples repository has been cloned.
Fixes #2621
> build(corda-all-in-one-obligation): fix build unable to select packages

- .github/workflows/ci.yaml
**Trivy** is a cutting-edge security tool designed to enhance the safety of containerized applications by conducting thorough vulnerability assessments. Specifically developed for scanning container images, ranging from low-severity issues to critical threats. It employs an intelligent rating system to categorize vulnerabilities based on their severity levels, ensuring that **high** to **critical** vulnerabilities are given special attention. Upon detecting vulnerabilities that fall within this elevated range, Trivy will throw an **error**.
By integrating Trivy into our deployment pipeline, we can proactively mitigate security risks and enhance the resilience of our repository.
Fixes https://github.com/hyperledger/cacti/issues/1876
Depends On https://github.com/hyperledger/cacti/pull/2121 …
> ci: add container scanning to default checks

- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-api-server/src/main/json/openapi.json
- packages/cactus-cmd-api-server/src/main/kotlin/generated/openapi/kotlin-client/README.md
- packages/cactus-cmd-api-server/src/main/kotlin/generated/openapi/kotlin-client/src/main/kotlin/org/openapitools/client/apis/DefaultApi.kt
- packages/cactus-cmd-api-server/src/main/proto/generated/openapi/services/default_service.proto
- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-cmd-api-server/src/main/typescript/generated/proto/protoc-gen-ts/services/default_service.ts
- packages/cactus-cmd-api-server/src/main/typescript/generated/proto/protoc-gen-ts/services/default_service_grpc_pb.d.ts
- packages/cactus-cmd-api-server/src/main/typescript/generated/proto/protoc-gen-ts/services/default_service_pb.d.ts
- packages/cactus-cmd-api-server/src/main/typescript/openapi/get-open-api-spec.ts
- packages/cactus-cmd-api-server/src/main/typescript/web-services/get-open-api-spec-v1-endpoint.ts
- packages/cactus-cmd-api-server/src/main/typescript/web-services/grpc/grpc-server-api-server.ts
- packages/cactus-cmd-api-server/src/test/typescript/unit/get-open-api-spec-v1-endpoint.test.ts
- packages/cactus-core/package.json
- packages/cactus-core/src/main/typescript/public-api.ts
- packages/cactus-core/src/main/typescript/web-services/get-open-api-spec-v1-endpoint-base.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-open-api-spec-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/unit/get-open-api-spec-v1-connector-besu.test.ts
- packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
- yarn.lock
commit ff29e94e981a80a8665d82f2190f34f79087531e (HEAD -> pr/charellesandig/1994, charellesandig/issue1877)
Date:   Wed Sep 13 16:39:42 2023 -0700
feat(cmd-api-server): add GetOpenApiSpecV1Endpoint (HTTP GET)
The new endpoint can serve up the OpenAPI specification file of the
API server via a get request without any parameters needed.
Under the hood it uses the re-usable common base endpoint class that
we've recently added to the core package.
The test case at this file path demonstrates how to use it via the API
client:
`packages/cactus-cmd-api-server/src/test/typescript/unit/get-open-api-spec-v1-endpoint.test.ts`
commit ebd0abfebdfd6051ca61d278f16b49787c168887 …
> feat(cmd-api-server): swagger.json endpoints

- package.json
> build(codegen): fix URL of OpenAPI generator jar v6.6.0 not 6.3.0

- examples/cactus-example-carbon-accounting-backend/package.json
- examples/cactus-example-cbdc-bridging-backend/package.json
- yarn.lock
Upgraded hardhat to newer versions which don't depend on flat at all.
Fixes #2667
> docs(example-cbdc-bridging-backend): fix CVE-2020-36632

- examples/test-run-transaction/supply-chain-app-stub/package.json
Both mongoose and the mongodb NodeJS driver dependency appeared to be
completely unused so instead of upgrading I just removed them.
Fixes #2669
> docs(examples): fix Mongoose Prototype Pollution vulnerability

- packages/cactus-cmd-api-server/package.json
- packages/cactus-plugin-ledger-connector-fabric-socketio/package.json
- weaver/samples/fabric/fabric-cli/package-local.json
- weaver/samples/fabric/fabric-cli/package.json
- yarn.lock
Upgraded all imports of protobufjs to non-vulnerable
versions (v7.2.5)
Fixes #2682
> fix(cmd-api-server): fix CVE-2023-36665 protobufjs Prototype Pollution vuln

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
The linter warning for unexpected any was fixed with Record<string, unknown>
[skip ci]
Closes: #2677
> style: fix unexpected any linter w in startCockpitFileServer

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
Imported CorsOptionsDelegate and CorsRequest and typed corsOptionsDelegate to it
Closes: #2674
Possibly not a chore, but a style issue
[skip ci]
> chore: fix linter warning in CreateCorsMiddleware

- packages/cactus-api-client/src/main/typescript/api-client.ts
Used the suggester Record<string, unknown> to replace any
[skip ci]
Closes: #2675
> style: fix unexpected any linter warnings in extendWithT

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-common/package.json
- packages/cactus-common/src/main/typescript/exception/coerce-unknown-to-error.ts
- packages/cactus-common/src/main/typescript/exception/create-runtime-error-with-cause.ts
- packages/cactus-common/src/main/typescript/exception/error-from-symbol.ts
- packages/cactus-common/src/main/typescript/exception/error-from-unknown-throwable.ts
- packages/cactus-common/src/main/typescript/public-api.ts
- packages/cactus-common/src/main/typescript/types/has-key.ts
- packages/cactus-common/src/test/typescript/unit/exception/create-runtime-error-with-cause.test.ts
Utility functions to conveniently re-throw excpetions typed as unknown
by their catch block (which is the default since Typescript v4.4).
Example usage can and much more documentation can be seen here:
packages/cactus-common/src/main/typescript/exception/create-runtime-error-with-cause.ts
and here
packages/cactus-common/src/test/typescript/unit/exception/create-runtime-error-with-cause.test.ts
Closes: #1702
[skip ci]
Signed-off-by: Michael Courtin <michael.courtin@accenture.com>
> feat(cactus-common): add createRuntimeErrorWithCause() & newRex()

- .github/workflows/.dast-nuclei-cmd-api-server.yaml
- .github/workflows/ghpkg-all-kotlin-api-clients-publish.yaml
- BUILD.md
- examples/supply-chain-app/README.md
- package.json
> build(setup): remove install-yarn and document new yarn setup

- packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/get-keychain-entry-endpoint.ts
- packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/set-keychain-entry-endpoint.ts
- packages/cactus-plugin-keychain-vault/src/main/typescript/web-services/get-keychain-entry-endpoint-v1.ts
- packages/cactus-plugin-keychain-vault/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-plugin-ledger-connector-quorum/package.json
- packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-web3-method-v1.test.ts
- packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/api-client/verifier-integration-with-quorum-connector.test.ts
- packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
- packages/cactus-test-tooling/src/test/typescript/integration/quorum/quorum-test-ledger/constructor-validates-options.test.ts
- tools/docker/quorum-all-in-one/start-quorum.sh
- yarn.lock
- add WebsocketProvider options to quorum LP
- add test for calling getBlock with verifier
> feat(quorum): add WebsocketProvider options to quorum LP

- packages/cactus-plugin-ledger-connector-ethereum/package.json
- packages/cactus-plugin-ledger-connector-ethereum/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/plugin-ledger-connector-ethereum.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/types/model-type-guards.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/web-services/watch-blocks-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-contract-deploy-and-invoke-using-json-object-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-contract-deploy-and-invoke-using-keychain-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-invoke-web3-contract-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-transact-and-gas-fees.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/manual/geth-alchemy-integration-manual-check.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/unit/model-type-guards.test.ts
- packages/cactus-test-plugin-ledger-connector-ethereum/package.json
- packages/cactus-test-plugin-ledger-connector-ethereum/src/test/typescript/integration/api-client/verifier-integration-with-ethereum-connector.test.ts
- yarn.lock
- Add legacy and EIP1559 gas configuration options to transaction requests.
- Legacy gas configuration is updated to EIP1559 using the same logic as web3 libraries.
- Update the tests to work with new API.
- Added test suite to test new features - `geth-transact-and-gas-fees.test.ts`
Depends on #2581
> feat(cactus-plugin-ledger-connector-ethereum): support London fork gas prices

- PULL_REQUEST_TEMPLATE.md
fixes: #91
adds Pull Request Template on the root directory as guideline for contributors.
[skip ci]
> docs: add Pull Request Template

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
This pull request addresses issue #2676  by fixing an Unexpected any linter warning in the getOrCreateWebServices() method of the ApiServer class. The warning occurred due to a typecast using (app as any). 
Replaced (app as any) with (app as express.Express)[httpVerbPrometheus as keyof express.Express](httpPathPrometheus, prometheusExporterHandler);
The use of keyof here is crucial because it ensures that httpVerbPrometheus and httpVerb are treated as the valid key of the express.Express type. This is necessary because HTTP verbs, like GET, POST, PUT etc... should be treated as keys within the express.Express type. By casting httpVerbPrometheus as keyof express.Express, we enforce type safety and prevent potential runtime errors that could occur if an invalid HTTP verb is used. In …
> style(cmd-api-server): fix any linter in getOrCreateWebServices()

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/test/typescript/integration/jwt-unprotected-endpoint-authz-ops-confirm.test.ts
1. Refactored the assertion to inspect the nested inner exception's message
instead of the outer, more generic one.
2. Also fixed a bug in the ApiServer class where it was constructing a comma
seperated list of unprotected endpoints incorrectly and ended up with
[object object] as the CSV instead of a list of the HTTP URLs of the endpoints.
Fixes #2711
[skip ci]
> test(cmd-api-server): fix expected Non-exempt unprotected got Failed to start

- examples/cactus-example-discounted-asset-trade/balance-management.ts
- examples/cactus-example-discounted-asset-trade/template-trade-management.ts
- examples/cactus-example-discounted-asset-trade/transaction-ethereum.ts
- examples/cactus-example-discounted-asset-trade/transaction-fabric.ts
- examples/cactus-example-discounted-asset-trade/transaction-indy.ts
- examples/cactus-example-tcs-huawei/BalanceManagement.ts
- examples/cactus-example-tcs-huawei/BusinessLogicTcsElectricityTrade.ts
- examples/cactus-example-tcs-huawei/TransactionEthereum.ts
- examples/cactus-example-tcs-huawei/package.json
- packages/cactus-cmd-socketio-server/src/main/typescript/verifier/DriverCommon.ts
- packages/cactus-core-api/src/main/typescript/plugin/ledger-connector/i-send-request-response-v1.ts
- packages/cactus-core-api/src/main/typescript/plugin/ledger-connector/i-socket-api-client.ts
- packages/cactus-core-api/src/main/typescript/public-api.ts
- packages/cactus-test-plugin-ledger-connector-ethereum/src/test/typescript/integration/api-client/verifier-integration-with-ethereum-connector.test.ts
- packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/api-client/verifier-integration-with-quorum-connector.test.ts
- packages/cactus-verifier-client/src/main/typescript/verifier.ts
- yarn.lock
An interface representing the response object of the send sync and send async
request methods on the connection-chain verifier API.
Also great when trying to help bridge the gap between the API returning
results as `unknown` and the tests needing auto-completion for the properties
to assert for type of data at runtime.
@see {ISocketApiClient<BlockType>}
@see {Verifier<LedgerApiType extends ISocketApiClient<unknown>>}
@see {IVerifier}
refactor(core-api,verifier-client): use unknown instead of any type
1. Changes the ISocketApiClient and the Verifier type definitions so that
instead of `any` they are heavily relying on `unknown` which helps spotting
bugs in the code where type checks should be done at runtime but currently …
> feat(cactus-core-api): add ISendRequestResultV1<T> for Fujitsu verifier

- packages/cactus-plugin-ledger-connector-cdl-socketio/README.md
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/connector/ServerPlugin.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/connector/cdl-request.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/connector/type-defs.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/test/typescript/integration/cdl-connector-manual.test.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/tsconfig.json
- Add alternative auth method using subscriptionKey instead of accessToken.
- Both auth methods are supported but can't be used at the same time.
- Adjust manual test script to work with subscriptionKey.
- Build manual script as part of the main build.
- Update README.
- Remove default `api/v1/` URL prefix for compatibility with https://en-portal.research.global.fujitsu.com/
[ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this …
> feat(cactus-plugin-ledger-connector-cdl-socketio): support subscription key auth

- tools/docker/indy-sdk-cli/Dockerfile
**Change Description:**
In the Dockerfile, the issue related to NodeJS was addressed by updating the NodeJS installation method to use the new NodeSource installation method. The previous method using `curl -sL https://deb.nodesource.com/setup_16.x | bash -` had become deprecated, so the new method was applied for compatibility with the latest practices.
The specific changes made in the Dockerfile are as follows:
1. Removed the old installation method for NodeJS:
```Dockerfile
```
2. Added the new NodeSource installation method:
```Dockerfile
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /usr/share/keyrings/nodesource-archive-keyring.gpg \
&& echo "deb [arch=amd64 signed-by=/usr/share/keyrings/nodesource-archive-keyring.gpg] …
```
> build(tools/docker/indy-sdk-cli): fix deprecation deb.nodesource.com/setup_16.x

- examples/cactus-example-electricity-trade/package.json
- examples/cactus-example-tcs-huawei/package.json
- package.json
- weaver/core/drivers/fabric-driver/package.json
- weaver/core/identity-management/iin-agent/package.json
- weaver/samples/fabric/fabric-cli/package.json
- weaver/sdks/besu/node/package.json
- weaver/sdks/fabric/interoperation-node-sdk/package.json
- yarn.lock
I ran `yarn up eslint-plugin-prettier --exact` to produce the diff of
this commit. I also ran `yarn lint` to verify that the linter works.
[skip ci]
Fixes #2727
[x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
[x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
[x] Follow the Commit Linting …
> build(lint): fix linter - doesn't work after last prettier upgrade to v3.0.0

- .gitignore
- packages/cactus-common/src/main/typescript/error-utils.ts
- packages/cactus-plugin-ledger-connector-ethereum/README.md
- packages/cactus-plugin-ledger-connector-ethereum/package.json
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/plugin-ledger-connector-ethereum.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/types/model-type-guards.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/web-services/deploy-contract-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/web-services/invoke-contract-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/web-services/invoke-raw-web3eth-contract-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/web-services/invoke-raw-web3eth-method-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/web-services/run-transaction-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/web-services/watch-blocks-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/benchmark/cli/run-benchmark-environment.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/benchmark/setup/artillery-helper-functions.js
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/benchmark/setup/geth-benchmark-config.yaml
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/benchmark/setup/geth-benchmark-env.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-invoke-web3-contract-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/unit/model-type-guards.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/tsconfig.json
- packages/cactus-test-geth-ledger/src/main/typescript/geth-test-ledger.ts
- packages/cactus-test-plugin-ledger-connector-ethereum/src/test/typescript/integration/api-client/verifier-integration-with-ethereum-connector.test.ts
- tools/docker/geth-all-in-one/Dockerfile
- yarn.lock
- Return JSON error before checking for Error instance in safeStringifyException
(for cases when custom errror extends `Error` with `toJSON()` method)
- Move artillery dependency up to the root (since its common tool depdenecy)
- Add web3js http/ws provider options to connector.
- Make http provider optional (can run on ws web3js provider only)
- Don't register async endpoints when WS provider is not available.
- Return 400 for invalid responses from ethereum ledger (to distinguish from connector errors)
- In docker `geth-all-in-one` allow overwriting of default options when starting the ledger.
- Add artillery stress test scripts
- Template config and artillery functions file
- Common environment setup file
- CLI for running the test environment on a separate machine.
- Jest test to run …
> feat(cactus-plugin-ledger-connector-ethereum): add stress test

- packages/cactus-plugin-ledger-connector-ethereum/README.md
- packages/cactus-plugin-ledger-connector-ethereum/package.json
- packages/cactus-plugin-ledger-connector-ethereum/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/plugin-ledger-connector-ethereum.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-contract-deploy-and-invoke-using-keychain-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-invoke-web3-method-v1.test.ts
- yarn.lock
- Add proxy endpoint handling. Requests sent to this endpoint will be passed directly to the ethereum node.
- Add test to verify that proxy is working.
- Update README of ethereum connector.
[ ] Follow the Commit Linting specification. You may refer to this …
> feat(cactus-plugin-ledger-connector-ethereum): add json-rpc proxy

- packages/cactus-common/src/main/typescript/http/express-http-verb-method-name.ts
- packages/cactus-common/src/main/typescript/public-api.ts
- packages/cactus-common/src/test/typescript/unit/http/express-http-verb-method-name.test.ts
1. Also ships with a user-defined typescript type-guard so that we can
ensure at runtime that the string literal value is indeed one of the
valid ExpressJS HTTP verb method names.
2. The primary use-case for this is checking at runtime the HTTP verb
name of OpenAPI specifications that are being loaded into the API.
[x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
[x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this …
> feat(common): add express http verb method name string literal type

- examples/cactus-example-electricity-trade/BusinessLogicElectricityTrade.ts
- examples/cactus-example-electricity-trade/TransactionEthereum.ts
- examples/cactus-example-electricity-trade/config/usersetting.yaml
- examples/cactus-example-electricity-trade/config/validator-registry-config.yaml
- packages/cactus-plugin-ledger-connector-ethereum/README.md
- packages/cactus-plugin-ledger-connector-ethereum/package.json
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/sign-utils.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-contract-deploy-and-invoke-using-keychain-v1.test.ts
- yarn.lock
- Add methods for signing transactions to ethereum connector.
- Modify offline signing test to use this new method.
- Modify electricity trade sample to use new signing method.
- Add offline signature section to ethereum connector readme.
[ ] Follow the Commit …
> feat(cactus-plugin-ledger-connector-ethereum): add signing utils

- examples/cactus-example-cbdc-bridging-backend/src/fabric-contracts/cbdc-erc-20/javascript/lib/tokenERC20.js
- examples/cactus-example-cbdc-bridging-frontend/src/api-calls/fabric-api.js
docs(examples/cbdc): fix mismatch of Fabric identities in GET, POST requests
The state keys were not being generated correctly for some reason
It was working before without code changes so my best guess is that
the Fabric ledger/SDK versions were changed and that's what tripped it
up somehow.
Fixes #2739
[skip ci]
cc: @petermetz @Anusha-Padmanabhan
> docs(examples/cbdc): fix mismatch of Fabric identities in GET and POST requests

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
This addresses the shortcomings of the linter fix provided in #2751, which
uses unchecked casts to the linter warnings go away.
With the fix of #2751, at runtime, the possibility of a crash is still there
exactly as before, but it has silenced the linter about calling that
possibility out.
We now use a type guard to check the type of the object before casting it
and therefore ensure that at runtime the cast will not produce a crash.
[skip ci]
Depends on #2751
Depends on #2754
[x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, …
> fix(cmd-api-server): add runtime type validation to HTTP verbs pulled from OAS

- packages/cacti-ledger-browser/package.json
- yarn.lock
GitHub Security Advisory link to the vulnerability:
https://github.com/hyperledger/cacti/security/dependabot/260
[skip ci]
[x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
[x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
[x] Follow the Commit Linting specification. You may refer to this …
> fix(ledger-browser): fix vulnerability CVE-2022-37601

- examples/cactus-example-cbdc-bridging-backend/package.json
- extensions/cactus-plugin-object-store-ipfs/package.json
- package.json
- packages/cactus-plugin-keychain-google-sm/package.json
- packages/cactus-plugin-odap-hermes/package.json
- yarn.lock
1. Upgraded fabric-network from 2.2.10 to 2.2.18 wherever it was still 2.2.10
2. Upgraded ipfs-http-client project-wide from 51.0.1 to 60.0.1
3. Upgraded @google-cloud/secret-manager from 3.9.0 to 5.0.1
This is the second try at fixing this issue. For some reason the first
PR didn't get it done. The most likely reason is that other commits
in the meantime added back the vulnerable versions of the packages, but
I'm not a 100% sure.
[skip ci]
Fixes #2682
[x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
[x] Have git sign off …
> fix(cmd-api-server): fix CVE-2023-36665 protobufjs try 2

- package.json
- yarn.lock
1. Updated the yarn.lock file via yarn up -R and
2. Also added a forced resolution of the versions in the root
package.json for good measure.
[skip ci]
Fixes #2335
[ x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
[x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
[x] Follow the Commit Linting …
> build(deps): explicit bump of http-cache-semantics to >=4.1.1

- packages/cactus-plugin-ledger-connector-cdl-socketio/README.md
- packages/cactus-plugin-ledger-connector-cdl-socketio/sample-config/default.yaml
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/connector/cdl-request.ts
- packages/cactus-plugin-ledger-connector-cdl-socketio/src/main/typescript/connector/type-defs.ts
- Add separate configurations for endpoints supporting access token and subscription key separately.
- This is required by current public instance of CDL.
> feat(cactus-plugin-ledger-connector-cdl-socketio): separate endpoint for subscription key

- examples/cactus-example-cbdc-bridging/README.md
Update README.md with new instructions to run the frontend. Previously, the source code was not in the project and a default Docker image was being provided. Now, developers can start the frontend development server directly and run the code with live reload.
> docs(examples/cbdc): update README.md with new instructions to run

- package.json
- yarn.lock
This is a workaround for the problem Peter intorduced in the build with
an earlier commit where he upgraded axios to 1.5.1 universally.
The above had lead to a problem with the nano package, which is a
dependency of the fabric node SDK packages.
The longer term solution is to migrate to the newer Fabric Gateway
client SDK and completely remove the older fabric dependencies from
the project, but until we can do that (a big undertaking) we have to
be content with this shorter term workaround and hope that axios 0.27.2
does not turn out to be vulnerable critically (because that would force
our hand with upgrades again).
Partially addresses #2807 (not a full fix)
**A Must Read …
> build(deps): add resolutions: axios>=0.27.2, nano>=10.0.0

- tools/custom-checks/check-open-api-json-specs.ts
1. There was no "ERROR:" prefix for some of the problems that the check
was returning making it hard/not so obvious to figure out what the
actual problems are that are making the checks fail overall.
[skip ci]
> build(tools): fix custom-checks/check-open-api-json-specs error messages

- .devcontainer/devcontainer.json
> build(dev-container): add git auto-completion via .bashrc

- packages/cactus-core/package.json
- packages/cactus-core/src/main/typescript/public-api.ts
- packages/cactus-core/src/main/typescript/web-services/handle-rest-endpoint-exception.ts
- yarn.lock
1. This is a function that is designed to be called by all the REST API
endpoint implementations to (more) correctly handle errors.
2. The problem right now is that we do not differentiate between invalid
request errors (e.g. expected exceptions) vs.
legitimate crashes (e.g. unexpected exceptions)
What the above means is that a lot of our endpoints will crash with an
HTTP 500 error code returned to the client even if the problem as user-
error (such as a missing parameter that is mandatory).
3. With the new utility function the REST endpoint code can easily
apply the decision logic at runtime in their own catch blocks' and
set the HTTP response status code based on the information (context)
provided by the callee (most often the connector plugin's underlying
method that was called)
An …
> feat(cactus-core): add handleRestEndpointException utility to public API

- package.json
- packages/cactus-plugin-ledger-connector-ubiquity/package.json
- packages/cactus-plugin-ledger-connector-ubiquity/src/main/typescript/plugin-ledger-connector-ubiquity.ts
- yarn.lock
1. Couldn't get rid of vulnerable versions in a couple of dependencies
because the underlying dependencies have gone ESM only which is a blocker
for us at the moment unfortunately.
2. Swapped out the ubiquity TS client to a version of it that I self
published onto npm after a full renovation of all of its dependencies.
Depends on #2807 (because that one also has a couple of dependency bumps
that are needed to eliminate the vulnerabilities)
Fixes #2828
Fixes #2544
> build(deps): bulk fix CVEs via dependency resolution overrides 2023-10-23

- packages/cactus-cmd-api-server/Dockerfile
- packages/cactus-cmd-api-server/README.md
1. wget now gets installed explicitly
2. upgraded to ubuntu 22.04 LTS for the base image
3. upgraded nodejs to v20 LTS and npm to v10
3. Published the container image corresponding to this commit tagged as
`ghcr.io/hyperledger/cactus-cmd-api-server:2023-11-16-issue2894`
[skip ci]
Fixes #2894
> fix(cmd-api-server): healthcheck broken due to missing wget binary

- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
When deploying multiple contracts on multiple nodes, there are multiple
SSH connections being established.
When this all happens on the same host (because you are running the
all-in-one image for example) then the closing and opening of the same
SSH port is not instant between disconnect and connect operations of the
SSH client and connectivity problems come up.
Due to lack of time I quickly fixed this by adding a 5 second wait
between the disconnect and connect operations. Retries would be a much
better solution long term especially since race conditions can never
truly be fixed with hardcoded wait times that will sooner or later become
too short or too long depending on the exact nature of the problem.
[skip ci]
**Pull …
> fix(connector-corda): contract deployment SSH reconnect race condition

- yarn.lock
Run of the mill lock file out of sync issue that happens every now and
then by mistake when we forget to run yarn install before committing our
changes for a PR.
Could've been avoided if we had the `build-dev` CI action set to
required but for now it gives us a better chance of reaching 2.0.0
if it's disabled temporarily.
[skip ci]
> build(yarn): update the lock file because it got out of sync 2023-nov-22

- weaver/core/network/fabric-interop-cc/contracts/interop/certificate_utils.go
- weaver/sdks/corda/src/main/kotlin/org/hyperledger/cacti/weaver/sdk/corda/HashFunctions.kt
- weaver/sdks/fabric/interoperation-node-sdk/src/eciesCrypto.js
The Logic Behind the Problem
When RNG (Random Number Generator) values are not received through a hardware TRNG, seed values apply a certain pattern. (It takes a seed value such as a mathematical formula or time.) In response to this situation, there are various secure random classes to increase security.
Solution
Changes have been made to get random values using safe randomness instead of mathematical randomness. This increases the complexity of the pattern, making it difficult to discover even if data is listened to for long periods of time.
The changes that have been made;
- In the "certificate_utils.go" file, the random value was taken from the math class (mrand "math/rand") and used. By taking this random value from the secure random class, we obtain a more reliable random value. I …
> fix(weaver): usage of weak PRNG issue

- .devcontainer/devcontainer.json
1. Also performed a minor upgrade of the golang compiler version
because the version we were using had a bug in it (compiler bug)
[skip ci]
> build(devcontainer): switch to JDK 8 (for Corda v4) and Node 20 LTS

- packages/cactus-cmd-socketio-server/src/test/typescript/unit/cmd-socketio-blp-plugin.test.ts
- packages/cactus-plugin-keychain-azure-kv/src/test/typescript/integration/plugin-keychain-azure-kv.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/benchmark/setup/geth-benchmark-env.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-contract-deploy-and-invoke-using-json-object-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-contract-deploy-and-invoke-using-keychain-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-invoke-web3-method-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-transact-and-gas-fees.test.ts
- packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v2.3.0-deploy-contract-from-json.test.ts
- packages/cactus-plugin-ledger-connector-sawtooth/src/test/typescript/integration/sawtooth-monitoring-endpoints.test.ts
- packages/cactus-plugin-persistence-ethereum/src/test/typescript/integration/persistence-ethereum-functional.test.ts
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/withdraw-endpoint-invalid-id.test.ts
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/withdraw-endpoint.test.ts
- packages/cactus-test-verifier-client/package.json
- packages/cactus-test-verifier-client/src/main/typescript/verifier-with-go-eth-stress-check.ts
- packages/cactus-test-verifier-client/tsconfig.json
- yarn.lock
- Replace deprecated cactus-plugin-ledger-connector-go-ethereum-socketio with openapi-based cactus-plugin-ledger-connector-ethereum.
> test(cactus-test-verifier-client): replace socketio connector with eth openapi

- examples/cactus-example-cbdc-bridging-backend/src/crypto-material/crypto-material.json
- examples/cactus-example-cbdc-bridging-backend/src/fabric-contracts/asset-reference/typescript/src/asset-reference-contract.spec.ts
- examples/cactus-example-cbdc-bridging-backend/src/fabric-contracts/cbdc-erc-20/javascript/crypto-material/crypto-material.json
- examples/cactus-example-cbdc-bridging-backend/src/fabric-contracts/cbdc-erc-20/javascript/lib/tokenERC20.js
- examples/cactus-example-cbdc-bridging-frontend/src/api-calls/fabric-api.js
- examples/cactus-example-cbdc-bridging-frontend/src/crypto-material/crypto-material.json
* What I believe has been an update to the Fabric SDK has led the application to break due to having the Fabric identities hardcoded (for the Fabric-Ethereum ID mapping). This was first noted in #2739.
* An initial fix was deployed in #2802 but only the Mint function was changed, which caused other functions to be breaking at the moment (e.g., Escrow)
* This commit changes the crypto material files and reverts the workaround in PR #2802
* The crypto material is only used for testing and to show information in the frontend (e.g., requesting the balance of a specific user based on the identity)
* For critical operations, access control is being performed by the chaincode by using the call at the begining of the relevant methods
Fixes #2914
> docs(examples/cbdc): fix mismatch of fabric identities

- examples/cactus-example-supply-chain-frontend/package.json
- examples/cactus-example-supply-chain-frontend/src/app/bamboo-harvest/bamboo-harvest-detail/bamboo-harvest-detail.page.ts
- yarn.lock
Webpack does not play nice with the `run-time-error-cjs` package's exports.
I replaced it with the vanilla `run-time-error` because the front-end
package is fine with it (does not have ESM/CJS issues like other packages)
[skip ci]
---
> docs(examples): fix supply-chain-frontend run-time-error-cjs angular build

- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-web3-eea.test.ts
Commit to be reviewed
fix(connector-besu): toBuffer only supports 0x-prefixed hex
```
1. Updated private-deploy-contract-from-json-web3-eea.test.ts gaslimit from
3000000 to its hex equivalent
```
fixes: #2791
> fix(connector-besu): toBuffer only supports 0x-prefixed hex

- .devcontainer/devcontainer.json
1. This was forced through the domino effect of webpki related security
vulnerabilities that made it important for us to upgrade some dependencies
which on the other hand did not work with the slightly older rust compiler
that the dev container had had.
Relevant links for the vulnerabilities (this is not a fix yet)
- https://github.com/hyperledger/cacti/security/dependabot/762
- https://github.com/advisories/GHSA-8qv2-5vq6-g2g7
Skipping the CI because it's just a development environment change.
[skip ci]
---
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for …
> build(devcontainer): upgrade rust compiler to v1.74 (current latest stable)

- packages/cactus-plugin-persistence-fabric/README.md
- packages/cactus-plugin-persistence-fabric/src/main/typescript/plugin-persistence-fabric.ts
- Make not critical connector API private. This will allow easier refactors in the future. Most of the fields were used for testing purposes anyway.
- Change naming of some methods to match persistence-ethereum plugin.
> fix(persistence-fabric): hide not critical API

- .github/workflows/cacti-dev-container-vscode-publish.yaml
- .github/workflows/test_weaver-asset-exchange-besu.yaml
- .github/workflows/test_weaver-asset-exchange-corda.yaml
- .github/workflows/test_weaver-asset-exchange-fabric.yaml
- .github/workflows/test_weaver-asset-transfer.yaml
- .github/workflows/test_weaver-corda-interop-app.yaml
- .github/workflows/test_weaver-data-sharing.yaml
- .github/workflows/test_weaver-docker-build.yaml
- .github/workflows/test_weaver-go.yaml
- .github/workflows/test_weaver-node-pkgs.yaml
- .github/workflows/test_weaver-relay.yaml
1. Migrated from the stock GitHub Actions yaml syntax to using this custom
action[1] that allows us to skip the running of jobs based on path filtering.
The difference compared to the old solution is that this one won't just
skip the checks that are marked as required but it will pass them instead.
2. This is a suboptimal solution because we have to run each job so that
the code can be checked out and then examined for changes. This uses
resources that we should not have to expend, but currently there's no way
to avoid this because of the way the GitHub handles required checks that
are skipped (which cause a deadlock on the CI at the currently).
3. There is a relevant discussion thread about the problem here [2] which
should be voted on heavily so that it gets the necessary attention from …
> ci(github): fix path filtering of required but skipped workflows

- packages/cactus-common/src/main/typescript/exception/coerce-unknown-to-error.ts
- packages/cactus-core/package.json
- packages/cactus-core/src/main/typescript/web-services/handle-rest-endpoint-exception.ts
- packages/cactus-core/src/test/typescript/unit/handle-rest-endpoint-exception.test.ts
- packages/cactus-plugin-keychain-memory/src/main/typescript/web-services/delete-keychain-entry-endpoint-v1.ts
- packages/cactus-plugin-keychain-memory/src/main/typescript/web-services/get-keychain-entry-endpoint-v1.ts
- packages/cactus-plugin-keychain-memory/src/main/typescript/web-services/has-keychain-entry-endpoint-v1.ts
- packages/cactus-plugin-keychain-memory/src/main/typescript/web-services/set-keychain-entry-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/deploy-contract-solidity-bytecode-endpoint.ts
- yarn.lock
1. This is a security fix so that the exception serialization does not
accidentally XSS anybody who is looking at crash logs through some
admin GUI that is designed to show logs that are considered trusted.
Related discussion about `1)` can be seen at this other pull request:
https://github.com/hyperledger/cacti/pull/2893
---
> fix(cactus-common): coerceUnknownToError() now uses HTML sanitize

- tools/weaver-build-local.sh
- weaver/core/drivers/fabric-driver/package-local.json
- weaver/core/identity-management/iin-agent/package-local.json
- weaver/samples/besu/besu-cli/package-local.json
- weaver/samples/fabric/fabric-cli/package-local.json
- weaver/sdks/besu/node/package-local.json
- weaver/sdks/fabric/interoperation-node-sdk/package-local.json
- weaver/sdks/fabric/interoperation-node-sdk/src/MembershipManager.ts
- weaver/tests/network-setups/corda/scripts/check-nodes-status.sh
- Add a bash script in tools to build all the weaver packages in single command.
- Export `getMSPConfigurations` from fabric interop sdk (is imported in fabric cli, was causing compilation error on node 20)
- Move bash shebang to the top of `check-nodes-status`. On ubuntu 20 having this below was causing the file to be interpreted as sh (resulting in error)
- Update `package-local.json` files to be more inline with `package.json`.
> feat(weaver): add build script and fix minor issues

- .cspell.json
- packages/cactus-test-tooling/package.json
- packages/cactus-test-tooling/src/main/typescript/indy/indy-test-ledger.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
- packages/cactus-test-tooling/src/test/typescript/integration/indy/indy-test-ledger/indy-test-ledger.test.ts
- packages/cactus-test-verifier-client/package.json
- tools/docker/indy-all-in-one/script-cleanup.sh
- yarn.lock
- Add `IndyTestLedger` class to setup test indy ledger for testing purposes.
- Add functional tests for new test ledger class.
- Minor fix in cleaning up sample indy test ledger.
Depends on #2861
> feat(indy-test-ledger): add helper class for indy ledger

- packages/cactus-plugin-ledger-connector-ethereum/README.md
- packages/cactus-plugin-ledger-connector-ethereum/package.json
- packages/cactus-plugin-ledger-connector-ethereum/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/plugin-ledger-connector-ethereum.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/web-services/watch-blocks-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-contract-deploy-and-invoke-using-json-object-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-contract-deploy-and-invoke-using-keychain-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-invoke-web3-method-v1.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-monitoring-blocks.test.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-transact-and-gas-fees.test.ts
- packages/cactus-test-plugin-ledger-connector-ethereum/package.json
- packages/cactus-test-plugin-ledger-connector-ethereum/src/test/typescript/integration/api-client/verifier-integration-with-ethereum-connector.test.ts
- yarn.lock
- Update web3.js to 4.4 (I was hoping to use requested by me `safeDisconnect` method, but it seem to be still unavailable in this version)
- Support monitoring without websocket ethereum node access by using http polling method. Method is chosed automatically during runtime, based on supplied ethereum node URL.
- Refactored `WatchBlocksV1Endpoint` into base class and child classes that implement monitoring strategies. `WatchBlocksV1Endpoint` is now instantiated with factory method. This will allow easier addition of new strategies in the future.
- Add monitoring tests to ethereum connector pacakge, remove overlaping tests from verifier-integration-with-ethereum-connector.test.
For rebasing and squashing, …
> feat(ethereum-connector): support block monitoring with http only connection

- packages/cactus-core/package.json
- packages/cactus-core/src/main/typescript/consensus-has-transaction-finality.ts
- packages/cactus-core/src/main/typescript/web-services/get-open-api-spec-v1-endpoint-base.ts
- packages/cactus-core/src/main/typescript/web-services/handle-rest-endpoint-exception.ts
- packages/cactus-core/src/main/typescript/web-services/register-web-service-endpoint.ts
- yarn.lock
1. The GetOpenApiSpecV1EndpointBase<S, P> class now has the request
handler migrated to the new error handling mechanism that automatically
differentiates between HTTP statuses of 4xx and 5xx.
2. The register-web-service-endpoint utility function uses the new error
handling utilities as well, but on the lower level, e.g. it coerces unknown
errors to RuntimeError instances to minimize the risk of information loss
when re-throwing the inner exception with more context attached to it.
3. The consensus-has-transaction-finality file was similarly migrated
to the new error handling mechanisms.
4. A dependency to the cactus-core package was added for the easier handling
of HTTP specific errors. The http-errors-enhanced-cjs package contains
useful shorthands for HTTP-aware error handling and can …
> refactor(cactus-core): catch block get-open-api-spec-v1-endpoint-base

- weaver/sdks/corda/src/main/kotlin/org/hyperledger/cacti/weaver/sdk/corda/CredentialsExtractor.java
Fixes: #2767
This pull request addresses the issue of improper exception handling. The need is to wrap the expected exceptions in a try-catch block and handle them explicitly.
- Enclosed the existing code within a try-catch block to capture exceptions.
- Added contextual information in the logs, and the exception is re-thrown within the getConfig() function, as part of the exception propagation process.
> fix(weaver): improper exception handling

- packages/cactus-plugin-ledger-connector-fabric/Dockerfile
Updated the version of the api server used in the docker file.
Fixes #2864
> fix(connector-fabric): address CVEs: CVE-2022-21190, CVE-2021-3918

- .dcilintignore
> style(weaver): fix DCI lint errors related to gradle wrapper scripts

- packages/cactus-core/src/main/typescript/web-services/handle-rest-endpoint-exception.ts
The fix was to start statically importing the http helper library we use
in `packages/cactus-core/src/main/typescript/web-services/handle-rest-endpoint-exception.ts`
instead of how it was (dynamic imports at runtime).
1. There have been reports of dynamic imports causing segmentation
faults in the NodeJS process when Jest is involved.
2. It is looking like this bug was another instance of that manifesting
but slightly differently because this time around Jest decided to hide
the stack trace of it as well.
3. Because of `2)` we have no specific evidence of the theory. We can only
say that the change in this commit made the problem go away, but since
there never was any crash logs or stack traces on the CI environment,
this remains a conjecture.
4. Trying to reproduce the issue locally …
> test(cactus-core): fix false negative test results

- packages/cacti-ledger-browser/package.json
- yarn.lock
- Bump vite to 4.5.2 to solve security issue reported by dependabot in https://github.com/hyperledger/cacti/pull/2999
- Update other vite and build plugins to latest versions.
- Update solidjs and solidjs router to fix runtime issues.
> build(deps-dev): bump vite and other ledger-browser deps

- packages/cactus-core/src/test/typescript/unit/handle-rest-endpoint-exception.test.ts
This change makes it easier to read and debug some of the assertions of
the test case which are a little convoluted due to the usage of the Jest
spies.
These changes were done as part of another fix but ultimately turned out
to be not a factor for that fix and therefore I thought it bess to separate
the change out onto it's own PR to make it easier to review.
Related to #2966 but this is not the actual fix.
> test(cactus-core): refactor handle-rest-endpoint-exception.test.ts

- tools/clear-openapi-codegen-folders.js
Extended the existing globs in the clean script to include the back-end
code generated via the `kotlin-spring` template as well.
1. Previously only the generated client code was removed and regenerated
but with this change we now have the generated corda connector backend
API kotlin code removed as well.
2. The build files such as the build.gradle.kts and pom.xml files are not
deleted for now just the files under the `api` and the `model` directories
within the src/main and src/test code folders.
3. Running the delete script and then the code generation results in no
git index changes which is what we strive for.
4. The reason why we needed a slightly more complicated glob pattern
for achieving this is because the back-end code requires hand-written
implementation for the endpoints which …
> build(tools): codegen clean script now removes corda kotlin-spring src

- .devcontainer/devcontainer.json
1. This will result in the `trivy` binary being available on the path
of the dev container after a first/re-build.
2. The tool can be used to scan dependencies for versions that have
vulnerabilities.
3. The scanning has to be done a per-package basis instead of being
possible to scan the entire mono-repo in one fell swoop.
4. The documentation for the tool can be found here: https://github.com/aquasecurity/trivy
> build(devcontainer): add trivy to the image specification

- .cspell.json
- weaver/core/drivers/corda-driver/README.md
- weaver/core/drivers/corda-driver/build.gradle
1. The build.gradle file now has the maven publish plugin pulled which
can be used to generate pom.xml files that we don't really plan on using
for publishing but are still necessary to have in a temporary fashion
because the scanning tool (Trivy) only suports scanning dependencies
for vulnerabilities via pom.xml files of the Maven tool but not through
`build.gradle` files of the Gradle tool.
2. The `README.md` file was updated with detailed steps on how to run a
scan that includes generating the pom file, renaming it according to the
requirements of Trivy itself and then running the actual scan.
3. Some of the cspell issues have been rectified by adding new words to
the config.
**Character …
> build(weaver/corda-driver): add Trivy scanning capability and steps

- .github/workflows/ci.yaml
- .github/workflows/test_weaver-asset-exchange-besu.yaml
- .github/workflows/test_weaver-asset-exchange-corda.yaml
- .github/workflows/test_weaver-asset-exchange-fabric.yaml
- .github/workflows/test_weaver-asset-transfer.yaml
- .github/workflows/test_weaver-corda-interop-app.yaml
- .github/workflows/test_weaver-data-sharing.yaml
- .github/workflows/test_weaver-docker-build.yaml
- .github/workflows/test_weaver-go.yaml
- .github/workflows/test_weaver-relay.yaml
- Current file match glob is incorrect and never matches a file.
- I didn't find a way to filter files by extension (as it was attempted now) so I propose to loose up the rules and run the test if any file in a package has changed.
- I've noticed in another PR (https://github.com/hyperledger/cacti/pull/3018) that most tests didn't run, even though this PR changes most ts files, from all packages I think.
- I've digged a little bit in dorny/paths-filter sources, found out the file matching string is passed to `picomatch` for actual filtering.
- `picomatch` is very simple (but fast), and does not support any advanced globbing techniques. I've done some tests locally, and the best solution I found is to use less strict matching rules.
**A …
> ci(github): loosen up file matching when selecting tests to run

- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
* reverts changes of commit 3371772c582389f6ee0c6fb66af875dd93cc94c6,
which seems to be breaking the Fabric Test Ledger
Results of further investigation into the root cause done by Peter:
1. The URLs we specify have the `grpcs://` protocol specified meaning that
TLS is used for securing the connection.
2. Certificates that are generated by the Fabric-provided boostrap scripts
when setting up crypto materials for the ledger are generated with `localhost`
as the hostname instead of the IP address of localhost.
3. The C++ gRPC implementation does not support mixing IP addresses and
hostnames when it comes to connections that are using TLS, e.g. if the
certificate we are using was made out for `localhost` then it won't work
for `127.0.0.1` even though technically from our perspective they …
> test(test-tooling): fix FabricTestLedger INVALID_ENDORSER_TRANSACTION

- BUILD.md
- fix node version in BUILD.md what caused type error in corepack
and prevented yarn from installing packages correctly.
Error message when using node 16: Type Error: URL.canParse is not a function
Signed-off-by: Tomasz Awramski <tomasz.awramski@fujitsu.com>
> docs(build): change NodeJS version in BUILD.md to v18.18.2

- examples/cactus-example-carbon-accounting-backend/package.json
- examples/cactus-example-carbon-accounting-business-logic-plugin/package.json
- examples/cactus-example-cbdc-bridging-backend/package.json
- examples/cactus-example-supply-chain-backend/package.json
- examples/cactus-example-supply-chain-business-logic-plugin/package.json
- extensions/cactus-plugin-htlc-coordinator-besu/package.json
- packages/cactus-plugin-htlc-eth-besu-erc20/package.json
- packages/cactus-plugin-htlc-eth-besu/package.json
- packages/cactus-plugin-keychain-aws-sm/package.json
- packages/cactus-plugin-keychain-azure-kv/package.json
- packages/cactus-plugin-keychain-google-sm/package.json
- packages/cactus-plugin-keychain-vault/package.json
- packages/cactus-plugin-ledger-connector-besu/package.json
- packages/cactus-plugin-ledger-connector-fabric/package.json
- packages/cactus-plugin-ledger-connector-iroha/package.json
- packages/cactus-plugin-ledger-connector-polkadot/package.json
- packages/cactus-plugin-ledger-connector-xdai/package.json
- yarn.lock
The command used to perform this upgrade was:
`yarn up openapi-types --exact`
Simple quality of life improvement. The openapi-types package is used
mainly as a helper for dealing with Open API spec related logic in a
cleaner manner. It doesn't really affect the runtime behavior of the
code that much.
With all that said, it is worthwhile to consolidate the versions we use
because strange/hard to debug compiler bugs can (and do) emerge from
time to time just on account of us juggling multiple different versions
of certain libraries.
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasin …
> build(deps): upgrade pkg openapi-types to v12.1.3 project-wide

- examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
This is a purely stylistic change that makes the code read much better
and also reduces the chance of future bugs that would get introduced due
to block scoping side effects that people not experienced with the
language could make.
> style(docs/examples/supply-chain): move block scoped code to functions

- examples/cactus-example-cbdc-bridging-backend/src/test/typescript/cucumber/steps/besu-gateway.steps.ts
- examples/cactus-example-cbdc-bridging-backend/src/test/typescript/cucumber/steps/bridge-back.steps.ts
- examples/cactus-example-cbdc-bridging-backend/src/test/typescript/cucumber/steps/bridge-out.steps.ts
- examples/cactus-example-cbdc-bridging-backend/src/test/typescript/cucumber/steps/common.ts
- examples/cactus-example-cbdc-bridging-backend/src/test/typescript/cucumber/steps/fabric-gateway.steps.ts
Just ran `yarn lint` on `main` and it applied these formatting changes
so I'm applying the changes to make sure others don't have to deal with
the auto-formatter littering their commits with automated changes like
these.
The bigger story here is that this somehow passed the CI which makes me
suspect that we forgot to add a check to the lint action that would
verify that post-lint there are no files changed compared to the git
revision that is being linted, so figuring this out is a to-do still and
should go into it's own pull request later on. …
> style(docs/examples/cbdc): applied auto-formatting to CBDC example code

- packages/cactus-test-tooling/package.json
- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/main/typescript/http-echo/http-echo-container.ts
- packages/cactus-test-tooling/src/main/typescript/postgres/postgres-test-container.ts
- packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
- yarn.lock
1. The container management library that we use in the test infrastructure
(called dockerode) is expecting streams that are defined in the global
namespace of the `@types/node` library, e.g. the standard library of NodeJS
itself.
2. Previously we were using the "streams" package to provide type information
to the streams that we were passing around to dockerode and it was working
fine, but after some changes that seem unrelated this has broken the
compilation process.
3. The mentioned changes are not yet on the main branch, but we expect
them to be there soon and so this change is laying the groundwork for that
by pre-emptively fixing the broken build's root cause which is that the
test-tooling package does not declare it's typings related dependencies
correctly: It implicitly uses the …
> refactor(test-tooling): fix types of streams: use NodeJS.ReadableStream

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/common/find-and-replace-fabric-logging-spec.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/common/ssh-exec.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-source/deploy-contract-go-source-impl-fabric-v2-5-6.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
The deployContractGoSourceV1() method now assumes that the underlying
test ledger is Fabric 2.5 (current LTS).
This will allow us to upgrade the contracts that are being used by the
Supply chain app to Fabric 2.x from Fabric 1.x which will then implicitly
fix a large number of other issues at the same time.
This change is part of laying the foundation for that follow-up work.
Primary changes:
-----------------
1. Added a new, standalone utility function to deploy go source contracts
with the name of `deployContractGoSourceImplFabricV256()`.
2. The code of this function was derived from the original Fabric v1
compatible deployContractGoSourceV1 method of the Fabric connector.
3. 2 organizations are supported for deployment via the endpoint.
4. The endpoint is only used by the supply chain …
> refactor(connector-fabric): deployContractGoSourceV1 uses Fabric v2.5.6

- tools/bump-openapi-spec-dep-versions.ts
- tools/create-production-only-archive.ts
- tools/generate-sbom.ts
- tools/get-latest-sem-ver-git-tag.ts
- tools/npm-list.ts
- tools/sync-npm-deps-to-tsc-projects.ts
1. The `-cjs` version of the package was put into place because in the
production packages we needed it to be able to import the dependency
despite us not using ESM just yet.
2. We did a blanket search and replace at the time which seemed like a
good idea but turns out it wasn't because there are some tooling scripts
(the ones in this diff) that are already using ESM and for those the
-cjs flavored package started breaking the code.
3. So this change is just a partial/selective/surgical revert of the
earlier project-wide migratin from run-time-error to run-time-error-cjs. …
> tools: fix scripts - use run-time-error instead of run-time-error-cjs

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/delegate-signing-methods.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source-private-data.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-lock-asset.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/fabric-watch-blocks-delegated-sign-v1-endpoint.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/fabric-watch-blocks-v1-endpoint.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/get-block.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/obtain-profiles.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-identities.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-ws-ids.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/openapi/openapi-validation.test.ts
1. This fixes many flakes that we were suffering from before with the
older versions of the AIO image.
2. There could still be other flakes lurking around, but their numbers
should definitely be going down with this change due to the increased
stability of the new AIO image.
> test(connector-fabric): move integration tests to use Fabric v2.5.6 AIO

- examples/cactus-example-supply-chain-frontend/webpack.config.overrides.js
- packages/cactus-cmd-api-server/package.json
- packages/cactus-core-api/package.json
- packages/cactus-plugin-ledger-connector-iroha/package.json
- weaver/common/protos-js/package.json
- weaver/core/drivers/fabric-driver/package-local.json
- weaver/core/drivers/fabric-driver/package.json
- weaver/core/identity-management/iin-agent/package-local.json
- weaver/core/identity-management/iin-agent/package.json
- weaver/samples/fabric/fabric-cli/package-local.json
- weaver/samples/fabric/fabric-cli/package.json
- weaver/sdks/fabric/interoperation-node-sdk/package-local.json
- weaver/sdks/fabric/interoperation-node-sdk/package.json
- yarn.lock
1. This is a pre-requisite for a bigger change that is adding gRPC
endpoint support to the plugins.
2. We've had gRPC support in the API server for a long time, but the
plugins are not yet able to register their own gRPC services as of now.
3. The reason we need the newer version is because some types are not
exported by the older version that we'll be using to implement the
gRPC support for plugins.
> build(deps): upgrade @grpc/grpc-js to v1.10.3

- packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/Dockerfile
- packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/rust/gen/examples/server/server.rs
1. The solution here was to migrate the image from Debian to Ubuntu
because it seems to not have the same vulnerabilities as the lastest
stable Debian image does, so the change itself is to move to Ubuntu 24.04
LTS.
2. Also upgraded the Rust toolchain to the current latest which mandated
a couple of small code changes that are also added in this commit.
The original security report from Trivy that we've discoverd on the CI:
┌─────────────┬───────────────┬──────────┬───────────────────┐
│   Library   │ Vulnerability │ Severity │ Installed Version │
├─────────────┼───────────────┼──────────┼───────────────────┤
│ libgnutls30 │ CVE-2024-0553 │ HIGH     │ 3.6.7-4+deb10u11  │
│             │               │          │                   │ …
> fix(plugin-keychain-vault): fix CVE-2024-0553 in vault server image

- packages/cactus-core-api/src/main/typescript/plugin/grpc-service/i-plugin-grpc-service.ts
- packages/cactus-core-api/src/main/typescript/public-api.ts
1. This will be used by the upcoming functionality of the API server that
allows all plugins to register their own gRPC services as part of the API
server's own gRPC service.
2. The above mechanism will largely be the same conceptually as the one
we have for HTTP and SocketIO endpoints already.
3. It is optional for plugins to implement gRPC services and therefore
the interface is a standalone one instead of being baked into the more
generic IPluginWebService interface for example.
> feat(core-api): add IPluginGrpcService type & user-defined type guard

- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
1. Prior to this change the polling function that waits for transactions
to be confirmed was running in  while loop without any delay, meaning that
the code that fetches the latest block is executing thousands of times
each second (or however fast the CPU in the machine/network connection are).
2. Now there is a second delay between each execution of the loop so that
we are not hammering the node of the ledger we are connected to.
3. This also has the added benefit of the test cases using this method
using much less CPU power.
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-an …
> refactor(connector-besu): tx poll per second not at full CPU speed

- examples/cactus-example-cbdc-bridging-backend/src/main/typescript/infrastructure/cbdc-bridging-app-dummy-infrastructure.ts
1. The older versions of the AIO image are rusty (flaky to boot) and so
to increase the stability of the example application I considered it
prudent to upgrade to the latest and greatest (non-breaking) all-in-one
image that we have.
2. There might be other branches out there in development where the same
change is already pending, if this is the case then apologies, but I just
had to get this done right away because it had a direct dependency from
another pull request where I was upgrading web3 packages and I had to
have the example application up and running in order to verify that other
pull requests not messing anything up, so here we are.
For …
> docs(examples/cbdc): migrate backend to Fabric v2.5.6 all-in-one image

- .github/workflows/actionlint.yaml
1. Previously we just winged it with a bash script downloading another
bash script to unzip the actionlint binaries.
2. From now on we'll use the GitHub action from the marketplace which
has a lot of configuration options exposed in a convenient way such as
what type of warnings to ignore, what version of actionlint to install,
etc.
> ci(github): refactor ActionLint job to use the official installer

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/main/typescript/grpc/grpc-credentials-factory.ts
- packages/cactus-cmd-api-server/src/main/typescript/grpc/grpc-server-factory.ts
- packages/cactus-cmd-api-server/src/main/typescript/public-api.ts
1. The API server supports gRPC endpoints, but plugins are not yet able
to register their own gRPC services to be exposed the same way that was
already possible for HTTP endpoints to be registered dynamically. This
was due to an oversight when the original contribution was made by Peter
(who was the person making the oversight - good job Peter)
2. The functionality works largely the same as it does for the HTTP
endpoints but it does so for gRPC services (which is the equivalent of
endpoints in gRPC terminology, so service === endpoint in this context.)
3. There are new methods added to the public API surface of the API server
package which can be used to construct gRPC credential and server objects
using the instance of the library that is used by the API server.
This is necessary because …
> feat(cmd-api-server): add gRPC plugin auto-registration support

- examples/cactus-example-carbon-accounting-backend/package.json
- examples/carbon-accounting/Dockerfile
- examples/carbon-accounting/supervisord.conf
- yarn.lock
---
examples(carbon-accounting):fix CVE-2022-25881 CVE-2021-39167
```
1. Modified the Dockerfile to use the updated versions 
of the packages being used
2. Modified the supervisord.conf to use the correct path
because it has changed after updating the versions
```
Fixes #2062
> chore(carbon-accounting): fix CVE-2022-25881 CVE-2021-39167

- packages/cactus-cmd-api-server/package.json
- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
- yarn.lock
1. This is enabling plugins to expose their operations via ConnectRPC
services which is very similar to gRPC but it comes with a few extra
bells and whistles that can come in very handy.
2. There is an upcoming pull request that makes it so that the keychain
memory plugin implements and registers its services via this newly added
hook of the API server. The importance of this is that test coverage for
the code in this commit resides on another branch, meaning that even though
there are no new test cases on this branch, the feature has been extensively
tested and there is test-automation in place to continue verifying it
as well.
3. The main difference between the hook methods are that for CRPC the
API server expects an array of service definition+implementation pairs
instead of just a …
> feat(cmd-api-server): add ConnectRPC auto-registration for plugins

- packages/cactus-core/package.json
- packages/cactus-core/src/main/typescript/public-api.ts
- packages/cactus-core/src/main/typescript/web-services/configure-express-app-base.ts
- packages/cactus-core/src/main/typescript/web-services/stringify-big-int-replacer.ts
- packages/cactus-core/src/test/typescript/unit/web-services/configure-express-app-base.test.ts
- yarn.lock
1. The idea here is to re-use the common basic tasks of configuring an
express instance similar to how the API server does it but without having
the chicken-egg problem of circular dependencies between the API server
and the plugins.
2. More detailed discussion can be seen in this other pull request in
the comments: https://github.com/hyperledger/cacti/pull/3169
> feat(core): add configureExpressAppBase() utility function

- packages/cactus-plugin-ledger-connector-quorum/Dockerfile
---
chore(connector-quorum): fix CVEs: CVE-2023-36665, CVE-2022-21190
```
1. Modified the Dockerfile to use the updated versions of the packages being used
```
Fixes #2865
> chore(connector-quorum): fix CVEs: CVE-2023-36665, CVE-2022-21190

- .github/workflows/test_weaver-pre-release.yaml
Fixes the script injection attack mentioned here: https://hackerone.com/reports/2471956
Check sample attack run here: https://github.com/sandeepnRES/cacti/actions/runs/8830394750/job/24243428274?pr=23
from PR on my fork: https://github.com/sandeepnRES/cacti/pull/23
Source for the solution: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack
> ci: mitigate script injection attack in test_weaver-pre-release.yaml

- packages/cactus-plugin-ledger-connector-polkadot/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-polkadot/src/main/typescript/web-services/deploy-contract-ink-endpoint.ts
- packages/cactus-plugin-ledger-connector-polkadot/src/main/typescript/web-services/get-prometheus-exporter-metrics-endpoint.ts
- packages/cactus-plugin-ledger-connector-polkadot/src/main/typescript/web-services/get-raw-transaction-endpoint.ts
- packages/cactus-plugin-ledger-connector-polkadot/src/main/typescript/web-services/get-transaction-info-endpoint.ts
- packages/cactus-plugin-ledger-connector-polkadot/src/main/typescript/web-services/invoke-contract-endpoint.ts
- packages/cactus-plugin-ledger-connector-polkadot/src/main/typescript/web-services/run-transaction-endpoint.ts
- packages/cactus-plugin-ledger-connector-polkadot/src/main/typescript/web-services/sign-raw-transaction-endpoint.ts
---
refactor: rename OpenAPI extension in plugin-ledger-connector-polkadot 
```
1. Updated the files in packages/cactus-plugin-ledger-
connector-polkadot to use x-hyperledger-cacti
```
Fixes #3198 
> refactor: rename OpenAPI extension in plugin-ledger-connector-polkadot

- packages/cactus-common/src/main/typescript/js-object-signer.ts
- packages/cactus-plugin-bungee-hermes/README.md
- packages/cactus-plugin-bungee-hermes/src/main/json/openapi.json
- packages/cactus-plugin-bungee-hermes/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/plugin-bungee-hermes.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/utils.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/view-creation/privacy-policies.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/view-creation/snapshot.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/view-creation/state.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/view-creation/view.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/view-merging/extended-state.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/view-merging/integrated-view.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/view-merging/merge-policies.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/web-services/merge-views-endpoint.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/web-services/process-view-endpoint.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/bungee-merge-views.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/bungee-process-views.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/fabric-test-pruning.test.ts
BUNGEE-Hermes is supposed to be able to process and merge views, following 'privacy-policies' (which are basicaly functions that alter the data included in a View/IntegratedView). 
The algorithm of Merging views is detailed  in the paper [BUNGEE](https://dl.acm.org/doi/pdf/10.1145/3643689).
Summary of Changes:
- Added new types for view merging
- Created some merge and process policies for demonstration
- new endpoints and plugin logic to merge and process views
- two new tests to test new functionality
- utility function to fully deserialize a view
- slightly changed View type, to keep record of its old versions metadata
- updated README.md
> feat(bungee-hermes): process & merge views

- jest.config.js
Found the solution and a long discussion about it here:
https://github.com/kulshekhar/ts-jest/issues/1057
TLDR: The Jest resolver needs a little extra information/tweak to the
config so that it can correctly handle the .js imports.
Specifically this comment provided the solution which I made here:
https://github.com/kulshekhar/ts-jest/issues/1057#issuecomment-1482644543
Fixes #3254
> build(plugin-keychain-memory): fix local imports broken due to .js exts

- package.json
On a laptop with 16 GB RAM the default JS heap size is not enough anymore
to do a full typescript build of the project from scratch.
The size of the heap for NodeJS processes gets determined at runtime by
an algorithm that (most likely) depends on the total RAM in your computer:
https://stackoverflow.com/a/75555120
For laptops with 16 GB RAM or less, the heap ends up being calculated to
an amount that is too low at this size of the project so we have to give
it a little nudge by specifying the parameter for heap size explicitly to
be 3 GB instead of the default. …
> build(package.json): set JS heap to 3 GB for typescript compilation

- packages/cactus-plugin-keychain-memory/package.json
- packages/cactus-plugin-keychain-memory/src/main/typescript/plugin-keychain-memory.ts
- packages/cactus-plugin-keychain-memory/src/test/typescript/unit/plugin-keychain-memory-observability.test.ts
- yarn.lock
1. This is an example of how to add observability to a plugin such as
if you had to somehow expose the stream of transaction execution requests
flowing through a connector plugin but did not feel like setting up Kafka
or RabbitMQ just for this and instead opted to do it with an in-process,
purely NodeJS/Javascript based solution.
2. The downside of this is of course that this doesn't work well in a
distributed computing environment just by itself, since if you were to
host a fleet of servers running the same connector plugin with horizontal
scaling, then this wouldn't be able to observe all the invocations across
the server fleet, but it would still make it easier to implement a functionality
like that.
3. The main purpose of this pull request is educational. The keychain memory
plugin is …
> feat(plugin-keychain-memory): add observability via RxJS ReplaySubjects

- .github/workflows/ci.yaml
---
chore(github): shorten ci.yaml workflow and job names
```
ce - cactus-example
cp - cactus-plugin
cpk - cactus-plugin-keychain
cpl - cactus-plugin-ledger
cplc - cactus-plugin-ledger-connector
plc - plugin-ledger-connector
cpp - cactus-plugin-persistence
ct - cactus-test
ctp - cactus-test-plugin
```
Fixes: hyperledger#2624
> chore(github): shorten ci.yaml workflow and job names

- .cspell.json
- extensions/cactus-plugin-htlc-coordinator-besu/src/test/typescript/integration/plugin-htlc-coordinator/counterparty-htlc-endpoint.test.ts
1. The test seem to have been broken from the moment of the introduction
of the HSTS header assertions.
2. The HSTS headers should be managed on the API server level instead of
individual endpoints.
3. I'll create a follow-up issue for working on this in a more generic
way that gets HSTS headers in place across the board and also in a way
that these are configurable for scenarios when the users don't want them.
> test(plugin-htlc-coordinator-besu): fix HSTS header assert lowercase

- packages/cactus-cmd-api-server/Dockerfile
[fix(cmd-api-server): address](https://github.com/hyperledger/cacti/pull/2899/commits/23d0bc53ffbe7caa216362604196d9b4b08d871a) https://github.com/advisories/GHSA-rc47-6667-2j5j 
Updated the Dockerfile & https-cache-semantics inside the cmd-api-server package
Fixes: https://github.com/hyperledger/cacti/issues/2862
Signed-off-by: zondervancalvez <zondervan.v.calvez@accenture.com>
> fix(cmd-api-server): address CVE-2022-25881

- .github/workflows/ci.yaml
The problem seems to have been that the yarn cache restore operation
was somehow reverted to the old way of doing it which at this point
have been deprecated and broken by upgrades performed by GitHub in the
meantime.
I've updated the job definition yaml to declare the cache restore operation
the same way all the other jobs are doing it so that it doesn't crash while
attempting to restore the yarn dependency cache prior to a build+test job.
The logs of the failing job looked like this which provided the clue to
what the issue might be:
```sh
2024-05-29T18:14:26.2450767Z Current runner version: '2.316.1'
2024-05-29T18:14:26.2479056Z ##[group]Operating System
2024-05-29T18:14:26.2479698Z Ubuntu
2024-05-29T18:14:26.2480035Z 22.04.4
2024-05-29T18:14:26.2480413Z LTS …
```
> ci(github): fix broken ci.yaml workflow job of ethereum connector

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
- packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
1. The ConnectRPC port defaults to 6000 in the API server so for test cases where multiple
instances of the API server are created and started, we need to specify the ports
explicitly in the API server config so that they don't clash with each other casusing the
test to fail.
2. The fix here was to simply bind to port 0 for all the ConnectRPC listeners which
eliminated the possibility of a clash and the test is passing once again.
3. I also snuck in a quality of life improvement for contributors: the API server will no
longer log the entire details of the fastify server that is being used for CRPC thereby
reducing the verbosity of the logs by a wide margin.
Crash logs that revealed the bug in the test case:
```sh
024-05-31T20:14:00.9554919Z [2024-05-31T20:14:00.953Z] ERROR (api-server): …
```
> test(plugin-consortium-manual): fix port binding - multiple API servers

- package.json
- yarn.lock
The changes made to this commit were performed by running `yarn up -R web3-utils`
in the root directory of the project which upgraded all the transitive web3-utils
dependency versions. Finally the root package.json's web3-utils declaration had
to be manually bumped as well.
Tags
- Runtime dependency
- Patch available
Weaknesses
- WeaknessCWE-1321
CVE ID
- CVE-2024-21505
GHSA ID
- GHSA-2g4c-8fpm-c46v
The security advisory:
https://github.com/hyperledger/cacti/security/dependabot/987
Related pull request that was an attempt by the robots to fix the issue (without success)
https://github.com/hyperledger/cacti/pull/3264
For rebasing and squashing, …
> fix(security): mitigate CVE-2024-21505

- tools/create-production-only-archive.ts
- tools/create-temporary-clone.ts
This makes the tooling code a more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
and is a pre-requisite of some follow-up changes that are about to get proposed
in a separate pull request by Peter that are specific to vendoring the openapi.json spec files.
> refactor(tools): extract createTemporaryClone() utility function

- .github/workflows/scorecard.yml
- README.md
Going forward, tracking the health of a project using the [OpenSSF Scorecard](https://github.com/ossf/scorecard) is going to be mandatory. For this purpose:
- I've configured a GitHub action to track OpenSSF criteria as per instructions in https://github.com/ossf/scorecard-action.
- I've also added a badge to the main README that reports the score inferred by the latest scan (triggered by each commit).
> ci(ossf): configured GitHub action and badge for OpenSSF scorecard

- extensions/cactus-plugin-htlc-coordinator-besu/src/main/json/openapi.tpl.json
- extensions/cactus-plugin-object-store-ipfs/src/main/json/openapi.json
- extensions/cactus-plugin-object-store-ipfs/src/main/json/openapi.tpl.json
- packages/cactus-plugin-consortium-manual/src/main/json/openapi.tpl.json
- packages/cactus-plugin-htlc-eth-besu-erc20/src/main/json/openapi.tpl.json
- packages/cactus-plugin-htlc-eth-besu/src/main/json/openapi.tpl.json
- packages/cactus-plugin-keychain-aws-sm/src/main/json/openapi.tpl.json
- packages/cactus-plugin-keychain-azure-kv/src/main/json/openapi.tpl.json
- packages/cactus-plugin-keychain-google-sm/src/main/json/openapi.tpl.json
- packages/cactus-plugin-keychain-memory-wasm/src/main/json/openapi.tpl.json
- packages/cactus-plugin-keychain-memory/src/main/json/openapi.tpl.json
- packages/cactus-plugin-keychain-vault/src/main/json/openapi.tpl.json
On a high level this is a find & replace operation where the occurrences of the
first bullet point were replaced with the second bullet point:
* `"$ref": "https://raw.githubusercontent.com/hyperledger/cactus/v2.0.0-alpha.2`
* `"$ref": "../../../../..`
The firs bullet point above is called a URL reference while the second one is
called a REMOTE references (remote as in a different spec file on the file-system).
1. With this change, we unlock the release process being able to issue code that
is working on the latest OpenAPI specifications that we are cross-referencing
from one package to another.
2. Previously you had to manually update the references in about a hundred
and fifty locations to make sure that the versions are bumped but after this
change this happens automatically as the …
> build: unpin OpenAPI specs from v2.0.0-alpha.2 URL refs, use REMOTE

- .github/workflows/dev-container-vscode-publish.yaml
1. We don't have a Dockerfile anymore to define the image of the dev container
instead the build's input is the `devcontainer.json` file which can be built
using the `@devcontainers/cli` npm package instead of the usual `docker build`
command on the terminal.
2. The ci.yaml job building the image was already doing the build this way but
we must've forgotten to update the publish job as well.
> ci(github): fix VSCode dev container publish job - use official builder

- RELEASE_MANAGEMENT.md
- package.json
- tools/bump-openapi-spec-dep-versions.ts
1. After this change the steps within the release management documentation should
work without issues.
2. Currently the process is (was) broken due to our reliance on URL references
within the OpenAPI specifications which created a chicken-egg problem with the
release tag issuance and the building of the source code to be released.
This change depends on the other pull requests that are refactoring the cross-package
OpenAPI specification references:
Depends on #3288
Depends on #3315
> build(release-management): fix checklist and OpenAPI spec version bumps

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-plugin-keychain-aws-sm/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-lock-asset.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-ws-ids.test.ts
There's still about a hundred test cases to be migrated so I'm combining a
few at a time in the pull requests to reduce the CI resource consumption.
They are fairly boilerplate changes that usually follow the exact same
pattern so it's fairly easy to review with that in mind (hopefully) despite
the slightly larger size.
> test: migrate run-tx-with-ws-ds, keychain-aws-sm tests from Tap to Jest

- RELEASE_MANAGEMENT.md
The detailed explanation is here:
Do not enable auto-merging on GitHub for the pull request doing the release.
The problem with auto-merging here is that it would modify the release commit's SHA as the
rebase would happen on GitHub's servers where your git signing identity is not available to use
given that GitHub does (should) not have access to your private key for signing.
The way the preserve your commit signature as valid the commit SHA must remain the same and the
way to achieve this is to perform the pull request merging with fast forward. The merging
ensures that there is no commit SHA change and the `--ff-only` option ensures that there is no
merge commit to throw a wrench in the process.
**Pull Request …
> docs(RELEASE_MANAGEMENT): explain auto-merge for release PRs is a no-no

- .github/workflows/all-nodejs-packages-publish.yaml
1. Longer term we'll just fix the scripts that are crashing, but right now
as a short term solution I disabled the script execution.
2. It might even be more secure for us to use this ignore scripts flag
permanently because some of the attack vectors are in those scripts which
new versions of the dependencies can execute arbitrary code.
> ci(github): add --ignore-scripts to lerna publish - some are failing

- packages/cacti-plugin-weaver-driver-fabric/package.json
- packages/cacti-plugin-weaver-driver-fabric/readme.md
- packages/cacti-plugin-weaver-driver-fabric/src/main/typescript
- weaver/core/drivers/fabric-driver/server/events.ts
- weaver/core/drivers/fabric-driver/server/fabric-code.ts
- weaver/core/drivers/fabric-driver/server/listener.ts
- weaver/core/drivers/fabric-driver/server/server.ts
- weaver/core/drivers/fabric-driver/server/walletSetup.ts
- yarn.lock
* This commit is a step towards of our roadmap of creating an integrated API, where fabric driver from weaver will be merged with ledger connector from cactus. 
* Currently this is only creating a package for the fabric driver with a symbolic link, trying to experiment how to move the weaver packages as cacti packages.
* Following this we want to convert all the weaver modules to cacti packages.
* And then deeper integration will be the future steps.
> feat(fabric-driver): added weaver fabric driver as cacti package

- weaver/common/protos-js/Makefile
- weaver/sdks/besu/node/makefile
- weaver/sdks/fabric/interoperation-node-sdk/makefile
Fix the issue identified in previous release, here is the error log screenshot, where it was ignoring local `.npmrc` required for publishing, and then later on `npm publish` is unable to authenticate:
> ci: fix weaver nodejs publish ignore local .npmrc

- packages/cactus-test-tooling/src/main/typescript/corda/corda-test-ledger.ts
- packages/cactus-test-tooling/src/main/typescript/corda/sample-cordapp-enum.ts
1. This way we can have examples and test cases developed that use either
the negotiation or the obligation cordapps. Earlier we could only use
the obligation cordapp as it was the hardcoded directory path for contract
deployments.
2. Not an actual feature just an extension to the testing infrastructure
that we have and we need the additional possibilities here because of the
new Harmonia Labs examples coming up.
> test(test-tooling: add negotiation-cordapp support from kotlin-samples

- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/JsonJvmObjectDeserializer.kt
- packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/test/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/JsonJvmObjectDeserializerTest.kt
1. This allows the API clients to specify a class name from which the backend
will retrieve the JVM Class<?> object.
2. It is very simple under the hood it just uses `Class.forName(x)`
3. It is needed to be able to do this because when passing in flow parameters
sometimes the arguments are Class<?> objects and so this was a feature gap.
> feat(connector-corda): add JSON classname->JVM class object deserialize

- .cspell.json
- packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.tpl.json
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/index.web.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-boolean.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-cacti-public-key-impl.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-corda-amount.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-corda-identity-party.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-corda-unique-identifier.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-corda-x500-name.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-currency.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-long.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-string.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server-v4.7.test.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server-v4.8.test.ts
1. These functions are used so more easily construct the JSON representation
of JVM objects (references and primitive values) that we need to define when
interacting with the Corda JVM connector (which is used for Corda v4 ledgers)
2. This is not a comprehensive set but more like a trailblazing initial
implementation to showcase how to create and use these factory functions.
> feat(connector-corda): add initial set of JvmObject factory functions

- package.json
- tools/custom-checks/check-missing-node-deps.ts
- yarn.lock
1. The depcheck tool we use have not correctly discovered some of the
missing dependencies that we have because it only verifies that the
imported dependency is present SOMEwhere in the package.json file, not that
it is specifically present in the production dependencies section which
leads to crashes and broken packages due to the API server not installing
dev dependencies when instantiating a plugin and therefore missing a few
of the dependencies that are otherwise very much needed at runtime in
production.
2. The solution to the problem was to implement our own typescript parsing
with babel and then double check the work of depcheck to make sure that
the dependencies that it marks as "no issues" are actually OK and have no
issues.
3. The hardest edge case was type imports e.g. `import …
> ci(custom-checks): fix depcheck not detecting missing dependencies

- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/deploy-cordapp-jars-to-nodes-v4.8-express.test.ts
1. Upgrading the images that were being used made it so that now the test
is no longer flaky/broken (or at least that's what a series of executions
of it made it looked like on my local machine)
2. Based on the above it might be worthwhile to put this test back into the
ones that are running (previously it was marked to be skipped).
3. We should keep an eye on it to make sure it's not flaky on the CI either
(which has resources much more constrained than my local development machine)
> test(connector-corda): fix deploy-cordapp-jars-to-nodes-v4.8-express

- examples/cactus-example-cbdc-bridging-backend/src/fabric-contracts/asset-reference/typescript/package.json
- examples/cactus-example-cbdc-bridging-frontend/package.json
- examples/cactus-example-electricity-trade/tools/transferNumericAsset/package.json
- examples/test-run-transaction/package.json
- examples/test-run-transaction/supply-chain-app-stub/package.json
- package.json
- packages/cacti-ledger-browser/package.json
- packages/cactus-plugin-bungee-hermes/src/test/typescript/fabric-contracts/lock-asset/chaincode-typescript/package.json
- packages/cactus-plugin-bungee-hermes/src/test/typescript/fabric-contracts/simple-asset/chaincode-typescript/package.json
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/basic-asset-transfer/chaincode-typescript/package.json
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/lock-asset/chaincode-typescript/package.json
- packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/unit-test/package.json
- packages/cactus-plugin-satp-hermes/package.json
- packages/cactus-plugin-satp-hermes/src/test/typescript/fabric-contracts/lock-asset/chaincode-typescript/package.json
- weaver/core/drivers/fabric-driver/package-local.json
- weaver/core/drivers/fabric-driver/package.json
- weaver/core/identity-management/iin-agent/package-local.json
- weaver/core/identity-management/iin-agent/package.json
- weaver/samples/besu/besu-cli/package-local.json
- weaver/samples/besu/besu-cli/package.json
- weaver/samples/besu/simpleasset/package.json
- weaver/samples/fabric/fabric-cli/package-local.json
- weaver/samples/fabric/fabric-cli/package.json
- weaver/sdks/besu/node/package-local.json
- weaver/sdks/besu/node/package.json
- weaver/sdks/fabric/interoperation-node-sdk/package-local.json
- weaver/sdks/fabric/interoperation-node-sdk/package.json
- yarn.lock
1. Brings in size and performance improvements.
2. Also adds support for some new features such as Ecmascript setters
https://www.infoworld.com/article/3715246/typescript-adds-support-for-ecmascripts-set-methods.html
Fixes #3326
> build(typescript): upgrade compiler to v5.5.x

- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/index.web.ts
1. We were only exporting the API client and the related data model type
definitions for NodeJS builds but not for the web.
2. This made it so that you couldn't import/use the Besu API client from
a front-end application such as Angular or React.
> feat(connector-besu): expose API client and OpenAPI code for web builds

- .github/workflows/deploy_docs.yml
- .gitignore
- docs/docs/index.md
- docs/docs/references/openapi/index.md
- docs/mkdocs.yml
- docs/requirements.txt
- docs/scripts/publish_openapi.py
Create project documentation reference page of all open api specs produced by monorepo projects.
chore(docs): generate browsable openapi specs 
1. Updated deploy_docs workflow to generate markdown for openapi
specs files present across packages
Secondary Changes required to incorporate 1)
2. Added docs/scripts/publish_openapi.py to generate markdown 
3. Added swagger-ui-tag plugin to mkdocs
4. Updated docs/requirements.txt for the above plugin to be
downloaded.
> chore(docs): generate browsable openapi specs

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
1. The API server was mutating global shared state in it's own constructor
which was causing problems with other components (pretty much all of them)
2. I deleted the line that copies the API server's own log level to the
LoggerProvider so that the API server's log level can be it's own.
3. The way this bug came about is that in the supply chain app example
in the back-end the API server had to be muted (log level WARN) in order
for it to stop printing misleading logs due to us binding to the wildcard
host it would claim in its own logs that the WWW GUI is accessible on the
wildcard host in a web browser, but this was wrong and caused many people
a lot of confusion unfortunately.
4. The fix for the supply chain app is to set the API server's log level to
WARN and have the supply chain app …
> fix(cmd-api-server): stop changing LoggerProvider log level

- packages/cactus-plugin-ledger-connector-besu/Dockerfile
- packages/cactus-plugin-ledger-connector-besu/README.md
---
build(connector-besu): fix CVE-2022-21190 CVE-2023-36665 CVE-2022-2421
```
1. Updated the version of the base image that is used in the Dockerfile
2. Updated the Dockerfile to use the yarn version 3
3. Updated the README to the new command to run the container
```
Fixes #2745
> build(connector-besu): fix CVE-2022-21190 CVE-2023-36665 CVE-2022-2421

- examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app-cli.ts
- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
1. Now you can run the supply chain app example locally and then hit CTRL+C
on the terminal and it will gracefully shut down all the containers hosting
the infrastructure and only after that the NodeJS process itself will exit.
2. Previously we had a bug where it wouldn't wait for the containers to wind
down and it left them running which was causing problems when people didn't
notice this behavior and their machines would get into this broken state where
the previous execution's containers were hanging around and one of them blocking
ports too. …
> docs(examples/supply-chain-app): fix resource cleanup of shutdown logic

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
1. The library we use for having async functions handle resource deallocation
was not being used correctly by the API server.
2. The library only supports callback style asynchronous code and the API
server assumed that it could return a promise from the shutdown hooks which
lead to the problem that our shutdown hooks were not being awaited for.
> fix(cmd-api-server): shutdown hook was not waiting for promises

- packages/cactus-plugin-persistence-ethereum/src/main/sql/schema.sql
1. The problem was that the database schema was defined in a way that was
destroying timestamp information during insertion of records.
2. Updating the schema to hold the timestamp information made the test pass.
More information about why it's recommended to store datetime data with
the TIMESTAMPTZ column type is explained by the author of the node-postgres
library which is an important part of the problem (it assumes local time
for columns that do not store the timestamp time zone).
https://node-postgres.com/features/types#date--timestamp--timestamptz
Fixes #3373 …
> fix(plugin-persistence-ethereum): make created_at TIMESTAMPTZ in schema

- .github/workflows/all-nodejs-packages-publish.yaml
- .github/workflows/besu-all-in-one-publish.yaml
- .github/workflows/cmd-api-server-publish.yaml
- .github/workflows/connector-besu-publish.yaml
- .github/workflows/connector-corda-server-publish.yaml
- .github/workflows/connector-fabric-publish.yaml
- .github/workflows/corda-4-6-all-in-one-obligation-publish.yaml
- .github/workflows/corda-4-7-all-in-one-obligation-publish.yaml
- .github/workflows/corda-4-8-all-in-one-obligation-publish.yaml
- .github/workflows/dev-container-vscode-publish.yaml
- .github/workflows/example-carbon-accounting-publish.yaml
- .github/workflows/example-supply-chain-app-publish.yaml
- .github/workflows/fabric2-all-in-one-publish.yaml
- .github/workflows/geth-all-in-one-publish.yaml
- .github/workflows/ghpkg-all-kotlin-api-clients-publish.yaml
- .github/workflows/iroha2-all-in-one-publish.yaml
- .github/workflows/keychain-vault-server-publish.yaml
- .github/workflows/quorum-all-in-one-publish.yaml
- .github/workflows/quorum-multi-party-all-in-one-publish.yaml
- .github/workflows/sawtooth-all-in-one-publish.yaml
---
perf(ci): only publish artifacts on git version tags of main 
```
Primary Changes 
1. Remove auto publishing of container images in all **publish.yaml upon push and maintain automation runs during pull requests
```
Fixes #2360
> perf(ci): only publish artifacts on git version tags of main 

- weaver/sdks/besu/node/index.js
- weaver/sdks/besu/node/package.json
- weaver/sdks/fabric/interoperation-node-sdk/index.js
- weaver/sdks/fabric/interoperation-node-sdk/package.json
---
fix(ci): DeprecationWarning in yarn_custom_checks
```
1. Updated the main field to use index.js to fix the Deprecation Warning
```
Fixes #2956
> fix(ci): DeprecationWarning in yarn_custom_checks

- FAQ.md
docs(faq): added ipv6 default fix 
1. Added a new FAQ related to configure script stuck at discovering npm registry due to IPv6 defaults
> docs(faq): added ipv6 default fix

- tools/sync-npm-deps-to-tsc-projects.ts
---
build(sync-ts-config): fix no such file or directory protos-js/tsconfig.json
```
1. Fix issue with the object key
2. Temporarily added ignore paths for the missing tsconfig.json so the script will run successfully
```
Fixes: #3069 
Related to: #3366
> build(sync-ts-config): fix no such file or directory protos-js/tsconfig.json

- packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
1. Previously we specified the publish all ports flag of the Docker Engine
incorrectly and this lead to the ports not actually being published on
randomized ports.
2. This broke the supply chain app example when we tried to migrate it to
use 2 separate besu test ledger instances in tandem because they were
conflicting on the ports due to the lack of randomization.
> test(test-tooling): fix BesuTestLedger start cfg: publish all ports

- .taprc
- docs-cactus/source/support/fabric.md
- docs/docs/cactus/packages/cactus-plugin-ledger-connector-fabric.md
- docs/docs/cactus/support/fabric.md
- jest.config.js
- packages/cactus-plugin-ledger-connector-fabric/README.md
1. We've removed the Fabric v1.4.x test cases a while back but I forgot
to delete them from the .taprc and jest.config.js files for example.
2. Also in a couple of places the documentation was referring to the
test cases as well so that had to be updated also.
> docs(connector-fabric): remove references to old Fabric v1.4.x tests

- packages/cactus-plugin-ledger-connector-corda/README.md
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/jvm/serde/factory/create-jvm-int.ts
- packages/cactus-plugin-ledger-connector-corda/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/flow-database-access-v4.8.test.ts
- packages/cactus-test-tooling/src/main/typescript/corda-connector/corda-connector-container.ts
- packages/cactus-test-tooling/src/main/typescript/corda/corda-test-ledger.ts
Primary Change:
1. The test case was broken due to a number of different issues related
to the AIO image build an also the connector image build, but on top of
those problems it also had misconfiguration issues where the port number
wasn't set to what it should be for the RPC connection that the connector
container uses to establish communications with the AIO ledger image.
Secondary Change(s):
---------------------
1. Fixed 2 bugs in the test tooling package where the port configuration
was not randomizing the exposed ports of the corda connector container and
the corda test ledger leading to accessibility issues.
2. Also introduced a createJvmInt(...) utility function on the corda connector
package which allows the flowdb test case to construct the flow invocation …
> test(connector-corda): fix flow-database-access-v4-8 test case 

- .github/workflows/ci.yaml
We have the disk clean-up in the CI off by default because it takes a few
minutes to perform and most jobs don't need it, but for Corda it seems
necessary because our tests started failing with the message below
(lines wrapped to make sure we don't run over the 100 character limit
for the git commit message)
cactus-corda-4-8-all-in-one-flowdb:2024-07-08-hotfix-1]
[WARN] 09:48:28+0000 [Thread-2
(ActiveMQ-server-org.apache.activemq.artemis.core.server.impl.ActiveMQServerImpl$6@11a43807)]
core.server. -
AMQ222210: Free storage space is at 145.7MB of 77.9GB total. Usage rate is 99.8% which is
beyond the configured <max-disk-usage>. System will start blocking producers.
**A Must …
> ci(connector-corda): fix insufficient disk space errors

- .cspell.json
- .github/workflows/ci.yaml
- .github/workflows/coverage_ts.yaml
- tools/ci.sh
---
ci(coverage): add total typescript code coverage statistics
```
1. Updated the ci.yaml and ci.sh to introduce total typescript code coverage statistics using jest and istanbul-merge
```
Fixes #2661
> ci(coverage): add total typescript code coverage statistics

- .github/workflows/ci.yaml
- examples/cactus-example-supply-chain-backend/src/main/typescript/public-api.ts
- examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
- examples/cactus-example-supply-chain-backend/src/test/typescript/integration/supply-chain-cli-via-npm-script.test.ts
1. The test case was hanging at the end because it was waiting  for a
magic string to appear in the logs to indicate that the booting has finished.
2. The problems began when we changed the supply chain app's log message
from mentioning Cactus to Cacti which then invalidated the condition forever.
3. This left it hanging indefinitely and the test case was broken.
4. Now to fix the problem and avoid this happening again in the future
the supply chain app exports the log message pattern as a variable and the
test case imports that directly so if we change the log message in the
future it will automatically make sure that the test is also waiting for
the updated log message pattern to show up in the logs making this class
of bugs impossible to happen. …
> test(supply-chain-app-backend): fix via-npm-script.test.ts hanging

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/common/get-transaction-receipt-by-tx-id.ts
Since commit 8c030ae9e739a28ff0900f7af27ec0fbbb4b7ff9 we have to
manually decode the protocol buffer block data because the
querySystemChainCode() does not do it for us by default anymore.
This was causing some type-checks to fail in getTransactionReceiptByTxID()
which were explicitly guarding against receiving `Buffer`s as responses
but now the only thing we receive from the query system chain code method
is exactly `Buffer` type objects.
> fix(connector-fabric): decode blocks in getTransactionReceiptByTxID()

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/query-system-chain-methods.test.ts
The system chaincode query method's returns were not decoded correctly
because the test request assembling code was not updated to call the
responseType as such (old name was type)
> test(connector-fabric): fix rename type to responseType getBlockV1()

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-ws-ids.test.ts
- packages/cactus-test-tooling/src/main/typescript/ws-test-server/ws-test-server.ts
1. The hostconfig portion of the container start configuration was not
being set up correctly which made it so that the exposed ports were not
published on randomized ports like they were supposed to.
2. This caused  the `fabric-v2-2-x/run-transaction-with-ws-ids.test.ts`
test to fail because it couldn't map the container port to a host machine
port.
3. Setting up the ws-test-server.ts class so that it does map the ports
to the host machine solved the issue.
> test(test-tooling): fix WS identity server port publish configuration

- packages/cactus-plugin-bungee-hermes/package.json
- packages/cactus-plugin-bungee-hermes/src/main/typescript/plugin-bungee-hermes.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/strategy/obtain-ledger-strategy.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/strategy/strategy-besu.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/strategy/strategy-ethereum.ts
- packages/cactus-plugin-bungee-hermes/src/main/typescript/strategy/strategy-fabric.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/besu-test-basic.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/besu-test-pruning.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/bungee-api-test.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/bungee-merge-views.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/bungee-process-views.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/ethereum-test-basic.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/fabric-test-basic.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/fabric-test-pruning.test.ts
- yarn.lock
BUNGEE-Hermes required API credentials for ledger connectors within its methods. This change enables using Bungee with the connectors themselves.
https://github.com/hyperledger/cacti/pull/3251#pullrequestreview-2077548976
Summary:
- This includes the implementation to possibilitate the usage of ledgers connectors without instaciating API's with bungee.
- Tests changed to test for both using connectos and API's.
> feat(bungee-hermes): ability to use connectors without instanciating APIs

- packages/cactus-test-tooling/src/main/typescript/common/build-container-image.ts
- packages/cactus-test-tooling/src/main/typescript/corda/build-image-connector-corda-server.ts
- packages/cactus-test-tooling/src/main/typescript/corda/build-image-corda-all-in-one-v4-12.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
- tools/docker/corda-all-in-one/README.md
1. Currently our integration tests depend on pre-published container
images to be on the official registry (ghcr.io). This has pros and cons.
The pro is that we can pin the tests to a specific ledger version and
then have confidence that the test code works with that specific image.
On the other hand if the image itself has problems we won't know it until
after it was published and then tests were executed with it (unless we
perform manual testing which is a lot of effrot as it requires the
manual modification of the test cases).
2. In order to gives us the ability to test against the container image
definitions as they are in the current revision of the source code,
we are adding here a couple of utility functions to streamline writing
test cases that build the container images for …
> test(test-tooling): add container image builder utilities

- .github/workflows/coverage_ts.yaml
---
ci(coverage): change coverage_ts.yaml condition to use success only 
```
1. Updated the condition in coverage_ts.yaml to run only 
when the CI run is successful
```
Fixes #3371
> ci(coverage): change coverage_ts.yaml condition to use success only

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-source/deploy-contract-go-source-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract/deploy-contract-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/get-block/get-block-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/get-prometheus-exporter-metrics/get-prometheus-exporter-metrics-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/get-transaction-receipt/get-transaction-receipt-by-txid-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/run-transaction/run-delegated-sign-transaction-endpoint-v1.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/run-transaction/run-transaction-endpoint-v1.ts
1. Error-handling : Updates to the catch block of the Rest API endpoints of fabric package by importing the utility function handleRestEndpointException from cactus-core package that differentiates the user/developer errors.
2. Minor code changes in the endpoints like adding the functions and formulating the error messages.
> refactor(connector-fabric): reusable error handler in REST endpoints

- weaver/tests/network-setups/fabric/dev/Makefile
- weaver/tests/network-setups/fabric/dev/base.env
- weaver/tests/network-setups/fabric/dev/docker/docker-compose-ca.yaml
- weaver/tests/network-setups/fabric/dev/network.sh
While fabric setup for weaver tests downloads images specified in the Makefile, when the network is brought up the latest versions are pulled.
**Primary Change:**
- pass fabric versions from Makefile to network.sh, ensuring they are used
**Secondary Changes:**
network.sh:
- allow specifying fabric ca version
- set exit on error bash flag to avoid continuing if script is in error
- re-write unsupported version tests to not not generate error
> chore(weaver): use specific fabric versions

- packages/cactus-plugin-satp-hermes/package.json
- Some systems can experience failures due to concurrent forge file access.
> fix(satp-hermes): run sequencial instead of paralel

- BUILD.md
---
docs(build): add text build steps for Mac
```
1. Updated BUILD.md to include Mac OS specific installation instructions. 
2. Added placeholders for Linux and Windows specific instructions.
```
Fixes #1963 
Signed-off-by: ashnashahgrover <as19@williams.edu>
> docs(build): add text build steps for Mac

- .github/workflows/actionlint.yaml
- .github/workflows/weaver_deploy_go-pkgs.yml
1. There is a set of yaml workflow files that have to be removed prior to the
action lint task because they have hundreds of unfixed errors that we didn't
yet have time to address and the action lint github action has no easy way
to ignore files unfortunately so the easiest way to achieve that is to wipe
the fiels we don't want linting. This workaround caused a problem with the
workflow reuse improvements we were recently trying to introduce. So now
the way they get excluded is that we feed an explicit list of workflow files
to the linter that we want to get linted and we exclued the problematic files
from that list.
2. Also fixed on linter warning with the docker login action being outdated. …
> ci(actionlint): exclude files with very large number of linter errors

- .github/workflows/ci_weaver.yaml
- .github/workflows/test_weaver-asset-exchange-besu.yaml
- .github/workflows/test_weaver-asset-exchange-corda.yaml
- .github/workflows/test_weaver-asset-exchange-fabric.yaml
- .github/workflows/test_weaver-asset-transfer.yaml
- .github/workflows/test_weaver-corda-interop-app.yaml
- .github/workflows/test_weaver-data-sharing.yaml
- .github/workflows/test_weaver-docker-build.yaml
- .github/workflows/test_weaver-fabric-fabric-satp.yaml
- .github/workflows/test_weaver-go.yaml
- .github/workflows/test_weaver-node-pkgs.yaml
- .github/workflows/test_weaver-pre-release.yaml
- .github/workflows/test_weaver-relay.yaml
**Primary change:**
Creates a central workflow to run all 13 weaver test workflows from either a
push, a pull request, a github command, or a schedule.
Passes a 'run_all' boolean to sub-workflows to specify if all tests should be run, not
just those with changes.
**Secondary changes:**
- update concurrency groups to allow triggering from central workflow
- remove ability to run the 13 workflows individually to declutter ci menu
**Notes:**
* For example workflow output see here: https://github.com/jenniferlianne/cacti/actions/runs/10062422329  (jobs are displayed as a tree on the left).  
* A number of weaver tests are commented out with an 'if false' these were left unchanged.
Depends on #3446
- [x ] Pull Request Title and Commit Subject …
> refactor(ci/github): run weaver tests on schedule, re-use workflows

- .github/workflows/pr-commit-parity.yaml
- tools/pr-commit-parity.js
ci(github): workflow to ensure PR commit parity 
1. Added a script which ensures PR body and commit message
parity
Changes needed to incorporate 1)
--------------------------------
2. Added a new workflow to enable the same
Fixes #2214
> ci(github): workflow to ensure PR commit parity

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-plugin-keychain-aws-sm/src/test/typescript/integration/openapi/openapi-validation.test.ts
- packages/cactus-plugin-keychain-aws-sm/src/test/typescript/integration/plugin-keychain-aws-sm.test.ts
- packages/cactus-plugin-keychain-aws-sm/src/test/typescript/unit/api-surface.test.ts
- packages/cactus-plugin-keychain-aws-sm/src/test/typescript/unit/api-surface.ts
1. The Jest test execution was turned off for the AWS SM keychain plugin
for some reason so this PR enables it back and while at it
2. I also refactored one of the test cases to have less linter warnings
about us casting to `any`.
3. And on top of that I also migrated one of the test cases to Jest from
TAP/tape so that we are making some progress with the test coverage at
the same time.
One more notable thing is that I refactored the negative test assertions
while migrating to Jest so the test case now uses Jest native assertions
to check what exactly the error message returned by the API call for
deleting a non-existent item looks like. This is an example of the
refactoring that this issue is about:
https://github.com/hyperledger/cacti/issues/3455 …
> ci(github): fix keychain-aws-sm no code coverage files/dir found

- .github/workflows/ci.yaml
> ci(github): upgrade actions/github-script to 7.0.1 project-wide

- .github/workflows/ci.yaml
- .github/workflows/daml-all-in-one-publish.yaml
- tools/docker/daml-all-in-one/Dockerfile
- tools/docker/daml-all-in-one/README.md
- tools/docker/daml-all-in-one/generate-jwt-token.sh
- tools/docker/daml-all-in-one/healthcheck.sh
- tools/docker/daml-all-in-one/supervisord.conf
---
feat(connector-daml): aio image
```
1. Create a docker image on daml-all-in-one folder that contains an initial creation of DAML smart contracts
```
Fixes #3284
> feat(connector-daml): aio image

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/get-block/cacti-block-formatters.ts
- packages/cactus-plugin-persistence-fabric/README.md
- packages/cactus-plugin-persistence-fabric/package.json
- packages/cactus-plugin-persistence-fabric/src/main/sql/schema.sql
- packages/cactus-plugin-persistence-fabric/src/main/typescript/db-client/db-client.ts
- packages/cactus-plugin-persistence-fabric/src/test/typescript/manual/common-setup-methods.ts
- packages/cactus-plugin-persistence-fabric/src/test/typescript/manual/complete-sample-scenario.ts
- packages/cactus-plugin-persistence-fabric/src/test/typescript/manual/sample-setup.ts
- packages/cactus-plugin-persistence-fabric/tsconfig.json
- tools/docker/fabric-all-in-one/Dockerfile_v2.x
- tools/docker/fabric-all-in-one/run-fabric-network.sh
- yarn.lock
- Fix error when empty `transaction.actions` was received from a block.
- Copy schema SQL during build.
- Remove unique constraint on fabric transactions hash column (there are transactions with empty hash that would break it).
- Improve parsing of certificate subject/issuer attributes to handle more delimiters.
- Use new `install-fabric.sh` script (that is recommended for Fabric 2.5) instead of old bootstrap to fix some runtime issues that I've encountered.
- Add sample setup scripts. Simple can be used to run persistence against already running fabric ledger, complete will setup entire environment and run some basic operations to generate sample data.
- Improve documentation to include these new scripts and how to use them, fix smaller issues.
**Character …
> feat(persistence-fabric): add sample setup scripts, improve documentation

- .github/workflows/deploy_docs.yml
- .github/workflows/test_weaver-asset-exchange-fabric.yaml
- .github/workflows/test_weaver-asset-transfer.yaml
- .github/workflows/test_weaver-data-sharing.yaml
- .github/workflows/test_weaver-fabric-fabric-satp.yaml
- docs/mkdocs.yml
- weaver/samples/corda/corda-simple-application/clients/build.gradle
- weaver/samples/corda/corda-simple-application/makefile
- Fixes the failing `deploy_docs.yaml` action by adding token with appropriate permissioning.
- Pegs the `protoc-gen-go-grpc` version in the relevant actions to `v1.4.0` to match what's written in the documentation (this avoids test network setup failures when running integration tests.)
- Removed dead code from the Weaver Corda sample application.
- Made `mkdocs` publish URL customizable by owner.
> fix(ci): updated permissioning and versioning in GitHub Actions

- packages/cactus-plugin-ledger-connector-aries/src/test/typescript/integration/aries-setup-and-connections.test.ts
test(aries): refactor jest test negative test cases
``` 
1. Refactored all the negative test case exception assertions for
cactus-plugin-ledger-connector-aries. Removed try-catch blocks,
replaced with declarations through jest-extended's own API.
```
Fixes #3473
> test(aries): refactor jest test negative test cases

- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-record-locator.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/invoke-contract.test.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/openapi/openapi-validation.test.ts
test(besu): refactor jest test negative test cases
``` Primary Changes ----------------
1. Refactored all negative test case exception assertions for cactus-plugin-ledger-connector-besu.
Removed try-catch blocks, replaced with declarations through jest and jest-extended's own API.
2. Noted two tests within openapi-validation.test.ts
(GetPastLogsEndpoint and GetBesuRecordEndpointV1 with empty parameters) where the status
code returned should be 400 but is 200. This could be investigated in a seperate issue.
```
Fixes #3467
> test(besu): refactor jest test negative test cases

- packages/cactus-core-api/package.json
- packages/cactus-core-api/src/main/typescript/open-api/create-ajv-type-guard.ts
- packages/cactus-core-api/src/main/typescript/open-api/create-is-jws-general-type-guard.ts
- packages/cactus-core-api/src/main/typescript/public-api.ts
- packages/cactus-core-api/src/test/typescript/unit/open-api/create-ajv-type-guard.test.ts
- packages/cactus-core-api/src/test/typescript/unit/open-api/create-is-jws-general-type-guard.test.ts
- packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
- yarn.lock
1. createAjvTypeGuard<T>() is the lower level utility which can be used
to construct the more convenient, higher level type predicates/type guards
such as createIsJwsGeneralTypeGuard() which uses createAjvTypeGuard<JwsGeneral>
under the hood.
2. This commit is also meant to be establishing a larger, more generic
pattern of us being able to create type guards out of the Open API specs
in a convenient way instead of having to write the validation code by hand.
An example usage of the new createAjvTypeGuard<T>() utility is the
createIsJwsGeneralTypeGuard() function itself.
An example usage of the new createIsJwsGeneralTypeGuard() can be found
in packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
The code documentation contains examples as well for …
> feat(core-api): add createIsJwsGeneralTypeGuard, createAjvTypeGuard<T>

- .github/workflows/pr-commit-parity.yaml
- package.json
- tools/pr-commit-parity.js
- yarn.lock
ci(github): commit parity check based on similarity 
1. Added a commit-pr similarity ratio to lessen the check strictness
2. Added an env var to the workflow to easily control the similarity
ratio
Changes required to incorporate 1)
3. Added string-similarity-js package in package.json
Fixes #3470
> ci(github): commit parity check based on similarity

- packages/cactus-plugin-satp-hermes/src/main/json/openapi-blo-bundled.json
- packages/cactus-plugin-satp-hermes/src/main/typescript/blo/admin/get-status-handler-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/blo/dispatcher.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/blo/transaction/transact-handler-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage3-client-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage3-server-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/generated/gateway-client/typescript-axios/api.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/gol/satp-manager.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/web-services/get-all-session-ids-endpoints.ts
- packages/cactus-plugin-satp-hermes/src/main/yml/bol/openapi-blo-bundled.yml
- packages/cactus-plugin-satp-hermes/src/main/yml/bol/openapi-blo.yml
- packages/cactus-plugin-satp-hermes/src/main/yml/bol/schemas.yml
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-end-to-end-transfer-1-gateway.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-end-to-end-transfer-2-gateways-openapi.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-end-to-end-transfer-2-gateways.test.ts
Some small improves in the GetStatus endpoint for a little more information when asking for status (instead of the default return). there is still room for improvement.
Created a getAllSessionsIds endpoint which may be useful in the admin api.
> feat(satp-hermes): improve admin endpoints

- .github/workflows/coverage_ts.yaml
https://github.com/advisories/GHSA-cxww-7g56-2vh6
Address the following problem by upgrading to the latest version:
@actions/download-artifact has an Arbitrary File Write via artifact extraction
Affected versions
>= 4.0.0, < 4.1.7
Patched versions
4.1.7
Severity
High
7.3 / 10
GHSA ID
GHSA-cxww-7g56-2vh6
References
- GHSA-cxww-7g56-2vh6
- https://github.com/actions/download-artifact/releases/tag/v4.1.7
- GHSA-6q32-hq47-5qq3
- https://snyk.io/research/zip-slip-vulnerability
> build(github): fix @actions/download-artifact CVE-2024-42471

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-api-client/package.json
- packages/cactus-api-client/src/test/typescript/integration/default-consortium-provider.test.ts
- yarn.lock
This was the final test case that was still using TAP so now we got to
turn off the tape invocation in the ci completely which is also a performance
gain worth mentioning.
> test(api-client): jestify default-consortium-provider.test.ts

- openapi-generator-ignore
fix(openapi): openapi-generator-ignore file
1. Fixed openapi-generator-ignore file to include the
merge conflict error fix
> fix(openapi): openapi-generator-ignore file

- .github/workflows/pr-commit-parity.yaml
- package.json
- tools/pr-commit-parity.js
- yarn.lock
ci(github): skip commit parity for bots
1. Updated the workflow to include a skip
when the PR author is dependabot
2. Updated the pr-commit parity script to
include Levenshtein Distance string metric
instead of importing a package to reduce
workflow runtime
Changes required to incorporate 1)
3. Updated workflows/pr-commit-parity.yaml with
a conditional statement
Changes required to incorporate 2)
4. Updated the script with the functions,
levensheteinDistance and stringSimilarity
to have the required functionality
5. Updated the package.json with removal of the
package dependency of string-similarity-js
6. Updated the workflow and removed steps to
parse the project, thus reducing workflow
runtime
Fixes #3469 …
> ci(github): skip commit parity for bots

- .cspell.json
- packages/cactus-test-tooling/src/main/typescript/corda/build-image-besu-all-in-one-latest.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
1. This will help author test cases for the Besu connector that are designed
to be testing the latest version of the image instead of a pinned one that
we pull from the registry as part of the test case.
2. We need tests for both latest and pinned image versions if we want to
make sure that the connector is backward compatible with older ledger versions.
> test(test-tooling): add new besu AIO image builder utility

- .github/workflows/pr-commit-parity.yaml
ci(github): fix commit parity running outside PR 
1. Updated the workflow to run only on Pull Requests
Fixes #3515
> ci(github): fix commit parity running outside PR

- .devcontainer/devcontainer.json
- .vscode/extensions.json
1) updated trivy version in the .devcontainer file and included trivy vs-code extension
Changes required to incorporate 1)
3) included trivy vs-code extension in the .vscode/extensions.json file
Fixes https://github.com/hyperledger/cacti/issues/2650
Signed-off-by: ashnashahgrover <as19@williams.edu>
> docs(devcontainer): add trivy and its VSCode Extension

- weaver/common/protos-java-kt/build.gradle
- weaver/core/network/corda-interop-app/build.gradle
This bug was detected in release of `v2.0.0-rc.4`, by the deployment workflow
> fix(weaver-corda): added duplicate handling strategy in build.gradle

- .cspell.json
- packages/cactus-test-tooling/src/main/typescript/daml/daml-test-ledger.ts
- packages/cactus-test-tooling/src/main/typescript/public-api.ts
- tools/docker/daml-all-in-one/Dockerfile
- tools/docker/daml-all-in-one/README.md
test(test tooling): add DamlTestLedger implementation
```
1. Create a test tooling class for DAML AIO Image
```
Fixes #3435 
> test(test tooling): add DamlTestLedger implementation

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install-version-selection.test.ts
> test(test-cmd-api-server): jestify plugin-import-with-npm-install-version

- .github/workflows/all-nodejs-packages-publish.yaml
The NodeJS package publishing GitHub workflow job will now publish
all packages to both GHCR and npmjs.org registries.
It dynamically reconfigures the .npmrc file with the appropriate registry
URL and the correct token gets set through the environment variables as well.
The lerna publish script gets invoked twice, with different registry configurations
which was the only way I found to make sure that all the packages are deployed
to all the locations where they are to be used.
Fixes #451
> ci(release-automation): make release issuance atomic

- packages/cactus-test-tooling/src/main/typescript/openethereum/openethereum-test-ledger.ts
---
fix(test-tooling): use of hardcoded password
```
1. BREAKING CHANGE: "password" is now a mandatory parameter of the newEthPersonalAccount function
defined in openethereum-test-ledger.ts. It was previously optional.
2. Updated line 236 in openethereum-test-ledger.ts so the default password argument to the
newEthPersonalAccount function is not hardcoded.
```
Fixes #2766
> fix(test-tooling): use of hardcoded password

- .github/workflows/all-nodejs-packages-publish.yaml
The `all-nodejs-packages-publish.yaml` workflow now has an input parameter
where one can specify an arbitrary release git tag (such as v2.0.0-rc.5)
to be the one to be published.
This will help us in scenarios where the release automation script failed to
run on GitHub and we have no way of publishing the given release manually
from a local machine (since we do not have access to the npm/ghcr) tokens
of the foundation (which is good security posture that we are happy to have)
In the scenario described above, in the future this will (should) allow us
to fix bugs in the release automation script in commits that come **after**
the failed release and then manually trigger the updated (now functional)
publish job for the older release version.
This will (hopefully) grant us the ability to …
> ci(github): enable manual publishing of custom git tags via input args

- packages/cacti-ledger-browser/src/main/typescript/apps/eth/index.tsx
- packages/cacti-ledger-browser/src/main/typescript/apps/fabric/index.tsx
``` 
Changes
1. Added links to documentation and setup guides for eth-browser and fabric-browser.
```
Fixes #3550 
> docs(ledger-browser): add links to documentation 

- packages/cactus-plugin-ledger-connector-besu/src/main/go/generated/openapi/go-client/api/openapi.yaml
- packages/cactus-plugin-ledger-connector-besu/src/main/go/generated/openapi/go-client/model_deploy_contract_solidity_bytecode_no_keychain_v1_request.go
- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.tpl.json
- packages/cactus-plugin-ledger-connector-besu/src/main/proto/generated/openapi/models/deploy_contract_solidity_bytecode_no_keychain_v1_request_pb.proto
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/proto/protoc-gen-ts/models/deploy_contract_solidity_bytecode_no_keychain_v1_request_pb.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/impl/deploy-contract-v1/deploy-contract-v1-keychain.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/impl/deploy-contract-v1/deploy-contract-v1-no-keychain.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/impl/transact-v1/transact-v1-signed.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/deploy-contract-solidity-bytecode-no-keychain-endpoint.ts
- packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/v21-deploy-contract-from-json-no-keychain.test.ts
In the DeployContractSolidityBytecodeNoKeychainV1Request of
`packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.tpl.json`
there are parameters that are required despite the entire point of this
operation is to not need them (e.g. keychainId and contract JSON object).
Fixes #3586
> fix(besu): deployContractSolBytecodeNoKeychainV1 requires keychainId

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-sign-transaction-endpoint.test.ts
test(test-plugin-ledger-connector-besu): jestify v21-sign-transaction-endpoint
```
packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/
integration/plugin-validator-besu/v21-sign-transaction-endpoint.test.ts
```
Fixes #3565
> test(test-plugin-ledger-connector-besu): jestify v21-sign-transaction-endpoint

- .github/workflows/pr-commit-parity.yaml
- tools/pr-commit-parity.js
ci(github): pr parity to include hyphen
1. Updated the code to remove the hyphen regex from the pr-commit parity script
2. Removed an unused var from the workflow
Fixes #3557
> ci(github): pr parity to include hyphen

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-cmd-api-server/src/test/typescript/unit/config/config-service-example-config-validity.test.ts
- packages/cactus-cmd-api-server/src/test/typescript/unit/grpc-proto-gen-ts-client-healthcheck.test.ts
1. Also fixing a minor bug in config/config-service-example-config-validity.test.ts
where the path of the temporary files generated by the test were being saved
in the wrong directory instead of $PROJECT_ROOT/.tmp/...
> test(cmd-api-server): jestify grpc-proto-gen-ts-client-healthcheck test

- examples/cactus-example-supply-chain-frontend/tsconfig.json
- examples/test-run-transaction/tsconfig.json
- packages/cactus-common/src/main/typescript/exception/create-runtime-error-with-cause.ts
- tsconfig.base.json
- tsconfig.json
Project-wide upgrade to Typescript target of ES2022 so that we can use
the new Error APIs.
Wherever possible we should now use the new `cause`
property of the built-in `Error` type in combination
with the `asError(unknown)` utility function:
```typescript
import { asError } from "@hyperledger/cactus-common";
try {
await performSomeImportantOperation();
} catch (ex: unknown) {
const cause = asError(ex);
throw new Error("Something went wrong while doing something.", { cause });
}
```
More information about the EcmaScript proposal that made this possible:
https://github.com/tc39/proposal-error-cause
Fixes #3592
For rebasing and squashing, here's a …
> build: migrate to Typescript target of ES2022 and use Error.cause

- .github/workflows/ci.yaml
- tools/ci-skip-for-maintainers.js
---
perf(github): add knob/flag to manually override CI skip
```
1. Created a function to check if the commit message
contains 'cacti-skip-ci' to skip the CI check.
2. Check if the request is from the maintainer or not.
If he is a Maintainer, the CI-skip request will be
granted, else not.
```
Fixes #2679
> perf(github): add knob/flag to manually override CI skip

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-get-past-logs-endpoint.test.ts
test(connector-besu): migrate v21-get-past-logs-endpoint to Jest
```
packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/
integration/plugin-validator-besu/v21-get-past-logs-endpoint.test.ts
```
Fixes: #3572
Signed-off-by: Udhayakumari <62878965+Udhayakumari@users.noreply.github.com>
> test(connector-besu): migrate v21-get-past-logs-endpoint to Jest

- docs/scripts/publish_openapi.py
Primary Change: The openapi doc generation script had a reference to the @hyperledger package prefix hardcoded.
This meant that packages that were updated to @hyperledger-cacti still had an ampersand in their path, resulting in 
them not being included in the generated documentation.
> chore(docs): fix packagename ref in openapi doc generation

- .github/workflows/.dast-nuclei-cmd-api-server.yaml
ci(github): fix DAST scan besu connectivity
--------------
1. Hardcoded the localhost to 127.0.0.1 for the config.json file
required to spin up cactus-cmd-api-server
Secondary Changes
-----------------
3. Updated the verion of besu AIO
4. Updated the version of nuclei
Changes required to incorporate 3)
5. Updated the go version
Fixes #3596
> ci(github): fix DAST scan besu connectivity

- packages/cactus-plugin-satp-hermes/src/knex/migrations/20220331132128_create_logs_table.ts
- packages/cactus-plugin-satp-hermes/src/main/proto/cacti/satp/v02/crash_recovery.proto
- packages/cactus-plugin-satp-hermes/src/main/typescript/repository/interfaces/repository.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/repository/knex-local-log-repository.ts
- Added new protocol buffer definitions to extend functionality for Crash Recovery RPCs.
- Modified the database table structure to include the sequence_number field from `sessionData`. This enhancement enables retrieving logs from the server that has a sequence number greater than the one provided by the client, improving synchronization during rollback and recovery processes.
Addresses #3114 
> feat: add proto-definitions and update table structure

- .github/workflows/all-nodejs-packages-publish.yaml
- .github/workflows/publish-npm.yaml
---
ci(release): add sigstore npm integration through --provenance
```
1. Added provenance config to the publish workflows.
```
Fixes #2623
> ci(release): add sigstore npm integration through --provenance

- packages/cactus-plugin-ledger-connector-besu/src/main/go/generated/openapi/go-client/api/openapi.yaml
- packages/cactus-plugin-ledger-connector-besu/src/main/go/generated/openapi/go-client/model_deploy_contract_solidity_bytecode_no_keychain_v1_request.go
- packages/cactus-plugin-ledger-connector-besu/src/main/go/generated/openapi/go-client/model_deploy_contract_solidity_bytecode_v1_request.go
- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
- packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.tpl.json
- packages/cactus-plugin-ledger-connector-besu/src/main/proto/generated/openapi/models/deploy_contract_solidity_bytecode_no_keychain_v1_request_pb.proto
- packages/cactus-plugin-ledger-connector-besu/src/main/proto/generated/openapi/models/deploy_contract_solidity_bytecode_v1_request_pb.proto
- packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
Prior to this commit the Besu connector's API validated requests when deploying solidity
contracts via their bytecode such that the length of the bytecode parameter
cannot be longer than 24576 characters, but instead it should have an upper limit of
49154 characters because each byte is represented as two characters in hex.
See https://ethereum.stackexchange.com/a/47556 regarding the maximum length of the bytecode.
2 + (24576 * 2) = 49154 meaning that hex stores each byte in 2 characters and that
there is a 0x prefix (2 characters) which does not count towards the EVM 24576 bytecode limit."
Fixes #3636
For rebasing and squashing, here's a [must …
> fix(connector-besu): set contract bytecode field's max length to 49154

- examples/cactus-example-supply-chain-backend/README.md
Previously if you executed the image build commands that use the branch name
to produce container image tag names then you received an error if your branch
name contained a forward slash (/) which is common for people who use VSCode
extensions for managing branches related to pull requests.
The new commands are using `sed` to remove the forward slashes from the branch names
and replace them with underscores (_) so that the container image tags are
valid.
> docs(readme): fix container image build cmds: drop / from branch names

- packages/cacti-plugin-consortium-static/src/main/json/openapi.json
- packages/cacti-plugin-consortium-static/src/main/json/openapi.tpl.json
- packages/cacti-plugin-consortium-static/src/main/kotlin/generated/openapi/kotlin-client/src/main/kotlin/org/openapitools/client/models/LedgerType.kt
- packages/cacti-plugin-consortium-static/src/main/typescript/generated/openapi/typescript-axios/api.ts
- packages/cactus-core-api/src/main/go/generated/openapi/go-client/api/openapi.yaml
- packages/cactus-core-api/src/main/go/generated/openapi/go-client/model_ledger_type.go
- packages/cactus-core-api/src/main/json/openapi.json
- packages/cactus-core-api/src/main/json/openapi.tpl.json
- packages/cactus-core-api/src/main/kotlin/generated/openapi/kotlin-client/src/main/kotlin/org/openapitools/client/models/LedgerType.kt
- packages/cactus-core-api/src/main/typescript/generated/openapi/typescript-axios/api.ts
Peter's change: Added the missing ETHEREUM constant to the leger type
that the static consortium plugin has built in to it.
This was necessary because adding it only to the core-api broke the build.
The two types (since they are duplicates of each other) must be updated in
tandem otherwise the code won't compile (which is a good thing because it
is an example if when the compiler saves us from mistakes like this that would
otherwise stay hidden until much later and only come out as runtime errors)
Authored-by: Bruno Mateus
Signed-off-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>
**A Must Read for …
> feat(cactus-core-api): add Ethereum ledger type

- packages/cacti-plugin-consortium-static/src/main/json/openapi.json
- packages/cacti-plugin-consortium-static/src/main/json/openapi.tpl.json
depends on PR https://github.com/hyperledger-cacti/cacti/pull/3638
Signed-off-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>
> feat(cactus-consortium): add Ethereum ledger type

- packages/cactus-common/src/main/typescript/log-level.ts
- packages/cactus-common/src/main/typescript/public-api.ts
- tools/custom-checks/get-all-tgz-path.ts
---
ci(github): fix type exports in packages/cactus-common
```
1. Removed packages/cactus-common/hyperledger-cactus-common-*.tgz in ignore 
paths in get-all-tgz-path.ts file
2. Added the log-level.ts for the missing exports detected by attw -f json
3. Added exports in public-api.ts from log-level.ts
```
Fixes: #3635
> ci(github): fix type exports in packages/cactus-common

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/deploy-contract-go-source/deploy-contract-go-source-impl-fabric-v2-5-6.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
feat(fabric): serialization of ccp and sshconfig 
1. sshConfig and connectionProfile can now be passed as base64 encoded strings
Changes required to incorporate 1)
2. Added sshConfigBase64Encoded and connectionProfileBase64encoded properties to IPluginLedgerConnectorFabricOptions
3. Added necessary FabricConnector class variables
4. Added a new testcase to demonstrate the same
5. Updated an implementation which fetches sshConfig from class variable
Fixes #3577
> feat(fabric): serialization of ccp and sshconfig

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-past-logs-endpoint.test.ts
test(connector-besu): migrate get-past-logs-endpoint to Jest 
------------------
1. Updated the migrate get-past-logs-endpoint test 
to use Jest
2. Updated the ci.yaml TAPE_TEST_PATTERN to
incorporate the same
Fixes #3505
> test(connector-besu): migrate get-past-logs-endpoint to Jest

- package.json
- yarn.lock
Dependabot is not able to resolve this (seemingly) simple vulnerability
issue so we have to get in there and manually bump `body-parser`.
https://github.com/hyperledger-cacti/cacti/security/dependabot/1218
CVE ID
CVE-2024-45590
GHSA ID
GHSA-qwcr-r2fm-qrc7
Fixes #3657
> fix: upgrade body-parser to >=1.20.3 to fix CVE-2024-45590 DoS attacks

- weaver/common/protos-js/package.json
- weaver/samples/fabric/fabric-cli/package-local.json
- weaver/samples/fabric/fabric-cli/package.json
- weaver/sdks/besu/node/package-local.json
- weaver/sdks/besu/node/package.json
- weaver/sdks/fabric/interoperation-node-sdk/package-local.json
- weaver/sdks/fabric/interoperation-node-sdk/package.json
NPM registry references changed from `hyperledger` to `hyperledger-cacti`.
Removed unnecessary publish reference from `fabric-cli`, which is meant to be used purely for local testing and experiments.
> fix(weaver-publish-npm): corrected publish URLs

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-transaction-endpoint.test.ts
packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/
integration/plugin-validator-besu/get-transaction-endpoint.test.ts
Fixes: #3539
Signed-off-by: Udhayakumari <62878965+Udhayakumari@users.noreply.github.com>
> test(connector-besu): jest migrate get-transaction-endpoint

- package.json
- packages/cactus-plugin-ledger-connector-ethereum/package.json
- yarn.lock
Versions of the package http-proxy-middleware before 2.0.7, from 3.0.0 and
before 3.0.3 are vulnerable to Denial of Service (DoS) due to an UnhandledPromiseRejection
error thrown by micromatch. An attacker could kill the Node.js process
and crash the server by making requests to certain paths.
CVE ID
CVE-2024-21536
GHSA ID
GHSA-c7qv-q95q-8v27
https://github.com/hyperledger-cacti/cacti/security/dependabot/1323
Fixes #3661
> fix(security): upgrade http-proxy-middleware to >=2.0.7 to mitigate DoS

- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/common/get-transaction-receipt-by-tx-id.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/public-api.ts
Authored-by: Eduardo Vasques eduardovasques10@tecnico.ulisboa.pt
Co-authored-by: Rafael Belchior rafael.belchior@tecnico.ulisboa.pt
Signed-off-by: Rafael Belchior rafael.belchior@tecnico.ulisboa.pt
> feat(cactus-connector-fabric): add get transaction receipt by tx id

- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/plugin-ledger-connector-ethereum.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/public-api.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/sign-utils.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/web-services/watch-blocks-v1-endpoint.ts
- packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-contract-deploy-and-invoke-using-keychain-v1.test.ts
Also improves watch blocks
Authored-by: Bruno Mateus <brumat315@gmail.com>
Co-authored-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>
Signed-off-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>
> feat(cactus-connector-ethereum): add RunTransactionV1Exchange to share receipt data

- .pre-commit-config.yaml
- CONTRIBUTING.md
- package.json
chore: install secret detection on pre-commit hooks
```
1. Installed gitleaks for secret detection.
2. This pre-commit checker detects any secrets
or crypto so that it doesn't get pushed to
the github repo.
3. Added script to run install and uninstall
the pre-commit hooks in package.json
```
Fixes #2290
> chore: install secret detection on pre-commit hooks

- packages/cactus-plugin-satp-hermes/package.json
- packages/cactus-plugin-satp-hermes/src/knex/knexfile-remote.ts
- packages/cactus-plugin-satp-hermes/src/knex/knexfile.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/blo/dispatcher.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage0-client-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage1-client-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage2-client-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage3-client-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/satp-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage0-server-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage1-server-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage2-server-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage3-server-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/types.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/gateway-utils.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/gol/satp-manager.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/logging.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/unit/services.test.ts
- yarn.lock
- refactored gateway argument in `storeLog`  & `storeProof` in gateway utils file.
- modified interface BLODispatcherOptions & SATPGatewayConfi , so that we can add the database connections, also injecting the dependencies of repository to the `SATPmanager` so the respective services have a way to store the logs.
- Improved SATP client and server stage services with databse logging.
- Added a new logging file to centralize and simplify log operations. (`logging.ts`)
- test on `packages/cactus-plugin-satp-hermes/src/test/typescript/unit/services.test.ts`
Addresses #3114 
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for …
> feat: add satp logging in all satges

- .github/workflows/ci.yaml
---
ci(trivy): fix scan failures due to TOOMANYREQUESTS DB error
```
1. Updated the ci.yaml to make the trivy scan 
run only on the weekends
```
Fixes #3652
> ci(trivy): fix scan failures due to TOOMANYREQUESTS DB error

- packages/cactus-plugin-satp-hermes/package.json
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/constants.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/gateway-init-startup.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-dockerization.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-with-bungee.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways-dockerization.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways-openapi.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways.test.ts
> fix(satp-hermes): miss spell and missing import

- examples/cactus-example-supply-chain-backend/Dockerfile
test(ghcr-example-supply-chain-app): fix missing patch @ionic-native
```
1. Updated the NVM version to 20.11.1 and added
the necessary yarn patch path to build the image
```
Fixes #3601
> test(ghcr-example-supply-chain-app): fix missing patch @ionic-native

- packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts
> fix(satp-dev): spelling

- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage0-client-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage2-client-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage0-server-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/gateway-blo.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/gateway-init-startup.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-with-bungee.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways-openapi.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/knex.config.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/unit/services.test.ts
1.Integrated knexLocalConfig and knexRemoteConfig into SATPGatewayConfig
Fixes https://github.com/hyperledger-cacti/cacti/pull/3665
Signed-off-by: Yogesh01000100 <yogeshone678@gmail.com>
> fix(test): add knex config in gateway

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts
test(htlc-eth-besu-erc20): migrate get-status-endpoint to Jest
```
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript /integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts
```
Fixes: #3650
Signed-off-by: Udhayakumari <62878965+Udhayakumari@users.noreply.github.com>
> test(htlc-eth-besu-erc20): migrate get-status-endpoint test cases to Jest

- examples/cactus-example-cbdc-bridging-frontend/package.json
- tools/custom-checks/get-all-tgz-path.ts
---
ci(github): fix type exports in cactus-example-cbdc-bridging-frontend
```
1. Removed examples/cactus-example-cbdc-bridging-frontend-*.tgz in ignore paths in get-all-tgz-path.ts file
2. Added main, module, types, and files in package.json
```
Fixes: #3631
> ci(github): fix type exports in cactus-example-cbdc-bridging-frontend

- packages/cactus-plugin-bungee-hermes/src/main/typescript/plugin-bungee-hermes.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/bungee-api-test.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/bungee-merge-views.test.ts
- packages/cactus-plugin-bungee-hermes/src/test/typescript/integration/bungee-process-views.test.ts
> fix(bungee-hermes): merge and process views tests

- .github/workflows/.dast-nuclei-cmd-api-server.yaml
- .github/workflows/ghpkg-all-kotlin-api-clients-publish.yaml
actions/upload-artifact and actions/download-artifact have been deprecated and need updated.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> chore: update actions

- package.json
- packages/cactus-plugin-satp-hermes/gateway-config.json
- packages/cactus-plugin-satp-hermes/src/main/typescript/blo/dispatcher.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/crash-management/server-service.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/session-utils.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/gol/crash-manager.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/gol/satp-manager.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/logging.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/repository/interfaces/repository.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/repository/knex-local-log-repository.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/gateway-init-startup.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/unit/SATPGatewayRunner-instantiation.test.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/unit/services.test.ts
- yarn.lock
- Fixed logging issues.
- If no configuration for the local database is provided, the system will default to using a local SQLite3 database and perform a migration upon the first login.
> fix(satp-hermes): when a db is not provided it creates a local repository, remote db is not required anymore

- packages/cacti-ledger-browser/package.json
- tools/custom-checks/get-all-tgz-path.ts
---
ci(github): fix type exports in packages/cacti-plugin-copm-fabric
```
1. Removed packages/cacti-ledger-browser/hyperledger-cacti-ledger-browser-*.tgz
in ignore paths in get-all-tgz-path.ts file
2. Added main, module, types, and files in package.json
```
Fixes: #3630
> ci(github): fix type exports in packages/cacti-ledger-browser

- packages/cactus-plugin-ledger-connector-polkadot/package.json
- tools/custom-checks/get-all-tgz-path.ts
---
ci(github): fix type exports in cactus-plugin-ledger-connector-polkadot
```
1. Removed packages/cactus-plugin-ledger-connector-polkadot/hyperledger-cactus-
plugin-ledger-connector-polkadot-*.tgz in ignore paths in get-all-tgz-path.ts
file
2. Fixed path for types in package.json
```
Fixes: #3634
> ci(github): fix type exports in cactus-plugin-ledger-connector-polkadot

- package.json
- packages/cactus-plugin-keychain-azure-kv/package.json
- packages/cactus-plugin-keychain-google-sm/package.json
- packages/cactus-plugin-keychain-vault/package.json
- yarn.lock
---
ci(custom-checks): fix dependencies being inconsistent phase 5
```
1. Fixed dependencies on targeted packages:
packages/cactus-plugin-keychain-azure-kv
packages/cactus-plugin-keychain-google-sm
packages/cactus-plugin-keychain-memory
packages/cactus-plugin-keychain-memory-wasm
packages/cactus-plugin-keychain-vault
```
Fixes: #3688
> ci(custom-checks): fix dependencies being inconsistent phase 5

- .github/workflows/all-nodejs-packages-publish.yaml
- .github/workflows/publish-npm.yaml
1. Updated publishing workflows to use gitHub.repository_owner variable
Fixes #3597
> ci(github): update publishing workflows to use github.repository_owner

- extensions/cactus-plugin-htlc-coordinator-besu/src/test/typescript/integration/plugin-htlc-coordinator/refund.test.ts
1. Refactored try-catch scenario in refund.test.ts
Fixes #3457
> test(plugin-htlc-coordinator-besu): use Jest error assert in refund.test

- tools/custom-checks/get-all-tgz-path.ts
---
ci(github): fix type exports in packages/cacti-plugin-copm-fabric
```
1. Removed packages/cacti-plugin-copm-fabric/hyperledger-cacti-cacti-plugin-
copm-fabric-*.tgz in ignore paths in get-all-tgz-path.ts file
2. Added main, module, types, and files in package.json
3. While fixing merge conflict, discovered new packages failing and added
on ignore path and created tickets for it
```
Fixes: #3629
> ci(github): fix type exports in packages/cacti-plugin-copm-fabric

- examples/cactus-example-cbdc-bridging-frontend/package.json
- examples/cactus-example-discounted-asset-trade/package.json
- examples/cactus-example-electricity-trade/package.json
- examples/cactus-example-electricity-trade/tools/transferNumericAsset/package.json
- examples/test-run-transaction/package.json
- packages/cacti-ledger-browser/package.json
- packages/cactus-test-plugin-keychain-memory/package.json
1. Removed the private property from various package.json files
Fixes #3667
> ci(github): fix Can't generate provenance for new or private package

- CODEOWNERS
chore(satp-hermes): add maintainers to satp-hermes package
This PR adds @LordKubaya and @AndreAugusto11 as maintainers for the `satp-hermes` package.
[skip ci]
> chore(satp-hermes): add maintainers to satp-hermes package

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-common/src/test/typescript/unit/logging/logger.test.ts
1. Fixed logger.test.ts after removing the skip on the test and UUID marker
now appears in the custom stream output
2. Migrated test file from tape to jest test
3. Removed file path of logger.test.ts in testPathIgnorePatterns to run jest
test
Peter's Updates
1. Removed the test case from the tap inclusion patterns in the CI workflow
and also in .taprc itself.
Fixes: #1465
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) …
> fix(logger): files needs to migrated from Tape to Jest

- tools/custom-checks/get-all-tgz-path.ts
---
ci(github): fix type exports in cactus-example-discounted-asset-trade
```
1. Removed examples/cactus-example-discounted-asset-trade/hyperledger-cactus-
example-discounted-asset-trade-*.tgz in ignore paths in get-all-tgz-path.ts
file
2. Custom-checks is running successfully
```
Fixes: #3740
> ci(github): fix type exports in cactus-example-discounted-asset-trade

- tools/custom-checks/get-all-tgz-path.ts
---
ci(github): fix type exports in cactus-example-discounted-asset-trade
```
1. Removed examples/cactus-example-electricity-trade/hyperledger-cactus-
example-electricity-trade-*.tgz in ignore paths in get-all-tgz-path.ts
file
2. Custom-checks is running successfully
```
Fixes: #3741
> ci(github): fix type exports in cactus-example-electricity-trade

- .github/workflows/all-nodejs-packages-publish.yaml
1. Added semver validation to all-nodejs-packages-publish.yaml
Fixes #2385
> ci(all-nodejs-packages-publish): restrict job trigger pattern to semver

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/refund-endpoint.test.ts
test(htlc-eth-besu-erc20): migrate refund-endpoint test cases from Tape to Jest
Primary changes:
```
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/refund-endpoint.test.ts
```
Fixes: #3701
Signed-off-by: Udhayakumari 62878965+Udhayakumari@users.noreply.github.com
> test(htlc-eth-besu-erc20): migrate refund-endpoint test cases from Tape to Jest

- weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh
1. Fixed network-setups fabric setupCC.sh:
weaver/tests/network-setups/fabric/dev/scripts/setupCC.sh
Peter's Changes
1. Fixed the commit message syntax so that it passes the linter
Fixes: #3679
Co-Authored-by: Peter Somogyvari <peter.somogyvari@accenture.com>
Signed-off-by: Daiki.Nakashima <Nakashima.Daiki@df.MitsubishiElectric.co.jp>
> ci(weaver): update network-setups fabric setupCC.sh

- packages/cacti-copm-core/README.md
Primary change: adds mermaid sequence diagrams for how COPM primitives are used in asset transfer, asset exchange, and data sharing to copm-core README
Secondary change: adds TOC and reformats urls to links.
> docs(copm): add sequence diagrams for COPM primitives

- packages/cactus-plugin-satp-hermes/src/main/typescript/api1/dispatcher.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/api1/gateway-errors.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/errors/satp-errors.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/core/satp-session.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts
- packages/cactus-plugin-satp-hermes/src/main/typescript/services/gateway/satp-manager.ts
- packages/cactus-plugin-satp-hermes/src/test/typescript/unit/shutdown-state.test.ts
Introduces a new function, `verifySessionState`, which upon shutdown verifies if all sessions are concluded. Also a flag was created to prevent new transactions to occur when shutdown was already called.
Additionally, a new type of error is introduced `gateway-error` .
Resolves #3756.
> fix(satp-hermes): shutdown of SATP gateway should assure there are no pending transfers before shutting down

- packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
- packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
- packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-openapi-validation-off-pkgs.test.ts
Added the new `openApiValidationOffPkgs` configuration parameter to the API
server. It accepts a list of package names for which OpenAPI validation should be disabled.
This is useful when dealing with plugins that have incorrect or incomplete
OpenAPI specifications or when there is a bug in the OpenAPI validator
middleware that cause it to have false negatives during validation.
This configuration parameter is optional and defaults to an empty array which means that
all of the plugins will have the OpenAPI request validation enabled by default.
As am example, setting this configuration parameter to
`["@hyperledger/cactus-plugin-ledger-connector-ethereum"]`
will disable OpenAPI validation for the Ethereum connector plugin
Fixes #3831 …
> feat(cmd-api-server): configurable OpenAPI HTTP request validation

- .github/workflows/.dast-nuclei-cmd-api-server.yaml
- packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
1. Fix the issue on plugin-ledger-connector-fabric that
throws an error when there is no sshConfig available.
Fixes #3671
> fix(dast): ccp, sshconfig missing

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/asset-transfer-private-data/chaincode-go/go.mod
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/fixtures/go/asset-transfer-private-data/chaincode-go/go.sum
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
Ran `go mod tidy` within the go chaincode directory of which the deploy
was failing:
`packages/cactus-plugin-ledger-connector-fabric/src/test/
typescript/fixtures/go/asset-transfer-private-data/chaincode-go/`
Also set `fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts` to be skipped
because it seems to have become flaky again. We have coverage for the same
functionality in other tests just not with the JS contract deployment
so it is not a big priority to have this test enabled. We expect most people
to use the Go/Typescript contracts anyway.
Fixes #3839 …
> test(fabric-connector): connector-fabric-baseline test is failing

- tools/custom-checks/check-dependency-version-consistency.ts
ci(custom-check): fix deps being inconsistent phase 1
1. Added web3 to the ignored dependency list as we are upgrading to viem instead
2. Updated the ignore package list to include the cacti-ledger-browser, cacti-plugin-consortium-static
Fixes #3684
> ci(custom-check): fix deps being inconsistent phase 1

- packages/cactus-test-tooling/src/main/typescript/common/containers.ts
- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- Added support for running the Fabric test ledger within a custom Docker network, enabling connections without requiring host network mode.
- It maintains support for host network mode configurations.
- Using the default configs would generate INVALID_ENDORSER_TRANSACTION.
Related issue: https://github.com/hyperledger-cacti/cacti/pull/3031
Previously, everything was bound to the host network. This worked for bare-metal testing, but any additional plugins running in separate containers also needed to communicate via localhost, which made containerized setups difficult to manage and unfeasible for isolated container environments.
> test(test-tooling): support for custom docker network

- packages/cacti-ledger-browser/src/main/sql/schema.sql
- packages/cactus-plugin-persistence-ethereum/src/main/sql/schema.sql
- packages/cactus-plugin-persistence-ethereum/src/test/typescript/integration/persistence-ethereum-postgresql-db-client.test.ts
- packages/cactus-plugin-persistence-fabric/src/main/sql/schema.sql
Primary Change:
* SQL schema
1. Enable RLS and set policy (Security Advisor, Type of Error)
2. Set RLS policy (Security Advisor, Type of Info)
3. Set search_path (Security Advisor, Type of Warning)
4. Set security_invoker (Security Advisor, Type of Error)
5. Reset GRANT of "ethereum.token_erc20" (Security Advisor, Type of Warning)
6. Remove duplicate index (Performance Advisor, Type of Warning)
7. Add public search path to use uuid_generate_v4()
* Test Code
1. Upgrade persistence-ethereum-postgresql-db-client.test PostgreSQL version
Fixes #3551
> fix(ledger-browser): supabase advisor errors and warnings

- .github/workflows/ci.yaml
- .taprc
- jest.config.js
- packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/openapi/openapi-validation.test.ts
test(htlc-eth-besu): migrate openapi-validation-endpoint test cases from Tape to Jest
```
packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/openapi/openapi-validation.test.ts
```
Fixes:#3808
Signed-off-by: Udhayakumari 62878965+Udhayakumari@users.noreply.github.com
> test(htlc-eth-besu): migrate openapi-validation-endpoint test cases from Tape to Jest

- packages/cactus-test-geth-ledger/src/main/typescript/geth-test-ledger.ts
- packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
- packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
- Added support for running the Besu and Ethereum test ledgers within a custom Docker network, enabling connections without requiring host network mode.
- Complement of https://github.com/hyperledger-cacti/cacti/pull/3871.
> test(test-tooling): support for custom docker network for besu and ethereum test networks

- packages/cacti-ledger-browser/src/main/typescript/apps/eth/components/AccountERC721View/NFTCard.tsx
- packages/cacti-ledger-browser/src/main/typescript/apps/eth/queries.ts
Primary Change:
* Query will select columns of 'nft_name', 'nft_description', 'nft_image'
* Display ERC721 metadata
1. Display 'nft_name' and 'nft_description'
2. Display 'nft_image'. If 'nft_image' can not be loaded, it will use default image
3. Delete the part of URL due to already displaying all the metadata from the URL
Fixes #3895 
> feat(ledger-browser): display new data about ERC721

- packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-dockerization.test.ts
- yarn.lock
> fix(satp-hermes): fix test
