.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/user-story-template.md
CODE-OF-CONDUCT.md
README.md

Signed-off-by: Hamilton <jonathan.m.hamilton@accenture.com>

Documentation Housekeeping

---

.github/ISSUE_TEMPLATE/user-story-template.md

Signed-off-by: Jonathan Hamilton <jonathan.m.hamilton@accenture.com>

Cleanup typo on #55

---

examples/simple-asset-transfer/quorum/api/package.json

fix(quorum/api): web3 patching typo

---

packages/connection-chain/README.md

feat(connection-chain): add readme, package dir

---

packages/core/examples/simple-asset-transfer/fabric/contracts/src/mycc/mycc.go
packages/core/examples/simple-asset-transfer/scenarios/share-pub-keys.js

This fixes https://github.com/hyperledger-labs/blockchain-integration-framework/issues/11

Avoid MVCC_READ_CONFLICT when adding public keys

---

packages/connection-chain/docs/REST-API/base/ecaccounts.md
packages/connection-chain/docs/REST-API/base/endchains.md
packages/connection-chain/docs/REST-API/sample/rules.md
packages/connection-chain/docs/REST-API/sample/transfers.md

Signed-off-by: takumat <takeuchi.takuma@fujitsu.com>

docs: add FUJITSU ConnectionChain-sample REST-API documents

---

CONTRIBUTING.md
README.md

Signed-off-by: Jonathan Hamilton <jonathan.m.hamilton@accenture.com>

docs: Resolves #17 with CONTRIBUTING.MD

---

packages/connection-chain/environment/base/cc_env/servers/appserver/serviceapi/bin/www
packages/connection-chain/environment/base/cc_env/servers/cooperation/coreSide/ec1_adapter/bin/www.js
packages/connection-chain/environment/base/cc_env/servers/cooperation/coreSide/ec2_adapter/bin/www.js
packages/connection-chain/environment/base/cc_env/servers/cooperation/ecSide/ec1_connector/bin/www.js
packages/connection-chain/environment/base/cc_env/servers/cooperation/ecSide/ec2_connector/bin/www.js
packages/connection-chain/environment/base/cc_env/servers/restserver/coreapi/bin/www

Signed-off-by: takeutak <takeuchi.takuma@fujitsu.com>

fix: add bin/www.js files on FUJITSU ConnectionChain-sample

---

.travis.yml
docs/tutorials/simple-asset-transfer.md
packages/core/.gitignore
packages/core/Vagrantfile
packages/core/tools/configure.sh

Script to add missing OS deps to run ci

---

packages/connection-chain/environment/base/cc_env/servers/appserver/serviceapi/package.json
packages/connection-chain/environment/base/cc_env/servers/cooperation/coreSide/ec1_adapter/package.json
packages/connection-chain/environment/base/cc_env/servers/cooperation/coreSide/ec2_adapter/package.json
packages/connection-chain/environment/base/cc_env/servers/cooperation/ecSide/ec1_connector/package.json
packages/connection-chain/environment/base/cc_env/servers/cooperation/ecSide/ec2_connector/package.json
packages/connection-chain/environment/base/cc_env/servers/restserver/coreapi/package.json

Signed-off-by: takeutak <takeuchi.takuma@fujitsu.com>

fix: morgan(v1.8.1 -> v1.9.1) on FUJITSU ConnectionChain-sample

---

.circleci/config.yml
packages/core/tools/ci.sh

fix(ci): run full CI suite on CircleCI

---

docs/feature-blockchain-migration.md
docs/use-story-blockchain-migration.md

Signed-off-by: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>

docs: add data migration feature proposal

---

packages/core/package.json

chore: cut release 0.2.0

---

.github/settings.yml
README.md

Add settings file

---

whitepaper/Makefile

docs(whitepaper): fix makefile and html+pdf toolchain

---

CONTRIBUTING.md

Partial of #46
As promised during our last call, there's checklists and git guidance

docs(contributing-md): PR checklist, git guidance

---

packages/cactus-test-tooling/package.json
packages/cactus-test-tooling/src/main/typescript/common/containers.ts
packages/cactus-test-tooling/src/main/typescript/http-echo/http-echo-container.ts
packages/cactus-test-tooling/src/main/typescript/public-api.ts
packages/cactus-test-tooling/src/test/typescript/integration/common/containers.test.ts

This can put and pull files to and from the file system of a running docker container.
cc: @sownak @jweate

test(test-tooling): add Containers utility class

---

whitepaper/whitepaper.md

Chapter 5: Identities, Authentication, Authorization is amended to clarify treatments on various IDs.
Signed-off-by: Shingo Fujimoto <shingo_fujimoto@fujitsu.com>

docs: white paper id spec

---

CONTRIBUTING.md

Add further instructions to create local branch on parallel working.
Signed-off-by: Shingo Fujimoto <shingo_fujimoto@fujitsu.com>

docs(contributing): create branch

---

whitepaper/whitepaper.md

Adding description about assumed bootstrap procedures to start Cactus application service.
This PR is submitted to resolve issue #198  .
Signed-off-by: Shingo Fujimoto <shingo_fujimoto@fujitsu.com>

docs(whitepaper): bootstraping Cactus application

---

CONTRIBUTING.md

Also talks about test case debugging
and some of our core principles
specific to test case development (not
to be confused with the design
principles of the project itself).
Also: Added a table of contents to the
CONTRIBUTING.md document as it is
now getting to a critical mass where it
is becoming to scan the whole
document without a TOC.
Fixes #187

docs(contributing-md): test automation/execution, SDK build

---

GOVERNANCE.md

docs(governance): due process for PRs in order of submission

---

whitepaper/whitepaper.md

This PR is submitted to resolve issue #178

docs(whitepaper): add API interface of Ledger-Plugin

---

BUILD.md

docs(build-md): add file to build project for contributors (not users)

---

CONTRIBUTING.md

docs(contributing): add directory structure

---

CONTRIBUTING.md

Also talks about the all in one docker images and
the classes that they use them.
Fixes #233

docs(contributing-md): ledger connector plugin test automation

---

packages/cactus-common/package-lock.json
packages/cactus-common/package.json
packages/cactus-common/src/main/typescript/js-object-signer.ts
packages/cactus-common/src/main/typescript/public-api.ts
packages/cactus-common/src/main/typescript/secp256k1-keys.ts
packages/cactus-common/src/main/typescript/signer-key-pair.ts
packages/cactus-common/src/test/typescript/unit/js-object-signer.test.ts
packages/cactus-common/src/test/typescript/unit/objects/get-all-method-names.ts

This PR resolve issue #136 
This PR depend on PR #245 and should only be merged after PR #245 merged.

feat(common): Stable Signature Generation from JS Objects

---

.gitignore

chore(gitignore): cactus-openapi-spec-*.json

---

packages/cactus-test-tooling/src/main/typescript/common/containers.ts

Helpers to list files under an arbitrary path in a container's file
system and a more generic method that helps executing shell
commands (exec())
Depends on #275

feat(test-tooling): Containers class ls() and exec() methods

---

CONTRIBUTING.md

docs(contributing-md): explain the importance of reproducible builds

---

commitlint.config.js
package.json

chore(commitlint): husky to run commitlint in pre-commit hooks

---

packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
packages/cactus-test-tooling/src/main/typescript/http-echo/http-echo-container.ts
packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts

Fixes #265
Signed-off-by: suyukuoacn <su-yu.kuo@accenture.com>

fix(test-tooling): getContainerInfo methods lookup criteria

---

codeql-analysis.yml

This is an automated security analysis tool.
Fixes #101

chore(security): add CodeQL analysis workflow

---

README.md

Responding to issue #306 
If these need updating, let me know!
Fixes #306
Edit from Peter: Added the `Fixes #306` line which will auto-close the issue once this PR is merged.

docs(readme): status badges for build, docs, license, etc. 

---

whitepaper/whitepaper.md

docs(whitepaper): update the section of Ledger Plugin API

---

whitepaper/whitepaper.md

This pull-request has already been approved as same as PR #322 #328 .
After the approval, some technical problem on GitHub happened and I built my fork again, so I requested the same pull-request again.  Would you mind if you approve my pull-request again?

docs(whitepaper): update the section of Ledger Plugin (fixed again)

---

packages/cactus-cmd-api-server/package.json

fix(cmd-api-server): bundle name typos

---

whitepaper/whitepaper.md

This PR is related with Issue #302 .

docs(whitepaper): revise API functions of Ledger Plugin

---

.gitignore
lerna.json
package-lock.json
package.json

Fixes #45 
Depends on #308 => meaning that #308 must be merged first prior to this getting merged.

chore: release automation

---

packages/ledger-plugin/fabric/validator/src/README.md
packages/ledger-plugin/fabric/validator/unit-test/README.md
packages/ledger-plugin/fabric/validator/unit-test/fabric-docker/README.md
packages/ledger-plugin/fabric/validator/unit-test/validatorDriver_signTransactionOffline.js
packages/ledger-plugin/go-ethereum/validator/src/README.md

This pull-request is related with Issue #385

fix(validator,example): fix bugs of sample code and README of validators

---

tools/docker/besu-all-in-one/supervisord.conf

This reverts commit f2219d95d85f589eb6aef97b547e2b78677315e8.
Fixes #399

fix(tools/docker/besu): all in one image RPC API CLI args

---

packages/cactus-cockpit/package.json
packages/cactus-cockpit/src/polyfills.ts

fix(cockpit): add missing process shim into polyfills

---

examples/cactus-example-supply-chain-backend/package.json
examples/cactus-example-supply-chain-business-logic-plugin/package.json
package.json
packages/cactus-api-client/package.json
packages/cactus-cmd-api-server/package.json
packages/cactus-common/package.json
packages/cactus-core-api/package.json
packages/cactus-core/package.json
packages/cactus-plugin-consortium-manual/package.json
packages/cactus-plugin-keychain-memory/package.json
packages/cactus-plugin-kv-storage-memory/package.json
packages/cactus-plugin-ledger-connector-besu/package.json
packages/cactus-plugin-ledger-connector-fabric/package.json
packages/cactus-plugin-ledger-connector-quorum/package.json
packages/cactus-plugin-validator-besu/package.json
packages/cactus-test-api-client/package.json
packages/cactus-test-cmd-api-server/package.json
packages/cactus-test-plugin-consortium-manual/package.json
packages/cactus-test-plugin-ledger-connector-quorum/package.json
packages/cactus-test-plugin-validator-besu/package.json
packages/cactus-test-tooling/package.json

```
build(webpack): no bundle generation by default …
Resolves hyperledger#390
```

build(webpack): no bundle generation by default

---

packages/cactus-cockpit/package-lock.json

------------------
**<ins>This PR includes the changes required to resolve the issue #432. Please read each point of the description below carefully!</ins>**
- Reviewing this one can be done as of right now as this PR is not dependent on any other PR.
- Feel free to ask @jagpreetsinghsasan via any of your preferred communication channels for help if you get stuck using the GitHub UI or any git features during the review.
----------------------------
chore(package-lock): update the package-lock.json
Primary change
--------------
1. Updated the package-lock.json file as an standalone commit, so it won't reflect in any other PR
Fixes #432
Fixes #432

chore(package-lock): update the package-lock.json

---

packages/cactus-common/package-lock.json
packages/cactus-common/package.json
packages/cactus-common/src/test/typescript/unit/api-surface.ts
packages/cactus-common/src/test/typescript/unit/bools.test.ts
packages/cactus-common/src/test/typescript/unit/checks.test.ts
packages/cactus-common/src/test/typescript/unit/coded-error.test.ts
packages/cactus-common/src/test/typescript/unit/logging/logger.test.ts
packages/cactus-common/src/test/typescript/unit/objects/get-all-field-names.test.ts
packages/cactus-common/src/test/typescript/unit/objects/get-all-method-names.test.ts
packages/cactus-common/src/test/typescript/unit/strings/drop-non-printable.test.ts
packages/cactus-common/src/test/typescript/unit/strings/is-string.test.ts
packages/cactus-common/src/test/typescript/unit/strings/replace-all.test.ts

test(common): increase test coverage

---

examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
packages/cactus-cmd-api-server/package.json
packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
packages/cactus-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
packages/cactus-core-api/src/main/typescript/plugin/plugin-aspect.ts
packages/cactus-core-api/src/main/typescript/public-api.ts
packages/cactus-core/src/main/typescript/plugin-registry.ts
packages/cactus-core/src/main/typescript/public-api.ts
packages/cactus-core/src/test/typescript/unit/plugin-registry.test.ts
packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.test.ts
packages/cactus-test-api-client/package.json
packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
packages/cactus-test-cmd-api-server/src/test/typescript/integration/runtime-plugin-imports.test.ts
packages/cactus-test-plugin-consortium-manual/package.json
packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/security-isolation-via-api-server-ports.ts
packages/cactus-test-plugin-ledger-connector-besu/package.json
packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/sign-transaction-endpoint.test.ts
packages/cactus-test-plugin-ledger-connector-quorum/package.json
packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-via-web-service.test.ts

**<ins>This PR depends on another [PR](https://github.com/hyperledger/cactus/pull/407) to ensure that the authors are not blocked in performing their work while waiting for the pull request to get reviewed. Please read the each point of the description below carefully!</ins>**
- It is strongly recommended that you review the parent PR first before reviewing this one because once that one (parent PR) is merged, this can be rebased onto the main branch which will literally disappear the additional commits that are shown in this PR but actually belong to the parent PR
- Before this one can be merged, #407 has to be approved and merged first.
- Reviewing this one can be done as of right now by looking at the changes made specifically by the single commit that this branch commits on top of the …

refactor(core-api): discontinue validator plugin aspect

---

examples/cartrade/README.md

fix(examples): fix README of cartrade

---

packages/jest.config.js
packages/ledger-plugin/VerifierBase.test.ts
packages/manual-of-auto-testing-codes.md
packages/package.json
packages/routing-interface/util/RIFUtil.test.ts
packages/routing-interface/util/RIFUtil.ts

This PR is related with Issue #443  .
Signed-off-by: Takuma TAKEUCHI takeuchi.takuma@fujitsu.com

feat(ci): add a sample of auto testing codes

---

.github/settings.yml

chore: Update default branch

---

examples/cactus-example-supply-chain-backend/package-lock.json
examples/cactus-example-supply-chain-backend/package.json
examples/cactus-example-supply-chain-business-logic-plugin/package-lock.json
examples/cactus-example-supply-chain-business-logic-plugin/package.json
packages/cactus-api-client/package-lock.json
packages/cactus-api-client/package.json
packages/cactus-plugin-consortium-manual/package-lock.json
packages/cactus-plugin-consortium-manual/package.json
packages/cactus-plugin-ledger-connector-fabric/package-lock.json
packages/cactus-test-api-client/package-lock.json
packages/cactus-test-api-client/package.json
packages/cactus-test-cmd-api-server/package-lock.json
packages/cactus-test-cmd-api-server/package.json
packages/cactus-test-plugin-consortium-manual/package-lock.json
packages/cactus-test-plugin-consortium-manual/package.json
packages/cactus-test-plugin-ledger-connector-besu/package-lock.json
packages/cactus-test-plugin-ledger-connector-besu/package.json
packages/cactus-test-plugin-ledger-connector-quorum/package-lock.json
packages/cactus-test-plugin-ledger-connector-quorum/package.json
packages/cactus-test-tooling/package-lock.json
packages/cactus-test-tooling/package.json

Done due to a high severity vulnerability
Fixes #449

build(deps): upgrade axios to 0.21.1

---

packages/cactus-test-tooling/src/main/typescript/common/containers.ts

Adds two utility functions to the class called Containers:
1. public static async waitForHealthCheck(containerId: string, timeoutMs: number = 180000): Promise<void>
Awaits until a container identified by the containerId
parameter becomes healthy.
2. public static async getById(containerId: string): Promise<ContainerInfo>
Utility method to obtain the ContainerInfo typed
object from the dockerode library that contains
the status information of the container among
other things.
Fixes #471
(cherry picked from commit f52626e268e732ced7441dafc1e9c75024aa4798)

feat(test-tooling): containers#getById and #waitForHealthCheck

---

examples/cactus-example-supply-chain-business-logic-plugin/src/main/json/openapi.json
packages/cactus-cmd-api-server/src/main/json/openapi.json
packages/cactus-core-api/src/main/json/openapi.json
packages/cactus-plugin-consortium-manual/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json

chore(license): add license object to OpenAPI specs

---

packages/cactus-core-api/src/main/typescript/plugin/keychain/i-plugin-keychain.ts
packages/cactus-plugin-keychain-memory/src/main/typescript/plugin-keychain-memory.ts
packages/cactus-plugin-keychain-memory/src/test/typescript/unit/plugin-keychain-memory.test.ts

Also remove the getEncryptionAlgorithm method.
Fixes #477

refactor(core-api): remove IPluginKeychain#rotateEncryptionKeys()

---

packages/cactus-plugin-keychain-vault/src/main/json/openapi.json

fix(keychain-vault): add missing license to openapi.json

---

whitepaper/cactus_arch.svg
whitepaper/whitepaper.md

whitepaper texts revised following given comments.
The architecture diagram is also updated to be aligned with revised texts.
This PR replaces closed PR#368

docs(whitepaper): updates on architecture diagram and terminology

---

docs/regulatory-and-industry-initiatives-reading-list.md

Special thanks to Eugenio Reggianini who
provided the initial set of links for this list via email.
Depends on #507 (CI won't pass without that)

docs(reading-lists): regulatory and industry standards initiatives

---

package-lock.json
package.json
webpack.dev.web.js
webpack.prod.web.js

fix: webpack 5 NodeJS polyfills for web GUI

---

packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/test/solidity/hello-world-contract/HelloWorld.json
packages/cactus-plugin-ledger-connector-besu/src/test/solidity/hello-world-contract/HelloWorld.sol
packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts

fix(connector-besu): avoid req.params repetition

---

packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts
packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts

fix(test-tooling): removed latest tag

---

README.md
examples/electricity-trade/README.md
examples/electricity-trade/script-build-all.sh
examples/electricity-trade/script-build-electricity-trade.sh
examples/electricity-trade/script-set-sawtooth-intkey.sh
examples/electricity-trade/script-start-electricity-trade.sh
examples/electricity-trade/script-start-ledgers.sh
examples/electricity-trade/script-start-validator-ethereum.sh
examples/electricity-trade/script-start-validator-sawtooth.sh
packages/ledger-plugin/sawtooth/validator/src/build/Dockerfile
packages/ledger-plugin/sawtooth/validator/src/copyStaticAssets.ts
packages/ledger-plugin/sawtooth/validator/src/copyUtilityAssets.ts
packages/ledger-plugin/sawtooth/validator/src/core/app.ts
packages/ledger-plugin/sawtooth/validator/src/core/bin/www.ts
packages/ledger-plugin/sawtooth/validator/src/core/config/default.ts
packages/ledger-plugin/sawtooth/validator/src/dependent/PluginConfig.ts
packages/ledger-plugin/sawtooth/validator/src/dependent/PluginUtil.ts
packages/ledger-plugin/sawtooth/validator/src/dependent/ServerMonitorPlugin.ts
packages/ledger-plugin/sawtooth/validator/src/dependent/ServerPlugin.ts
packages/ledger-plugin/sawtooth/validator/src/script-build-validator.sh
packages/ledger-plugin/sawtooth/validator/src/script-start-validator.sh
packages/ledger-plugin/sawtooth/validator/src/setup.sh
packages/script-build-packages.sh
packages/tsconfig.json

Related with Issue #589 
- Main contents: add README on example/electricity-trade and script files for setup
- Sub contents: fix copyrights etc.

refactor(example): add README on examples/electricity-trade

---

packages/cactus-api-client/src/test/typescript/integration/default-consortium-provider.test.ts

fix(api-client): flaky DefaultConsortiumProvider test #605

---

tools/docker/fabric-all-in-one/Dockerfile_v1.4.x
tools/docker/fabric-all-in-one/Dockerfile_v2.x
tools/docker/fabric-all-in-one/README.md

fix(tools): fabric all-in-one build cannot find rust compiler #617

---

packages/cactus-plugin-ledger-connector-besu/README.md
packages/cactus-plugin-ledger-connector-fabric/README.md
packages/cactus-plugin-ledger-connector-quorum/README.md
whitepaper/whitepaper.md

Resolve #343 
Updated the connectors readme files.

docs(whitepaper): updated readme files of connectors

---

examples/electricity-trade/README.md

fix(examples): fix some typo of README on examples/electricity-trade

---

packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts

fix(connector-quorum): ether value and query params added

---

packages/cactus-core-api/src/main/typescript/plugin/consortium/i-plugin-consortium.ts
packages/cactus-core-api/src/main/typescript/public-api.ts

feat(core-api): common consortium interface

---

packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.test.ts

feat(connector-besu): customizable nonce and gas

---

packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts

feat(connector-fabric): signing credentials for fabric

---

examples/cartrade/README.md
examples/electricity-trade/README.md

This pull-request is related with Issue #668

fix(example): fix bugs of README of examples/electricity-trade and examples/cartrade

---

packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/invoke-contract-endpoint-v2.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/web-services/invoke-contract-endpoint-v2.ts

feat(connector-besu): use contract instance map

---

packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.test.ts
packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/sign-transaction-endpoint.test.ts
packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-via-web-service.test.ts
packages/cactus-test-tooling/src/main/typescript/common/containers.ts
packages/cactus-test-tooling/src/main/typescript/github-actions/is-running-in-github-action.ts
packages/cactus-test-tooling/src/main/typescript/github-actions/prune-docker-all-if-github-action.ts
packages/cactus-test-tooling/src/main/typescript/public-api.ts

Depends on #697 
Depends on #695 
fix(ci): disk full issues on GitHub Action Workflow runner #698
Updates the test cases that use ledger containers to clean up
after themselves not just by stopping and deleting the containers
but by also doing a docker prune of the containers, images, networks
and volumes as well.
What we hope to accomplish here is that the GHA CI will stop
failing with disk full errors.
Fixes #698

fix(ci): disk full issues on GitHub Action Workflow runner #698

---

packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/invoke-contract-endpoint-v2.ts
packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/invoke-contract-v2.test.ts

Resolve #609 
Signed-off-by: AzaharaC <a.castano.benito@accenture.com>

refactor(connector-besu): common interface invoke-contract

---

packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/web-services/invoke-contract-endpoint-v2.ts
packages/cactus-plugin-ledger-connector-quorum/src/test/solidity/hello-world-contract/HelloWorld.json
packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/invoke-contract-v2.test.ts

Resolve #610 
Signed-off-by: AzaharaC <a.castano.benito@accenture.com>

refactor(connector-quorum): common interface invoke-contract

---

README.md

docs(readme): fix project name, link to sub-docs

---

packages/cactus-plugin-ledger-connector-corda/src/test/typescript/integration/jvm-kotlin-spring-server.test.ts

chore(connector-corda): fix typo in test assertion

chore(connector-corda): fix typo in test assertion

---

whitepaper/cactus_arch.svg

- related with Issue #737 
- contents:
- (bug fix) modify the typo ("regist o ry" -> "registry")
- (bug fix) add a white backscreen for make the diagram display on GitHub black screen

fix(whitepaper): fix cactus_arch.svg

---

docs/manual-of-auto-testing-codes.md
packages/ledger-plugin/fabric/validator/src/README.md
packages/ledger-plugin/go-ethereum/validator/src/README.md
packages/ledger-plugin/go-ethereum/validator/unit-test/README.md
packages/ledger-plugin/go-ethereum/validator/unit-test/geth-docker/README.md
tools/docker/fabric14-fabcar-testnet/README.md
tools/docker/geth-testnet/README.md
tools/docker/sawtooth-testnet/README.md
whitepaper/whitepaper.md

docs(ledger-plugin): fix some minor errors on documentation

---

examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-shipment-endpoint.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-shipment-endpoint.ts
packages/cactus-plugin-ledger-connector-fabric/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/plugin-ledger-connector-fabric.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/deploy-contract-go-bin-endpoint-v1/deploy-contract/deploy-cc-from-golang-source.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts

refactor(connector-fabric): common interface

---

packages/cactus-api-client/README.md

docs(api-client): finish writing the readme file #342

---

examples/cartrade/README.md
examples/electricity-trade/README.md
packages/package.json

fix(ledger-plugin): restore packages/package.json

---

packages/cactus-plugin-ledger-connector-fabric/package-lock.json
packages/cactus-plugin-ledger-connector-fabric/package.json

Depends on #581 
Date: 2021-03-29 16:27:52 -0700 
fix(connector-fabric): cve-2020-7774 Prototype Pollution high sev. #745
Attempt to get away with upgrading the fabric-network
dependency to the current latest 1.4.x which is 17.
Fingers crossed that this does not introduce other regressions.
Fixes #745

fix(connector-fabric): cve-2020-7774 Prototype Pollution high sev. #745

---

packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts

test(connector-besu): fix hardcoded test port #767

---

packages/cactus-cockpit/package-lock.json
packages/cactus-test-plugin-ledger-connector-besu/package-lock.json
packages/cactus-test-plugin-ledger-connector-besu/package.json

https://github.com/advisories/GHSA-p6mc-m468-83gw
CVE-2020-8203
low severity
Vulnerable versions: < 4.17.19
Patched version: 4.17.19
Versions of lodash prior to 4.17.19 are vulnerable to Prototype Pollution. The function zipObjectDeep allows a malicious user to modify the prototype of Object if the property identifiers are user-supplied. Being affected by this issue requires zipping objects based on user-provided property arrays.
This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to Denial of Service or Code Execution under specific circumstances.

fix(test): eliminate CVE-2020-8203 in besu connector test pkg

---

examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts

chore: linter fixes in supply chain example code

---

packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
tools/docker/test-npm-registry/Dockerfile
tools/docker/test-npm-registry/README.md
tools/docker/test-npm-registry/config.yaml

#810 
This is also tagged on DockerHub as
petermetz/cactus-test-npm-registry:1.0.0

feat(tools): add test-npm-registry container image

---

package-lock.json
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
packages/cactus-test-plugin-ledger-connector-besu/package-lock.json

chore(deps): npm audit fix 2021-04-16
Just ran npm audit fix against the
current main branch as of today.

chore(deps): npm audit fix 2021-04-16

---

packages/cactus-cmd-api-server/Dockerfile
packages/cactus-cmd-api-server/README.md
packages/cactus-cmd-api-server/healthcheck.sh

Tagged in DockerHub as a temporary measure (later will push to the
official Hyperledger Cactus repo as well):
petermetz/cactus-cmd-api-server:2021-04-18-fix-quorum-contract-types

feat(cmd-api-server): container image definition

---

packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-quorum/src/main/typescript/plugin-ledger-connector-quorum.ts
packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-from-json.test.ts

Resolve #743 
Depends on #731 
Depends on #702

feat(connector-besu, connector-quorum): contractAbi optional parameter

---

.devcontainer/Dockerfile
.devcontainer/README.md
.devcontainer/devcontainer.json
.devcontainer/library-scripts/common-debian.sh
.devcontainer/library-scripts/docker-in-docker-debian.sh

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>
**Added:**
- Devcontainer docker file
Resolve #504

docs: adding devcontainer docker file

---

packages/cactus-plugin-ledger-connector-fabric/Dockerfile
packages/cactus-plugin-ledger-connector-fabric/README.md

feat(connector-fabric): containerize-fabric

---

.gitignore
.vscode/extensions.json

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>
**Added**
- extensions.json file within the .vscode directory
**Updated**
- .gitignore file to allow extensions.json to be pushed to the repo
Resolve #863

docs(vscode): added extensions.json file with recommended extensions

---

FAQ.md
README.md

Fixes #853
cc: @hartm @RafaelAPB

docs(faq): bootstrapped FAQ.md document with name origins, watch script

---

package-lock.json
package.json
packages/cactus-cmd-api-server/src/test/resources/artillery/benchmark-script.yaml
packages/cactus-cmd-api-server/src/test/typescript/benchmark/artillery-api-benchmark.test.ts

This changes utilizes Artillery to load test our API endpoint. This is a first cut implementation.
BREAKING CHANGE: 🧨 Behaviors in a cloud environment is currently untested and could impact
CI pipeline.
Artillery works by sending HTTP requests at different intervals as defined in [benchmark-script.yaml](https://github.com/hyperledger/cactus/pull/845/files#diff-db633280d17272defd50724836cb82a91e5a6e23f040d8e261c5eb75a5d53382).
I've defined 3 phases, a warm up phase, a ramp up phase, and finally a phase imitating a sustained high load.
We can further define different scenarios, target endpoints, and user actions.
After running the test, Artillery produces a report in json format, which is read back in to pull out the metrics we need. We can then define a threshold, and write an assert to …

feat: incorporating load testing into our CI pipeline

---

whitepaper/whitepaper.md

fix(whitepaper): fix rendering

---

packages/cactus-plugin-ledger-connector-fabric/src/main/typescript/public-api.ts

Exports IPluginLedgerConnectorFabricOptions from the Fabric Connector public API 
cc @petermetz

fix(connector-fabric): export IPluginLedgerConnectorFabricOptions

---

docs/meta/guidelines-for-documentation-authors.md

docs(meta): guidelnies for documentation authors

---

packages/cactus-cmd-api-server/hooks/post_push

Adding a hook to publish this to the Hyperledger DockerHub repo.
Resolve #345

feat(api-server): publish API server docker image

---

examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-consortium-jws-endpoint-v1.ts
packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-node-jws-endpoint-v1.ts
packages/cactus-plugin-consortium-manual/src/main/typescript/plugin-consortium-manual.ts
packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts
packages/cactus-test-api-client/src/test/typescript/integration/api-client-routing-node-to-node.test.ts
packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/get-consortium-jws-endpoint.test.ts
packages/cactus-test-plugin-consortium-manual/src/test/typescript/integration/plugin-consortium-manual/security-isolation-via-api-server-ports.ts

refactor(consortium-manual): move logic from endpoint to plugin class

---

.github/workflows/dependent-issues.yml

There was a typo in the first fix I attempted so now fixing the fix here
(hopefully)

fix(github/workflows): dependent issues job name typo

---

packages/cactus-core-api/src/main/typescript/plugin/web-service/i-plugin-web-service.ts

chore(linter): fix warning in isIPluginWebService

---

packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts

Provide a method to retrieve the host port of the web socket JSON RPC
API exposed by the Besu AIO image backing the BesuTestLedger class. This
is a precursor to us adding support for the websocket transport in one
way or another (SocketIO != WebSockets in the strict sense of protocol
compatibility because SocketIO servers cannot be used by vanilla WS
applications out of the box)

feat: expose besu test ledger web socket API port

---

FAQ.md

docs(faq): port 0 binding explained

---

examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/typescript/business-logic-plugin/carbon-accounting-plugin.ts

fix(carbon-accounting): deleted incorrect plugin aspect

---

docs/source/index.rst
docs/source/packages.rst
docs/source/packages/cactus-api-client.md
docs/source/packages/cactus-cmd-api-server.md
docs/source/packages/cactus-common.md
docs/source/packages/cactus-core.md
docs/source/packages/cactus-plugin-consortium-manual.md
docs/source/packages/cactus-plugin-keychain-memory.md
docs/source/packages/cactus-plugin-keychain-vault.md
docs/source/packages/cactus-plugin-ledger-connector-besu.md
docs/source/packages/cactus-plugin-ledger-connector-corda.md
docs/source/packages/cactus-plugin-ledger-connector-fabric.md
docs/source/packages/cactus-plugin-ledger-connector-quorum.md
docs/source/packages/cactus-test-api-client.md
docs/source/packages/cactus-test-cmd-api-server.md
docs/source/packages/cactus-test-consortium-manual.md
docs/source/packages/cactus-test-plugin-ledger-connector-quorum.md
docs/source/packages/cactus-test-tooling.md

docs(readthedocsio): add packages readme files

---

FAQ.md

docs(faq): debugger and HTTP request serving

---

FAQ.md

docs(faq): internal watch failed: watch ENOSPC

---

packages/cactus-plugin-ledger-connector-corda/README.md

Depends on #940
Author Date: Fri May 07 2021 14:50:22 GMT-0700 (Pacific Daylight Time)
Committer Date: Fri May 07 2021 16:37:34 GMT-0700 (Pacific Daylight Time)	 
docs(connector-corda): how to write the JSON DSL #938
Add a dedicated section going into detail about the JSON DSL for
contract invocations.
This has come up on RC as something that's difficult for users to
figure out.
This covers the basics, there will be a more advanced version
of this in a follow-up commit later.
Fixes #938

docs(connector-corda): how to write the simple JSON DSL #938

---

packages/cactus-plugin-consortium-manual/src/main/json/openapi.json
packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-consortium-jws-endpoint-v1.ts
packages/cactus-plugin-consortium-manual/src/main/typescript/consortium/get-node-jws-endpoint-v1.ts
packages/cactus-plugin-consortium-manual/src/main/typescript/generated/openapi/typescript-axios/api.ts

refactor(core-api): get is replaced with post

---

BUILD.md
examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/typescript/business-logic-plugin/carbon-accounting-plugin.ts

docs(video): video guide added to build.md

---

packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts

fix(connector-besu): removed repeated check

---

.devcontainer/Dockerfile
.github/workflows/ci.yml
BUILD.md
examples/cactus-example-carbon-accounting-business-logic-plugin/package.json
examples/cactus-example-supply-chain-business-logic-plugin/package.json
examples/carbon-accounting/Dockerfile
examples/supply-chain-app/Dockerfile
packages/cactus-cmd-api-server/package.json
packages/cactus-core-api/package.json
packages/cactus-plugin-consortium-manual/package.json
packages/cactus-plugin-keychain-memory/package.json
packages/cactus-plugin-keychain-vault/package.json
packages/cactus-plugin-ledger-connector-besu/package.json
packages/cactus-plugin-ledger-connector-corda/package.json
packages/cactus-plugin-ledger-connector-fabric/package.json
packages/cactus-plugin-ledger-connector-quorum/package.json
packages/cactus-plugin-ledger-connector-xdai/package.json

JDK replaced by docker openapitool

---

tools/ci.sh

This is a workaround for the warnings that we've been getting
about the disk of the GHA runners being full. 
The trick is to delete the Android SDK and .NET from the runner
because we don't need any of those and it gives us a cozy 30 GB
extra space to play with which should be more than enough for
the foreseeable future.
The idea comes from:
https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150

ci: delete Android SDK, .NET in GitHub Action runners

---

packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/impl/ApiPluginLedgerConnectorCordaServiceImpl.kt
packages/cactus-plugin-ledger-connector-corda/src/main-server/kotlin/gen/kotlin-spring/src/main/kotlin/org/hyperledger/cactus/plugin/ledger/connector/corda/server/model/InvokeContractV1Response.kt
packages/cactus-plugin-ledger-connector-corda/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-corda/src/main/typescript/generated/openapi/typescript-axios/api.ts

Depends on #879
Author Date: Thu May 06 2021 19:17:42 GMT-0700 (Pacific Daylight Time)
Committer Date: Thu May 06 2021 19:26:50 GMT-0700 (Pacific Daylight Time) 
refactor(connector-corda): consolidate transaction invocation API #611
Fixes #611 

refactor(connector-corda): consolidate transaction invocation API #611

---

.readthedocs.yaml

fix(readthedocs): updated readthedocs file

---

examples/cactus-example-supply-chain-backend/src/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.ts
examples/cactus-example-supply-chain-backend/src/main/typescript/public-api.ts
examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app-cli.ts
examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts
examples/cactus-example-supply-chain-backend/src/test/typescript/integration/supply-chain-backend-api-calls.test.ts
examples/cactus-example-supply-chain-backend/src/test/typescript/integration/supply-chain-cli-via-npm-script.test.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/supply-chain-cactus-plugin.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-shipment-endpoint.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-shipment-endpoint.ts

A cosmetic change that helps people identify whata re test files and are
main source files since Visual Studio Code has this feature
that it highlights .test.ts files with a different icon in its
file explorer.

refactor(supply-chain-backend): .test.ts suffix for api-surface tests

---

examples/electricity-trade/README.md
examples/electricity-trade/cleanup.sh

Signed-off-by: Konstantin Rybalko <konstantin.rybalko@gmail.com>

Fixed cleanup.sh script according to the requirements, squashed to a single commit.

---

tools/docker/iroha-testnet/example/iroha-wallet/setup-iroha-wallet.sh

feat(iroha-testnet): Add REJECT check for transactions to setup-iroha-wallet.sh script in iroha-testnet
Signed-off-by: Takeshi Yonezu <tkyonezu@gmail.com>

feat(iroha-testnet): Add REJECT check for transactions to setup-iroha-wallet.sh script in iroha-testnet

---

packages/cactus-test-tooling/src/main/typescript/i-test-ledger.ts

Signed-off-by: Jeffrey Ushry <jeffrey.ushry@accenture.com>

style(test-tooling): linter fix  i test ledger

---

examples/cactus-example-supply-chain-frontend/src/app/shipment/shipment-detail/shipment-detail.page.ts

I hope it works! For some reason I can't seem to find the reviewer section of this page (bad news); I don't think this will hurt too much if I post it as a draft and also ping you @petermetz 

style(linter): shipment-detail page linter fix

---

examples/cactus-example-carbon-accounting-backend/example-config.json
examples/cactus-example-carbon-accounting-backend/package.json
examples/cactus-example-carbon-accounting-backend/src/main/typescript/carbon-accounting-app.ts
examples/cactus-example-carbon-accounting-backend/src/main/typescript/infrastructure/carbon-accounting-app-dummy-infrastructure.ts
examples/cactus-example-carbon-accounting-backend/src/utility-emissions-channel/typescript/src/index.ts
package.json

- Fixed Typos with logLevel
- Fixed fabric chaincode deployment error
Signed-off-by: Pritam Singh <pkspritam16@gmail.com>

docs(examples): fix typos and backend build

---

packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-balance.test.ts

@petermetz just pinging you because I don't have a reviewer section 😢

feat(connector-besu): add get balance method

---

packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-balance-endpoint.ts
packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-balance.test.ts
packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-balance-endpoint.test.ts

Fixes #1066
@petermetz Mr.Tyler helped me with the test cases!

feat(connector-besu): add getBalance web service

---

BUILD.md
CONTRIBUTING.md

add node tap --ts flag to docs

---

packages/cactus-plugin-ledger-connector-besu/package-lock.json
packages/cactus-plugin-ledger-connector-besu/package.json
packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-past-logs.test.ts

Signed-off-by: Hana Awad <awadhana0825@gmail.com>

feat(connector-besu): add get past logs method

---

packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-transaction-endpoint.ts
packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-transaction-endpoint.test.ts

Signed-off-by: Jeffrey Ushry <jeffrey.ushry@accenture.com>

feat(connector-besu): add getTransaction web service

---

packages/business-logic-plugin/BusinessLogicBase.ts

Signed-off-by: jsjs026 <jasonhack518@gmail.com>

fix(typo): fix typo of issue1053

---

packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
packages/cactus-plugin-ledger-connector-besu/src/main/typescript/web-services/get-past-logs-endpoint.ts
packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-past-logs-endpoint.test.ts

feat(connector-besu): add getPastLogs web service

---

examples/cactus-example-supply-chain-business-logic-plugin/src/main/json/openapi.json
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bamboo-harvest-endpoint-constants.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bamboo-harvest-endpoint.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bookshelf-endpoint-constants.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/insert-bookshelf-endpoint.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bamboo-harvest-endpoint-constants.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bamboo-harvest-endpoint.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bookshelf-endpoint-constants.ts
examples/cactus-example-supply-chain-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/list-bookshelf-endpoint.ts

Fixes #1120
@petermetz ping for review :)

docs(examples): supply chain- eliminate endpoint constant classes

---

package.json
tools/ci.sh
tools/custom-checks/check-open-api-json-specs.ts
tools/custom-checks/has-property.ts
tools/custom-checks/is-std-lib-record.ts
tools/custom-checks/run-custom-checks.ts

Ensures that openapi.json files "x-hyperledger-cactus"
extensions do not contain common mistakes in them due to
typos or just forgetting to specify certain mandatory
properties.
Fixes #489

build(tools): script to check OAS extensions #489

---

packages/cactus-common/src/main/typescript/js-object-signer.ts
packages/cactus-common/src/test/typescript/unit/js-object-signer.test.ts

Made all "any" types either explicit or unknown (where possible)
Allowed for private keys to be passed as either byte arrays (Buffer falls under this too) or strings
Resolves #1338

style(js-object-signer): removed all "unexpected any" types

---

docs/source/regulatory-and-industry-initiatives-reading-list.md

Also added latest business best practices doc link
Previous link was to an an announcement of the doc rather than the doc itself, and was also an outdated version

docs(reading-list): update BAFT DLPC doc to latest

---

docs/source/support.rst

docs(connector-iroha): add Iroha menu item in the ledger support matrix

---

packages/cactus-plugin-ledger-connector-iroha/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/openapi/openapi-validation.test.ts
packages/cactus-test-tooling/src/test/typescript/integration/iroha/iroha-test-ledger/constructor-validates-options.test.ts

Includes test for endpoint runTransactionV1
with test cases:
- Right request
- Request including an invalid parameter
- Request without a required parameter
Closes #1331
Related with #847

fix: openapi validation test for iroha plugin

---

tools/generate-api-server-config.js

docs(tools): fix/migrate example config generator to ESM

---

package.json
yarn.lock

chore(deps): upgrade @openapitools/openapi-generator-cli to latest

---

BUILD.md
packages/cactus-cmd-api-server/src/main/typescript/api-server.ts
packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
packages/cactus-test-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/deploy-contract-via-web-service.test.ts

fix(cmd-api-server): cockpit off by default #1239

---

packages/cactus-cmd-socketio-server/package.json
packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/util/ConfigUtil.ts
packages/cactus-cmd-socketio-server/src/main/typescript/verifier/DriverCommon.ts
packages/cactus-cmd-socketio-server/src/main/typescript/verifier/Verifier.ts
packages/cactus-cmd-socketio-server/src/main/typescript/verifier/VerifierAuthentication.ts

Fix warnings triggered by the strict flag, format the code according to
cactus/.prettierrc.js, minor fixes (mostly in log writing), dependency
injection for VerifierAuthentication.verify.
Closes: #1573

refactor(cmd-socketio-server): cmd-socketio-server Verifier test adjustments

---

.taprc
jest.config.js
packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts

File Path:
packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts
This is a PARTIAL resolution to issue #238 

test: jestify deploy-contract-from-json-xdai test

---

.taprc
jest.config.js
packages/cactus-common/src/test/typescript/unit/strings/is-string.test.ts

File Path:
packages/cactus-common/src/test/typescript/unit/strings/is-string.test.ts

test: jestify is-string test

---

.taprc
jest.config.js
packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/invoke-contract-xdai.test.ts

File Path:
packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/invoke-contract-xdai.test.ts

test: jestify invoke contract xdai test

---

.taprc
jest.config.js
packages/cactus-plugin-consortium-manual/src/test/typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts

File Path:
packages/cactus-plugin-consortium-manual/src/test/
typescript/unit/consortium/get-node-jws-endpoint-v1.test.ts

test: jestify get-node-jws-endpoint-v1 test

---

.taprc
jest.config.js
packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint.test.ts

File Path:
packages/cactus-test-plugin-htlc-eth-besu/
src/test/typescript/integration/
plugin-htlc-eth-besu/get-status-endpoint.test.ts

test: jestify test-plugin-htlc-eth-besu get-status-endpoint test

---

.taprc
jest.config.js
packages/cactus-core/src/test/typescript/unit/plugin-registry.test.ts

File Path:
packages/cactus-core/src/test/typescript/unit/plugin-registry.test.ts

test: jestify plugin-registry test

---

packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/openapi/openapi-validation.test.ts

style: 2021-09-20 linter warnings batch 20 / 26 
changes made in assigned lines 191-200

style: 2021-09-20 linter warnings batch 20 / 26 #1369

---

BUILD.md
CONTRIBUTING.md

fixes: #1792
Previous PR has been dropped off and cannot be reopened.
For reference, conversations about this PR is at #1795 

docs: changes to BUILD.md and CONTRIBUTING.md #1792

---

packages/cactus-common/src/test/typescript/unit/js-object-signer.test.ts

Fixes #1833
Depends on #1686 (The jestification PR)

test(common): fix assertion of signature equality

---

packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts

style(test-tooling): fix unexpected any quorum test ledger destroy

---

packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts

style(test-tooling): fix unexpected any quorum test ledger start

---

packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint-invalid.test.ts

test: fix htlc eth besu initialize-endpoint-invalid

---

examples/cactus-check-connection-ethereum-validator/BusinessLogicCheckEthereumValidator.ts
examples/cactus-check-connection-ethereum-validator/README.MD
examples/cactus-check-connection-ethereum-validator/RequestInfo.ts
examples/cactus-check-connection-ethereum-validator/TestEthereumBalance.ts
examples/cactus-check-connection-ethereum-validator/check-ethereum-validator.ts
examples/cactus-check-connection-ethereum-validator/config/BLP_config.ts
examples/cactus-check-connection-ethereum-validator/config/default.yaml
examples/cactus-check-connection-ethereum-validator/config/usersetting.yaml
examples/cactus-check-connection-ethereum-validator/copyBLPConfig.ts
examples/cactus-check-connection-ethereum-validator/copyStaticAssets.ts
examples/cactus-check-connection-ethereum-validator/package.json
examples/cactus-check-connection-ethereum-validator/replaceBLPConfigPath.ts
examples/cactus-check-connection-ethereum-validator/src/test/typescript/integration/check-connection-to-ledger.test.ts
examples/cactus-check-connection-ethereum-validator/tsconfig.json
jest.config.js
packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/TransactionManagement.ts

Add BLP that checks connectivity between ethereum ledger and connector
Closes: #1628
Signed-off-by: stepniowskip <piotr.stepniowski@fujitsu.com>

test: ethereum BLP with connectivity check

---

examples/discounted-cartrade/trades.ts
examples/electricity-trade/electricity-trade.ts
examples/test-run-transaction/test-run-transaction.ts
packages/cactus-cmd-socketio-server/package.json
packages/cactus-cmd-socketio-server/src/main/typescript/business-logic-plugin/BusinessLogicBase.ts
packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/CactusSocketIOServer.ts
packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/RequestInfo.ts
packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/TransactionManagement.ts
packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/routes/login.ts
packages/cactus-cmd-socketio-server/src/main/typescript/routing-interface/util/RIFUtil.test.ts
packages/cactus-cmd-socketio-server/src/main/typescript/util/TransactionSigner.ts
packages/cactus-cmd-socketio-server/tsconfig.json
yarn.lock

cmd-socketio-server will compile with global strict flag.
Part of https://github.com/hyperledger/cactus/issues/1671

refactor(cmd-socketio): fix strict flag warnings

---

packages/cactus-test-tooling/src/main/typescript/besu/besu-test-ledger.ts
packages/cactus-test-tooling/src/main/typescript/cactus-keychain-vault-server/cactus-keychain-vault-server.ts
packages/cactus-test-tooling/src/main/typescript/common/streams.ts
packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts

This is the recreation of PR of #1779
Reason for this new PR:
The previous repo was deleted.

style: 2021-09-20 linter warnings batch 23/26 fixes: #1371

---

BUILD.md
CONTRIBUTING.md
tools/generate-api-server-config.js

-add mention to test running via interface
-explain in more detail the docker requirement
-fix small bug preventing the correct execution of generate-api-server
cc @petermetz

docs: minor tweaks

---

FAQ.md

Description of the installation process for Apple M1 processors.

docs(faq): add instructions to install in Apple M1 processor (ARM-based)

---

examples/discounted-cartrade/package.json
packages-python/cactus_validator_socketio_indy/Dockerfile
packages-python/cactus_validator_socketio_indy/README.md
packages-python/cactus_validator_socketio_indy/post_install_script.py
packages-python/cactus_validator_socketio_indy/setup.py
packages-python/cactus_validator_socketio_indy/setup_indy.sh
packages-python/cactus_validator_socketio_indy/validator-python/validator_socketio_module/Settings.py

This refactor consists of creating pip package with validator to
install, instead of straight copying validator files while creating
docker image.
Closes: #1906
Signed-off-by: stepniowskip <piotr.stepniowski@fujitsu.com>

refactor: python pip package with indy validator

---

package.json
yarn.lock

fix(security): ensure ansi-html > 0.0.8 - CVE-2021-23424

---

.yarnrc
package.json
packages/cactus-cmd-api-server/Dockerfile
packages/cactus-plugin-ledger-connector-besu/Dockerfile
packages/cactus-plugin-ledger-connector-fabric/Dockerfile

fix(security): upgrade to yarn > 1.22.0 - CVE-2019-10773, CVE-2020-8131

---

.github/workflows/.dast-nuclei-cmd-api-server.yaml
.nuclei-config.yaml

ci: add fuzzer tests for our APIs

---

extensions/cactus-plugin-object-store-ipfs/README.md

Added some instructions for the usage of the package `plugin-object-store-ipfs` in the README.md.

docs(plugin-object-store-ipfs): added README.md description

---

docs/htlc-coordinator-alice-flow.md
docs/htlc-coordinator-bob-flow.md

docs(htlc-coordinator): added the flow diagram

---

packages/cactus-plugin-keychain-azure-kv/package.json
packages/cactus-plugin-keychain-azure-kv/src/main/json/openapi.json
packages/cactus-plugin-keychain-azure-kv/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-keychain-azure-kv/src/main/typescript/plugin-factory-keychain.ts
packages/cactus-plugin-keychain-azure-kv/src/main/typescript/plugin-keychain-azure-kv.ts
packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/delete-keychain-entry-endpoint.ts
packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/get-keychain-entry-endpoint.ts
packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/has-keychain-entry-endpoint.ts
packages/cactus-plugin-keychain-azure-kv/src/main/typescript/web-services/set-keychain-entry-endpoint.ts
packages/cactus-plugin-keychain-azure-kv/src/test/typescript/integration/plugin-keychain-azure-kv.test.ts

feat(keychain-azure-kv): complete request handler and endpoints #1010

---

whitepaper/whitepaper.md

Our whitepaper, the first point of contact from enterprises and individuals alike, is very outdated (for more than two years, it received no updates).  An outdated whitepaper brings a lot of confusion to newcomers, as 1) it doesn' reflect updated work done on blockchain interoperability, 2) doesn't reflect the current status of the code, and 3) doesn't reflect future plans for the project
These problems have been and continue to hamper the adoption of Hyperledger Cacuts.
I'm putting together an effort to update the whitepaper, with an initial focus on the abstract, introduction, and theoretical models (non-formal) for interoperability (based on [our recent research](https://www.techrxiv.org/articles/preprint/Do_You_Need_a_Distributed_Ledger_Technology_Interoperability_Solution_/18786527/1) …

docs(whitepaper): update abstract, introduction, interop. model

---

whitepaper/whitepaper.md

Split documentation that @petermetz asked for in the comments of PR #1810 

docs: add descriptions of ledgers in whitepaper

---

BUILD.md

docs: add link and image of jdk 8 install to build.md 

---

package.json
yarn.lock

fix: custom-checks script from package.json does not work #1809

---

README.md

docs(readme): add missing inclusive language statement

---

.github/workflows/.dast-nuclei-cmd-api-server.yaml
packages/cactus-plugin-ledger-connector-fabric/README.md

ci(connector-fabric): include endpoints in the fuzzer tests
Primary changes
----------------------
1. Updated the gitworkflow to include the fabric connector plugin endpoint
2. Updated the fabric connector plugin README.md for minor fixes
Fixes #1952

ci(connector-fabric): include endpoints in the fuzzer tests 

---

.github/workflows/semantic-pull-request.yaml

ci: add yaml workflow file for semantic-pull-request action

---

.github/workflows/.dast-nuclei-cmd-api-server.yaml
packages/cactus-plugin-ledger-connector-besu/README.md

ci(connector-besu): include endpoints in fuzzer tests 
--------------
1. Updated the git workflow to include the besu connector plugin endpoint
2. Added the task to run Besu all-in-one image
as a valid ws endpoint is required for connector to initialize
3. Updated the besu connector plugin README.md for minor fixes
Fixes #1949

ci(connector-besu): include endpoints in fuzzer tests

---

packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts

All I did was change from `test.skip` to just `test` and it turns out that the test works just fine. So for I've ran the test 20 times and it has passed every single time. This issue is a "fix" to #1957 ?

test(connector-iroha): tested previously skipped test

---

whitepaper/whitepaper.md

Just fixed some typos within the `whitepapers.md`, nothing too fancy!

docs: fixed typos within whitepaper

---

.devcontainer/Dockerfile
.github/workflows/ci.yml
BUILD.md

ci: bump NodeJS v14 and v16 minor versions to latest

---

packages/cactus-plugin-odap-hermes/README.md
packages/cactus-plugin-odap-hermes/src/main/json/openapi.json
packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/client/transfer-initialization.ts
packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/plugin-odap-gateway.ts
packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/recovery/recover-update.ts
packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/recovery/recover.ts
packages/cactus-plugin-odap-hermes/src/main/typescript/gateway/server/transfer-initialization.ts
packages/cactus-plugin-odap-hermes/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/integration/backup-gateway-after-client-crash.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/integration/client-crash-after-delete-asset.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/integration/client-crash-after-lock-asset.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/integration/client-crash-after-transfer-initiation.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/integration/odap-api-call-with-ledger-connector.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/integration/odap-api-call.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/integration/odap-rollback.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/integration/odap.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/integration/server-crash-after-transfer-initiation.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/make-checks.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/unit/client/transfer-initialization.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/unit/recovery/recover-update.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/unit/recovery/recover.test.ts
packages/cactus-plugin-odap-hermes/src/test/typescript/unit/server/transfer-initialization.test.ts

* Addition of backup gateways allowed field
* New test where a backup gateway is allowed to replace one that crashed

feat(odap-plugin): backup gateway implementation

---

packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-xdai/src/main/json/openapi.json

fix(security): close DDoS vulnerability in eth tx consistenty strategy

---

.github/workflows/ci.yml
examples/cactus-example-discounted-asset-trade/balance-management.ts
examples/cactus-example-discounted-asset-trade/balance.ts
examples/cactus-example-discounted-asset-trade/business-logic-asset-trade.ts
examples/cactus-example-discounted-asset-trade/business-logic-inquire-asset-trade-status.ts
examples/cactus-example-discounted-asset-trade/fabric-asset-management.ts
examples/cactus-example-discounted-asset-trade/fabric-asset.ts
examples/cactus-example-discounted-asset-trade/template-trade-management.ts
examples/cactus-example-discounted-asset-trade/template-trade.ts
examples/cactus-example-discounted-asset-trade/trades.ts
examples/cactus-example-discounted-asset-trade/transaction-ethereum.ts
examples/cactus-example-discounted-asset-trade/transaction-fabric.ts
examples/cactus-example-discounted-asset-trade/transaction-indy.ts
examples/cactus-example-discounted-asset-trade/transaction-info-management.ts
examples/cactus-example-discounted-asset-trade/transaction-info.ts
examples/cactus-example-discounted-asset-trade/www.ts
examples/cactus-example-electricity-trade/BalanceManagement.ts
examples/cactus-example-electricity-trade/BusinessLogicElectricityTrade.ts
examples/cactus-example-electricity-trade/MeterManagement.ts
examples/cactus-example-electricity-trade/README.md
examples/cactus-example-electricity-trade/TransactionEthereum.ts
examples/cactus-example-electricity-trade/balance.ts
examples/cactus-example-electricity-trade/electricity-trade.ts
examples/cactus-example-electricity-trade/www.ts
packages/cactus-cmd-socketio-server/package.json

- Rename package name and all it's occurances to match directory name.
Closes #2105

chore(cmd-socketio-server): rename package to match directory name

---

packages/cactus-plugin-ledger-connector-besu/Dockerfile

refactor(connector-besu): update base image to fix npm vulnerabilities

---

packages/cactus-plugin-ledger-connector-iroha/src/main/json/openapi.json
packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/generated/openapi/typescript-axios/api.ts
packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/plugin-ledger-connector-iroha.ts
packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts

Fixes: [#1253](https://github.com/hyperledger/cactus/issues/1253)
Signed-off-by: yashrajdesai <yashrajdesai30@gmail.com>

feat(connector-iroha): add dynamic request params

---

.github/containerscan/allowedlist.yaml
tools/docker/besu-all-in-one/Dockerfile

Signed-off-by: charelle <charelle.wrk@gmail.com>

fix(security): vulnerabilities found in besu-all-in-one #2055

---

package.json
packages/cactus-plugin-ledger-connector-iroha/package.json
packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/iroha-sign-utils.ts
packages/cactus-plugin-ledger-connector-iroha/src/main/typescript/plugin-ledger-connector-iroha.ts
packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/generate-and-send-signed-transaction.test.ts
packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/iroha-iroha-transfer-example.test.ts
packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/openapi/openapi-validation.test.ts
packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts

cactus-iroha plugin updated with the latest iroha-js library.

feat(connector-iroha): update-iroha-js

---

packages/cactus-plugin-odap-hermes/README.md

Following the merge of  #2154 this is the update of the README
* update the sequence diagram
* update the calls to create a gateway based on the new options of these classes

docs(odap-plugin): update odap plugin doc

---

packages/cactus-cmd-api-server/README.md
packages/cactus-plugin-ledger-connector-iroha/Dockerfile
packages/cactus-plugin-ledger-connector-iroha/README.md
packages/cactus-plugin-ledger-connector-iroha/package.json

----------------------------------
fix(plugin-ledger-connector-iroha): running dockerfile locally  
1. Updated iroha package.json to include a missing dependency
2. Updated Dockerfile to include new api-server image and
used yarn to install the iroha package
3. Updated README.md to include the newly changes to both
the api-server as well as iroha connector plugin
4. Updated cmd-api-server README.md to include similar
changes
Fixes #1874

fix(plugin-ledger-connector-iroha): running dockerfile locally

---

tools/docker/test-npm-registry/Dockerfile

fix(security): vulnerabilities found in test-npm-registry

---

.github/workflows/all-nodejs-packages-publish.yaml
.github/workflows/semantic-pull-request.yaml

Update Semantic PR to version 5

ci: set username and email for NPM

---

examples/cactus-example-carbon-accounting-backend/src/utility-emissions-channel/typescript/src/index.ts
examples/cactus-example-carbon-accounting-backend/src/utility-emissions-channel/typescript/src/lib/emissionsRecordContract.ts
examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/typescript/business-logic-plugin/web-services/dao-token/get-allowance-endpoint.ts
packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts

Some of the fixes were updated by Peter after Alec's internship has
come to an end before he could finish the requested changes.
Signed-off-by: Alec Phong <alecphong@gmail.com>
Partial solution #1375

style: remediate linter errors in examples and test-tooling

---

.github/workflows/publish-npm.yaml

chore: manually publish NPM

---

.github/settings.yml

chore: update settings to rename

---

tools/docker/fabric-all-in-one/Dockerfile_v1.4.x

fix(security): vulnerabilities found in fabric-all-in-one

---

BUILD.md
package.json

Fixes #2238
Signed-off-by: charellesandig [charelle.wrk@gmail.com](mailto:charelle.wrk@gmail.com)

build(yarn): migrate to CorePack

---

packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/rust/gen/Cargo.lock
packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/rust/gen/Cargo.toml
packages/cactus-plugin-keychain-vault/src/cactus-keychain-vault-server/rust/gen/examples/server/server.rs

feat(openssl): version upgrade to v0.10.48 in cactus-plugin-keychain-vault

---

.github/workflows/weaver_deploy_corda-pkgs.yml
.github/workflows/weaver_deploy_go-pkgs.yml
.github/workflows/weaver_deploy_node-pkgs.yml
.github/workflows/weaver_deploy_relay-server.yml

Fixes:
1. Go publish workflows: Correct the tagnames
2. Node workflows: fix typo in package.json after changing version (removed changing version in worklow)
3. Fix a typo in relay deployment workflow

fix(ci): multiple bug fixes in weaver deployment workflows

---

.cspell.json
examples/cactus-check-connection-ethereum-validator/package.json
package.json
tools/custom-checks/check-pkg-npm-scope.ts
tools/custom-checks/run-custom-checks.ts
tools/get-package-info-list.js
yarn.lock

chore: fix package.json#name properties to have scope and project name

---

packages/cactus-cmd-api-server/package.json
packages/cactus-cmd-api-server/src/test/typescript/benchmark/artillery-api-benchmark.test.ts
yarn.lock

build(cmd-api-server): upgrade to Artillery v2.x or migrate to loadtest

---

package.json
packages/cactus-test-tooling/package.json
yarn.lock

build(deps): clean up unused karma browser testing dependencies/files

---

tools/custom-checks/check-package-json-sort.ts
tools/custom-checks/check-sibling-dep-version-consistency.ts

build(tools): fix tooling globs where cactus is hardcoded

---

yarn.lock

docs(examples): fix CVE-2022-25858 - Terser insecure regular expression ReDoS

---

packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts

The linter warning was fixed with Record<string, unknown> and the types inside the function have been corrected.
The other 7 lines are just linter-errors for empty spaces, that where corrected, although that was not part of the issue, i hope it was ok.
[skip ci]
Closes: #2678

style: fixes Unexpected any linter W in getHelpText()

---

RELEASE_MANAGEMENT.md

Fixes #2336
[skip ci]
[skip ci]

docs(release): add RELEASE_MANAGEMENT.md file

---

README-cactus.md
README.md
docs-cactus/README.md
docs/docs/blog/2021-01-21-cross-chain-asset.md
docs/docs/blog/2021-01-21-emergence-enterprise-interoperability.md
docs/docs/blog/2022-11-07-introducing-hyperledger-cacti.md
docs/docs/blog/2023-10-03-hyperledger-cacti-graduation.md
docs/mkdocs.yml
weaver/README.md

- Updated README files to add current info and update links to point to the newly published integrated documentation (https://hyperledger.github.io/cacti/)
- Added a blog entries section to the documentation website.
[ ] Follow the Commit Linting specification. …

docs(README): updated README files to reflect recent documentation upgrades

---

.github/workflows/.dast-nuclei-cmd-api-server.yaml

Fixes #2590
[ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information.
[ ] Pull Request Title and Commit Subject must not exceed 72 …

ci(dast-nuclei): fix Could not run nuclei: no valid templates were found

---

docs/docs/cactus/packages/cactus-api-client.md
docs/docs/cactus/packages/cactus-cmd-api-server.md
docs/docs/cactus/packages/cactus-plugin-consortium-manual.md
docs/docs/cactus/packages/cactus-plugin-keychain-vault.md
docs/docs/cactus/packages/cactus-plugin-ledger-connector-besu.md
docs/docs/weaver/architecture-and-design/drivers.md
docs/docs/weaver/architecture-and-design/weaver-dapps.md

[skip ci]
Signed-off-by: GoodDaisy <90915921+GoodDaisy@users.noreply.github.com>

docs(weaver, cactus): fix typos

---

packages/cactus-test-plugin-ledger-connector-besu/README.md

Added missing readme file for the test package. It doesn't do much but
it does explain the core concept behind the package and that it is not
something that can/should be used for production deployments.
Fixes #834
[ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for …

docs(cactus-test-plugin-ledger-connector-besu): add README.md file

---

CODEOWNERS
MAINTAINERS.md

Congratulations @outSH! You are now a maintainer of the project.
[skip ci]
[ ] Follow the Commit Linting specification. You may refer to this …

docs(maintainers): add outSH as a maintainer to the project

---

examples/cactus-example-cbdc-bridging-frontend/package.json

1. Updated the version accordingly.
2. This pull request must be merged before we issue the 2.0.0 release
otherwise the npm package version will be broken on the public registry.
[skip ci]
Fixes #2874

docs(examples): fix cbdc-bridging-frontend/package.json version 2.0.0-alpha.2

---

.github/workflows/test_weaver-asset-exchange-besu.yaml
examples/cactus-example-cbdc-bridging-frontend/package.json
yarn.lock

1. License is now Apache-2.0
2. The package.json file is now sorted (following all the others)
3. The package name matches the pattern of all the other ones.
Fixes #2957

docs(cbdc-bridging-frontend): fix license, manifest sort, pkg name

---

.github/workflows/ci.yaml
.github/workflows/test_weaver-asset-exchange-besu.yaml
.github/workflows/test_weaver-corda-interop-app.yaml
.github/workflows/test_weaver-docker-build.yaml
.github/workflows/test_weaver-go.yaml
.github/workflows/test_weaver-node-pkgs.yaml
.github/workflows/test_weaver-relay.yaml

1. Adds a few static diff checking steps to the ci.yaml file so that
some of the biggest packages (based on test suite size) only get their
tests executed if their own or their dependencies' source code has changed.
2. Right now, for the affected packages this has equivalent effect as if
we had already implemented the dynamic diff analysis, but since the diff
checking globs are hardcoded statically, it means that when we change
any of the dependencies (which are siblings) and then we (obviously will)
forget to update the ci.yaml globs to match said change, then the diff
checking breaks down immediately.
3. Because of `2)` we still need to complete the dynamic diff analysis
CI performance story, but while that is happening I thought this change
could take 5 minutes and yield significant …

ci(github): manually pick the low hanging CI performance fruit

---

weaver/core/relay/Dockerfile
weaver/core/relay/Dockerfile.client
weaver/core/relay/Dockerfile.driver
weaver/core/relay/Dockerfile.server

build(weaver/core/relay): fix container image build due to OpenSSL version

---

CODEOWNERS
MAINTAINERS.md

1. The MAINTAINERS.md file was updated with contact details
2. The CODEOWNERS file was updated so that in addition to the current
code owners Rafael also has ownership of some of the sub-direcotires where
he is the most active in terms of contributions.
3. We welcome Rafael to expand the scope of ownership on packages later
as we are always looking to get more help with maintaining the code. :-)

docs: add Rafael Belchior as a maintainer

---

packages/cactus-common/package.json
packages/cactus-common/src/main/typescript/grpc/is-grpc-status-object-with-code.ts
packages/cactus-common/src/main/typescript/public-api.ts
packages/cactus-common/src/test/typescript/unit/grpc/is-grpc-status-object-with-code.test.ts
yarn.lock

1. User-defined Typescript type-guard function that asserts whether a value or object is a `@grpc/grpc-js` {Partial<StatusObject>} or not. The reason why it checks for {Partial} is because all of the properties of the {StatusObject} are defined as optional for some reason, hence we cannot assume anything about those being present or not by default.
2. Therefore this method will just check if the `code` property is set or not and return `true` or `false` based on that.
3. The above is also the reason why the name of the function is slightly more verbose than your average user-defined type-guard that could be named just "isGrpcStatusObject()" but we wanted to make sure that more specific type-guards can be added later that check for other optional properities or for the presence of all of …

feat(common): add isGrpcStatusObjectWithCode user-defined type guard

---

.gitignore
extensions/cactus-plugin-htlc-coordinator-besu/src/main/typescript/web-services/counterparty-htlc-endpoint.ts
extensions/cactus-plugin-htlc-coordinator-besu/src/test/typescript/integration/plugin-htlc-coordinator/counterparty-htlc-endpoint.test.ts

fix(plugin-htlc-coordinator-besu): add missing HSTS header

---

BUILD.md

---
chore(build.md): update documentation regarding deprecated scripts
```
1. Remove the Youtube video links from Cactus documentation
2. Added Go installation and updated node version
3. Checked for deprecated scripts in the md files
```
fixes: #1272

chore(build.md): update documentation regarding deprecated scripts

---

.github/workflows/test_weaver-asset-exchange-corda.yaml
weaver/samples/corda/corda-simple-application/clients/src/main/kotlin/com/cordaSimpleApplication/client/AssetExchangeManager.kt
weaver/samples/corda/corda-simple-application/scripts/initNetworkId.sh

corda-simple-app: fix typo for partyb twice in initNetworkId.sh

fix(corda-simple-app): use correct bond asset flows and contracts for bond asset exchange

---

tools/docker/supabase-all-in-one/Dockerfile
tools/docker/supabase-all-in-one/README.md
tools/docker/supabase-all-in-one/src/freeze-images.sh
tools/docker/supabase-all-in-one/src/run-supabase.sh

- Use latest supabase and container base versions.
- Use skopeo to freeze images, fetch the containers in separate build phase.
- Add anonymous volume definitions in dockerfile to speedup default runtime.
Closes #3099

feat(supabase-all-in-one): update versions, use skopeo

---

.github/workflows/.dast-nuclei-cmd-api-server.yaml
.github/workflows/actionlint.yaml
.github/workflows/besu-all-in-one-publish.yaml
.github/workflows/cacti-dev-container-vscode-publish.yaml
.github/workflows/ci.yaml
.github/workflows/cmd-api-server-publish.yaml
.github/workflows/connector-besu-publish.yaml
.github/workflows/connector-corda-server-publish.yaml
.github/workflows/connector-fabric-publish.yaml
.github/workflows/corda-4-6-all-in-one-obligation-publish.yaml
.github/workflows/corda-4-7-all-in-one-obligation-publish.yaml
.github/workflows/corda-4-8-all-in-one-obligation-publish.yaml
.github/workflows/dev-container-vscode-publish.yaml
.github/workflows/example-carbon-accounting-publish.yaml
.github/workflows/example-supply-chain-app-publish.yaml
.github/workflows/fabric-all-in-one-publish.yaml
.github/workflows/fabric2-all-in-one-publish.yaml
.github/workflows/geth-all-in-one-publish.yaml
.github/workflows/gg-shield-action.yaml
.github/workflows/ghpkg-all-kotlin-api-clients-publish.yaml
.github/workflows/iroha2-all-in-one-publish.yaml
.github/workflows/keychain-vault-server-publish.yaml
.github/workflows/quorum-all-in-one-publish.yaml
.github/workflows/quorum-multi-party-all-in-one-publish.yaml
.github/workflows/sawtooth-all-in-one-publish.yaml

---
feat(actionlint): fix the errors produced by the ActionLint tool
```
1. Fix errors found by Actionlint on multiple yaml files
2. Temporarily removed test_weaver*.yaml, weaver_deploy*.yml, weaver/ directory in ActionLint
```
fixes: #2651

feat(actionlint): fix the errors produced by the ActionLint tool

---

.github/workflows/dco.yaml

ci(github): add workflow for DCO check

---

GOVERNANCE.md

docs(goveranace): change rocketchat to discord

---

.github/workflows/ci.yaml
.taprc
jest.config.js
packages/cactus-plugin-keychain-memory-wasm/src/test/typescript/unit/plugin-keychain-memory-wasm.test.ts

test(plugin-keychain-memory-wasm): migrate test(s) to Jest from TAP

---

.devcontainer/devcontainer.json

1. This will help us with newer features and also potential CVEs in the
(now) quite outdated version we were using before.

build(devcontainer): upgrade docker engine to v26.x.y in the image

---

.github/workflows/test_weaver-go.yaml
.github/workflows/weaver_deploy_go-pkgs.yml
tools/go-gen-checksum.sh
tools/weaver-update-version.sh
weaver/sdks/fabric/go-sdk/Makefile
weaver/sdks/fabric/go-sdk/asset-manager/assetManager_test.go
weaver/sdks/fabric/go-sdk/helpers/helpers_test.go
weaver/sdks/fabric/go-sdk/interoperablehelper/interoperable-helper.go
weaver/sdks/fabric/go-sdk/interoperablehelper/interoperable-helper_test.go
weaver/sdks/fabric/go-sdk/membershipmanager/membership_manager.go
weaver/sdks/fabric/go-sdk/membershipmanager/membership_manager_test.go
weaver/sdks/fabric/go-sdk/readme.md

- ci(release-go-sdk): use make build to test build of go-sdk
- chore: fix update-weaver-version script typo with quotes
- chore: bug fix in release script go-gen-checksum
- test(go-sdk): change test package names to _test, add membership test
Previous release of `weaver-go-sdk` failed because of a bug in CI.
Also fixed the script `go-gen-checksum` identified in previous release and tested it on Ubuntu and Mac both.
Added test for membership manager of go-sdk in CI, renamed unit test packages with `_test`.

fix(go-sdk): use protos v1 api for fabric-protos-go unmarshal

---

weaver/core/identity-management/iin-agent/package-local.json
weaver/core/identity-management/iin-agent/package.json
weaver/sdks/besu/node/package-local.json
weaver/sdks/besu/node/package.json
weaver/sdks/fabric/interoperation-node-sdk/package-local.json
weaver/sdks/fabric/interoperation-node-sdk/package.json
yarn.lock

Updated mocha to newer versions which do not depend on the old minimatch

fix(security): address CVE-2022-3517 - minimatch < 3.0.5 ReDoS vuln

---

examples/cactus-example-cbdc-bridging-backend/src/fabric-contracts/satp-contract/chaincode-typescript/src/tokenERC20.ts
examples/cactus-example-cbdc-bridging-frontend/package.json
examples/cactus-example-cbdc-bridging-frontend/src/App.tsx
examples/cactus-example-cbdc-bridging-frontend/src/api-calls/besu-api.tsx
examples/cactus-example-cbdc-bridging-frontend/src/api-calls/fabric-api.tsx
examples/cactus-example-cbdc-bridging-frontend/src/api-calls/gateway-api.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/ActionsContainer.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/ApprovalsTable.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/AssetReferencesTable.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/Ledger.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/buttons/CriticalButton.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/buttons/NormalButton.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/dialogs/CrossChainTransferDialog.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/dialogs/MintDialog.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/dialogs/PermissionDialog.tsx
examples/cactus-example-cbdc-bridging-frontend/src/components/docs/DummyActionsContainer.tsx
examples/cactus-example-cbdc-bridging-frontend/src/index.tsx
examples/cactus-example-cbdc-bridging-frontend/src/pages/Helper.tsx
examples/cactus-example-cbdc-bridging-frontend/src/pages/HomePage.tsx
yarn.lock

* Separated Transfer functionality into local blockchain transfers and cross-chain transfers
* Added new table with the state of token approvals made to the bridge
* Highlight cross-chain functionality with red coloring
* Add helper page with instructions on how to use app

docs(cbdc): update frontend to match new functionality

---

tools/pr-commit-parity.js

ci(github): commit parity to use PR title in check 
1. Updated the script to include the check for releases
2. Fixed certain regex and added a new regex for issue/PR
references. This is done because the issue numbers tagged in
PR message or commit messages are sometime resolved directly
and sometimes parsed with the orgname.
3. With the new regex in 2), we can now safely check for parity
while including the fixes/depends line, further loosing the parity
check, thus reducing false-positives
Fixes #3526

ci(github): commit parity to use PR title in check

---

packages/cactus-cmd-api-server/README.md

This came up during a discussion here and I thought it best to document
it a little more thoroughly so that later it can be referenced for others
as well:
https://github.com/hyperledger/cacti/issues/3406#issuecomment-2299654552

docs(api-server): explain local plugin import through packageSrc config

---

package.json
weaver/sdks/fabric/interoperation-node-sdk/package-local.json
yarn.lock

Improper Verification of Cryptographic Signature
https://security.snyk.io/vuln/SNYK-JS-ELLIPTIC-7577916

fix: mitigate CVE-2024-42461 - bump elliptic to v6.5.7

---

weaver/common/protos-js/.npmrc.template
weaver/core/drivers/fabric-driver/.npmrc.template
weaver/core/identity-management/iin-agent/.npmrc.template
weaver/samples/besu/besu-cli/.npmrc.template
weaver/samples/fabric/fabric-cli/.npmrc.template
weaver/sdks/besu/node/.npmrc.template
weaver/sdks/fabric/interoperation-node-sdk/.npmrc.template

fix(weaver): update the npm url in .npmrc to hyperledger-cacti

---

packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-dockerization.test.ts

fix(satp-hermes): remove debugging print leftovers

---

packages/cactus-plugin-satp-hermes/src/main/typescript/blo/dispatcher.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/fabric-contracts/satp-wrapper/chaincode-typescript/src/satp-wrapper.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts

fix(satp-herms): oapi and lint

---

.github/workflows/ci.yaml
.github/workflows/satp-hermes-gateway.yaml
packages/cactus-plugin-satp-hermes/README.md
packages/cactus-plugin-satp-hermes/src/main/typescript/generated/SATPWrapperContract.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/gateway-init-startup.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-dockerization.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways-dockerization.test.ts

ci(satp-hermes): add docker deploy actions

---

packages/cactus-plugin-satp-hermes/src/test/typescript/environments/fabric-test-environment.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/knex.config.ts

fix(satp-hermes): contract and db test path fix

---

.github/actions/copm_test/action.yaml
.github/workflows/ci.yaml
.github/workflows/coverage_ts.yaml
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/fabric-watch-blocks-delegated-sign-v1-endpoint.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/fabric-watch-blocks-v1-endpoint.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/identity-client.test.ts

1. Refactored negative test cases in:
-fabric-watch-blocks-v1-endpoint.test.ts
-fabric-watch-blocks-delegated-sign-v1-endpoint.test.ts
-identity-client.test.ts
Fixes #3472
Peter's Updates:
-----------------
Updated the Cache GitHub Action to v4.2.2 because it started failing
with the current version due to deprecations in the GitHub API.
Signed-off-by: adrianbatuto <adrian.batuto@accenture.com>

test(connector-fabric): refactor jest test negative test cases

---

weaver/core/network/fabric-interop-cc/contracts/interop/manage_assets.go
weaver/core/network/fabric-interop-cc/libs/assetexchange/assetSwapContracts.go
weaver/samples/fabric/simpleassettransfer/tokenasset.go

chore: fix some function names in comment

---

packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage0-client-service.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage2-client-service.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage3-client-service.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage0-server-service.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage3-server-service.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/satp-bridge/besu-bridge.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/satp-bridge/ethereum-bridge.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/satp-bridge/fabric-bridge.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/satp-bridge/network-bridge.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/satp-bridge/satp-bridge-manager.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/bridge/fabric-bridge.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway.test.ts

Added abstract function for merging receipts and implemented it on each bridge;
Logged new receipts for user visualization;
Added e2e test for Fabric to Besu transactions;
Fixed some path mistakes;

fix(satp): check gas usage on satp bridge manager

---

examples/cactus-example-discounted-asset-trade/package.json
package.json
packages/cactus-plugin-ledger-connector-fabric/package.json
packages/cactus-test-tooling/package.json
weaver/sdks/fabric/interoperation-node-sdk/package-local.json
weaver/sdks/fabric/interoperation-node-sdk/package.json
yarn.lock

https://github.com/hyperledger-cacti/cacti/security/dependabot/1388
Fixes #3805

fix(security): address GHSA-vjh7-7g9h-fjfh upgrade elliptic to >=6.6.1

---

packages/cactus-plugin-ledger-connector-ethereum/src/main/typescript/plugin-ledger-connector-ethereum.ts
packages/cactus-plugin-ledger-connector-ethereum/src/test/solidity/hello-world-contract-with-event-emission/HelloWorldWithEvent.json
packages/cactus-plugin-ledger-connector-ethereum/src/test/solidity/hello-world-contract-with-event-emission/HelloWorldWithEvent.sol
packages/cactus-plugin-ledger-connector-ethereum/src/test/typescript/integration/geth-event-subscriber.test.ts

* Added new function to perform event listening in smart contracts
* Added new test file

feat(connector-ethereum): add event listener for smart contracts

---

packages/cactus-plugin-satp-hermes/src/main/typescript/api1/dispatcher.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/logging.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/services/gateway/satp-manager.ts

Connected log levels between files to avoid inconsistencies;

fix(satp): fix log level consistency

---

BUILD.md

Primary change: Isolate the VSCode Dev Container section in BUILD.md
Fixes #874

docs(vscode): high level devcontainer quickstart documentation

---

README.md

docs(readme): updated vscode, licence, openssf, issue badges
--------------
1. Updated the Readme.md to include the updated badges for open in vscode, licence, openssf scorecard and github issues
Fixes #3857

docs(readme): updated vscode, licence, openssf, issue badges

---

.github/workflows/satp-hermes-gateway.yaml

ci(satp-hermes): fix foundryup

---

examples/cactus-example-cbdc-bridging-backend/src/main/typescript/infrastructure/cbdc-besu-environment.ts
examples/cactus-example-cbdc-bridging-backend/src/main/typescript/infrastructure/cbdc-bridging-app-dummy-infrastructure.ts
examples/cactus-example-cbdc-bridging-backend/src/main/typescript/infrastructure/cbdc-fabric-environment.ts
examples/cactus-example-cbdc-bridging-frontend/package.json
packages/cactus-plugin-satp-hermes/src/test/typescript/constants.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/environments/besu-test-environment.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/gateway-blo.test.ts

fix: besu network and cdbc example

---

examples/cactus-example-cbdc-bridging-frontend/package.json
packages/cactus-plugin-satp-hermes/src/main/typescript/plugin-satp-hermes-gateway.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/services/monitoring/monitor.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/unit/shutdown-state.test.ts
yarn.lock

fix(satp-hermes): shutdown test

---

CODEOWNERS
MAINTAINERS.md

docs(maintainers): remove Jagpreet and Peter from active maintainers

---

packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-dockerization.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-with-api-server.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateway-with-api-server.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-dev-dockerization-fast.test.ts

fix(satp-hermes): fix tests

---

packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/bridge/leafs/ethereum-leaf.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/oracle/implementations/oracle-evm.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/environments/ethereum-test-environment.ts

fix(satp-hermes): fix ethereum gasConfigs

---

packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-dockerization.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-with-api-server.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateway-with-api-server.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways-dockerization.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-dev-dockerization-fast.test.ts

fix(satp-hermes): fix final satp docker test

---

packages/cactus-plugin-satp-hermes/package.json
packages/cactus-plugin-satp-hermes/src/main/typescript/api1/dispatcher.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/oracle/implementations/oracle-evm.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/oracle/oracle-execution-layer.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/oracle/oracle-manager.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/services/validation/config-validating-functions/bridges-config-validating-functions/validate-ethereum-config.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/services/validation/config-validating-functions/validate-cc-config.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/constants.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/oracle/oracle-errors.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/oracle/oracle-execute-api-server.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/oracle/oracle-execute-dockerization-fast.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/oracle/oracle-register-api-server.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-1-gateway-dockerization.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/satp-e2e-transfer-2-gateways-dockerization.test.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/unit/cli-validation.test.ts

feat(satp-hermes): new docker image and dockerization test for oracle

---

tsconfig.json

feat(satp-hermes): fix build

---

.github/workflows/satp-hermes-gateway.yaml
packages/cactus-plugin-satp-hermes/src/main/typescript/core/session-utils.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/client/stage1-client-service.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage0-server-service.ts

fix(satp-hermes): fixed session utils and session hashes

---

.github/dco.yaml
.github/workflows/commitlint-pull-request.yaml
.gitignore
commitlint.config.js
commitlint.config.mjs

Adds remediation commits for unsigned commits prior to  Thu Feb 9 09:58:33 2023 -0800 (included).
Context: https://discord.com/channels/905194001349627914/908379338716631050/1396094905834541088
To get unsigned commits run:
`git --no-pager log --pretty=format:"%h %s" --grep="Signed-off-by" --invert-grep
`
Most problematic commits are merge commits (where maintainers clicked the "Merge PR" button), causing a new commit to be added by the CI. Peter knew this and that is one of the reasons rebases were preferred from a certain point. Other commits were deemed hard to correct (for instance commit #1 by @tkuhrt was unsigned and a fix by push forcing to main would re-write the whole project history).
Ideally, we would have explicit authorization from each commit author. However, since many of …

chore(ci): add DCO remediation commits

---

packages/cactus-plugin-satp-hermes/src/main/typescript/core/satp-session.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-handlers/stage0-handler.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-handlers/stage1-handler.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-handlers/stage2-handler.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-handlers/stage3-handler.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/cross-chain-mechanisms/bridge/satp-bridge-execution-layer-implementation.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/services/gateway/gateway-orchestrator.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/services/monitoring/monitor.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/integration/monitoring/functionality.test.ts

fix(satp): quick fix to include environment variables in the monitor url

fix(satp): quick fix to include environment variables in the monitor url

---

.github/workflows/satp-hermes-docker.yaml

ci(satp-hermes): docker build fix

---

packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-handlers/stage0-handler.ts
packages/cactus-plugin-satp-hermes/src/main/typescript/core/stage-services/server/stage0-server-service.ts
packages/cactus-plugin-satp-hermes/src/test/typescript/unit/services.test.ts
packages/cactus-test-tooling/src/main/typescript/github-actions/is-running-in-github-action.ts

fix(satp-hermes): fix bug
